### ISSUE TITLE
Weird dates

### ISSUE THREAD

**Issue by raftheunis87** [Dielee/volvo2mqtt#10]
First of all, I can confirm this is working on a Volvo V60 T8 Polestar Engineered (2023)! So kudos for that!

The only thing that is a bit weird are the dates that I see on mqtt/HA:

<img width="346" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/3533046/e7a3f7f1-638a-4022-84a4-1ceb577035a6">

Do you perhaps have an idea what could be causing this? I'm located in Belgium.

I use the following docker command to run:

`docker run -d --restart unless-stopped --pull=always -e CONF_updateInterval=60 -e CONF_babelLocale='be' -e CONF_mqtt='@json {"broker": "xxx", "username": "xxx", "password": "xxx"}' -e CONF_volvoData='@json {"username": "xxx", "password": "xxx", "vin": "xxx", "vccapikey": "xxx"}' -e TZ='Europe/Brussels' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest`

**Comment by raftheunis87** [comment]
Also, the charging system status is empty so it seems

**Comment by Dielee** [comment]
Please try `CONF_babelLocale='fr_BE'` for the date error.

Charging system status is empty until a cable is plugged in.

**Comment by raftheunis87** [comment]
I used nl_BE, and that fixed it!

<img width="339" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/3533046/9ef99573-f710-40ee-a41a-051cecc67dd5">

The cable is currently plugged in, so it was charging when I installed the add-on. I will try to remove and re-plug the cable :)

**Comment by raftheunis87** [comment]
The "Charging System Status" is not updated so it seems :(

<img width="346" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/3533046/eedfef44-d88f-4e3c-8037-4a42a0da67a3">

**Comment by Dielee** [comment]
Maybe this isn't returned from the api...
I will build a debug version, wait a few minutes.

**Comment by raftheunis87** [comment]
![image](https://github.com/Dielee/volvo2mqtt/assets/3533046/a0036a90-708a-4345-aa21-9cd9ba9f3604)

Seems indeed like no data is returned from the API

**Comment by Dielee** [comment]
Please pull v1.0.9 and set env `-e CONF_debug=true`. This should give you the raw API results. If charging system state contains no data, there is nothing I can do, sorry!

**Comment by raftheunis87** [comment]
`{
  "status" : 200,
  "operationId" : "00d61ca7-8cbd-4382-9e6e-b600d1309b20",
  "data" : {
    "batteryChargeLevel" : {
      "value" : "100.0",
      "unit" : "percentage",
      "timestamp" : "2023-06-20T11:28:54.122Z"
    },
    "electricRange" : {
      "value" : "65",
      "unit" : "kilometers",
      "timestamp" : "2023-06-20T11:28:54.122Z"
    },
    "estimatedChargingTime" : {
      "value" : "17",
      "unit" : "minutes",
      "timestamp" : "2023-06-20T11:28:54.122Z"
    },
    "chargingConnectionStatus" : {
      "value" : "CONNECTION_STATUS_CONNECTED_AC",
      "timestamp" : "2023-06-20T11:28:54.122Z"
    },
    "chargingSystemStatus" : {
      "value" : "CHARGING_SYSTEM_CHARGING",
      "timestamp" : "2023-06-20T11:28:54.122Z"
    }
  }
}`

**Comment by Dielee** [comment]
v1.0.10 is on it's way

**Comment by raftheunis87** [comment]
<img width="337" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/3533046/992739fe-26e1-4f8b-899e-a3596507785c">

Issue resolved! Thanks a lot!

You can also add my car model to the supported list ;)

**Comment by Dielee** [comment]
So whats you car model ?
