### ISSUE TITLE
Homeassistant independance

### ISSUE THREAD

**Issue by schrej-zz** [Dielee/volvo2mqtt#100]
**Is your feature request related to a problem? Please describe.**
This great solution would also be interesting for other smarthome solutions like IOBroker and OpenHAB.

**Describe the solution you'd like**
Rewrite the tool so that it can be installed e.g. as a service and feed other solutions via MQTT.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by schrej-zz** [comment]
OK,
but Docker is a -let's say- additional feature.
I just like to run it as a service in a Proxmox Container.

**Comment by Dielee** [comment]
What do you need to run it inside a proxmox container ?

**Comment by schrej-zz** [comment]
Sorry for the late reply. I'm on vacation.
I think, it's more or less a matter of documentation and editing the conf/json files manually.
I don't use dockers, so I don't know exactly what's happening by calling the docker script.
But for me, on a first glance it seems sufficient to enter the parameters to the according config files and just start main.py. As mentioned in the other issue, homeassistant dependence should be sufficient in the announcement.
The Volvo MQTT topics should be independent from the MQTT listener. I will try after my vacation and might also support with a PR.

**Comment by Dielee** [comment]
This issue will be continued in #102
