### ISSUE TITLE
State topics

### ISSUE THREAD

**Issue by thomasddn** [Dielee/volvo2mqtt#102]
**Is your feature request related to a problem? Please describe.**
Now, `state` topics come somewhere under the `homeassistant/<component>/*` topic.

**Describe the solution you'd like**
 I believe this should come under `volvoAAOS2mqtt/*` because these states have nothing to do with Home Assistant as such. The `config` topics for Home Assistant should then point towards the `state` topics under `volvoAAOS2mqtt/*`. This is also how other applications I have running are doing it.

In #100 someone is asking to run it without Home Assistant. While it is possible to run this solution without it, there would still be (string) references to Home Assistant when someone wants to read data from MQTT. If `state` topics are moved under `volvoAAOS2mqtt/*`, then there is no reference to Home Assistant at all.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Dielee** [comment]
Yeah, this may be an improvement, but not yet on my to-do list, sorry!

**Comment by thomasddn** [comment]
Would you accept a PR? If so, I could have a look at it when I have some spare time.

**Comment by schrej-zz** [comment]
For compatibility reasons, I would suggest to keep "homeassistant" currently as default, but make the topic changeable in the config.

**Comment by thomasddn** [comment]
Could be done by configuring a prefix for where the none-HA topics should come. Something like `volvo_topic_prefix` with a default value of `homeassistant/{component}`, where `{component}` would be replaced with `switch`, `lock`, and so on. The `{component}` part should be optional, so it would not return an error when you use `volvoAAOS2mqtt` as value.

**Comment by thomasddn** [comment]
@Dielee I've created a pull request to fix this issue. Please see details at PR #109.

**Comment by schrej-zz** [comment]
I was able to run the Main.py successfully by just using the src folder ( and requirements.txt). Just edited config.json manually.

**Comment by thomasddn** [comment]
Hi bot! Please be patient, the PR is being tested.
