### ISSUE TITLE
Update README to notify users of new Home Assistant app available on the Google Play Store

### ISSUE THREAD

**Issue by IceBotYT** [Dielee/volvo2mqtt#103]
**Is your feature request related to a problem? Please describe.**
Recently, the Home Assistant team made the Home Assistant companion app available on the AAOS Google Play Store.
![image](https://github.com/Dielee/volvo2mqtt/assets/34712694/d555c889-68d5-42ff-8427-6fbae8017163)
You can also access the realtime location of the car, even while it's moving.

**Describe the solution you'd like**
Please update the README so users can access the realtime location of the car for use in automations and etc

**Describe alternatives you've considered**
The location API only works in certain regions and only updates after a trip is completed, so if the user installs the Home Assistant app on the play store, they can access the location

**Additional context**

**Comment by Dielee** [comment]
This has nothing to do with the Volvo API, so there is nothing I can do for you. Sorry.
