### ISSUE TITLE
Issues running the Add-on (Failed to save add-on configuration, not a valid value.)

### ISSUE THREAD

**Issue by nmcrae85** [Dielee/volvo2mqtt#106]
**Describe the bug**
I Get the error "Failed to save add-on configuration, not a valid value."
Using the latest version of the add-on. Using the GUI to input the data.

Full error here with redacted into 

"Failed to save add-on configuration, not a valid value. Got {'updateInterval': 300, 'babelLocale': 'en_gb', 'TZ': 'Europe/London', 'debug': True, 'disable_logging': False, 'mqtt': {'broker': '192.168.150.26', 'port': 1883, 'username': 'mqtt', 'password': 'REDACTED'}, 'volvoData': {'username': REDACTED, 'password': 'REDACTED', 'vin': '', 'vccapikey': ['REDACTED'], 'odometerMultiplier': 1, 'averageSpeedDivider': 1, 'averageFuelConsumptionMultiplier': 1}}"

**Comment by Dielee** [comment]
Your username have to be string. Please quote it, like the other options.

**Comment by nmcrae85** [comment]
Thanks. Im now getting this error. I can however get into the app and via a web login with the same username and password.

Sep 21 13:59:58 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.8.7
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 58, in authorize
    raise Exception(message["error_description"])

I did also try to build this as a docker container (which worked)

Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Battery Charge Level is supported by your vehicle.
Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Electric Range is supported by your vehicle.
Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Charging System Status is supported by your vehicle.
Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Charging Connection Status is supported by your vehicle.
Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Sep 21 13:51:15 volvo2mqtt [1] - INFO: Success! Odometer is supported by your vehicle.

However I get this error on the mqtt broker...

2023-09-21 13:47:52: ACL denying access to client with dangerous client id "volvoAAOS2mqtt_+447XXXXXXXX" - Note I have changed the number here

**Comment by Dielee** [comment]
This has something to do with your mqtt broker, I can't help you here, sorry!

**Comment by nmcrae85** [comment]
Issue resolved. MQTT brokers dont like + characters in the username :)

**Comment by Dielee** [comment]
Yes, so you changed your username to 00447XXXX ?

**Comment by nmcrae85** [comment]
I actually converted it to email address via the volvo website :)
