### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by mscottco** [Dielee/volvo2mqtt#108]
**Describe the solution you'd like**
It would be nice if there was an option to run this in a read-only mode so that features like controlling the lock state, windows and climate aren't possible.

**Describe alternatives you've considered**
Disabling the entity is an option but for the ultimate security, having it functionally disabled at the add-on level would be preferred.
I also had a look around the Volvo API to see if there was a read-only API key option but couldn't see one.

Thanks for your work on this awesome add-on!

**Comment by Dielee** [comment]
It's not as easy as it sounds.... Maybe I will take a look, but currently I do not have so much time...

**Comment by mscottco** [comment]
Thanks. Using the lock as an example, I'd envisage it would show up as a binary sensor entity instead of a switch so you can still read the status but there's not the option of accidentally unlocking the car.

**Comment by Dielee** [comment]
This seems to be a fronted related problem for me. Maybe take a look at this Lovelace component. (Link)[https://github.com/iantrich/restriction-card]
