### ISSUE TITLE
Polestar

### ISSUE THREAD

**Issue by stephanlarsson** [Dielee/volvo2mqtt#111]
Please excuse me if this is a completely irrelevant question, but are the Volvo AAOS Solution and servers hosting their API vastly different from Polestar?

If not, is it possible to use this HA integration for Polestars? Alternatively can this integration be Branched to access the Polestar API?

Kind regards,

//S

**Comment by Dielee** [comment]
I don't now. Do you have some documentation about the Polestar API ?

**Comment by Dielee** [comment]
This may be possible, but without any documentation, I can't do anything. Sorry!

**Comment by stephanlarsson** [comment]
Ok, thank you for the quick response, and I'll be sure to be back if I find anything at all to support that!
