### ISSUE TITLE
2024 XC90 B5 working

### ISSUE THREAD

**Issue by Kartax** [Dielee/volvo2mqtt#114]
Just wanted to let you know that my **2024 XC90 B5 AWD Mild-Hybrid** is working great while it wasn't with the Volvo On Call integration.

**Comment by Dielee** [comment]
Glad to hear!

**Comment by Rustymage** [comment]
> Just wanted to let you know that my **2024 XC90 B5 AWD Mild-Hybrid** is working great while it wasn't with the Volvo On Call integration.

Does the climate start the engine using this addon?
