### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by jvanderweken** [Dielee/volvo2mqtt#115]
Hello, the addon had worked very fine. But now there aren't still updates? Also in the Volvo App I doesn't see Updates. Do anyone has the same problem?
In the details of mqtt I also doens't see values in the Json code...

**Comment by Dielee** [comment]
Do you have some logs.?

**Comment by jvanderweken** [comment]
I don't know how to find an extract them... and I see now the xc60 updates comes, but still no for the xc40 it like a freeze of the states of this morning

**Comment by Dielee** [comment]
Try restarting the addom

**Comment by jvanderweken** [comment]
I still done more reboota, and rebuild the addon without something has changed...the problem still exits, but there aren't updates in the volvo app...

**Comment by Dielee** [comment]
If there aren't updates in the Volvo app, the addon can't work...

**Comment by jvanderweken** [comment]
[Notes_231024_222406.txt](https://github.com/Dielee/volvo2mqtt/files/13127110/Notes_231024_222406.txt)

I still arrive to exportthe logs, what i can see that the timestamp moves back than to the front and back again...

**Comment by Dielee** [comment]
This is the api timestamp. There is nothing i can do for you. This is a volo api issue.
