### ISSUE TITLE
Energy status not available (Volvo XC40 Recharge 2023 originally from Germany)

### ISSUE THREAD

**Issue by geedsen** [Dielee/volvo2mqtt#116]
Successfully added the integration

But:

![image](https://github.com/Dielee/volvo2mqtt/assets/1316595/48e05376-7ce0-41df-9174-2efb3f68662c)

I thought these should work for European cars?

**Comment by Dielee** [comment]
Which car do you drive ?

**Comment by geedsen** [comment]
XC40 Recharge 2023 (Full electric....) and now reading my previous post I realize it mentions Fuel.  🤭 Should use my reading glasses more often. Sorry for that.

**Comment by geedsen** [comment]
Question? Could there be that the API actually gives more info than the add-on supplies now? Line kWh day use etc?

**Comment by Dielee** [comment]
No, but you can calculate some of those values in HomeAssistant. Take a look at the wiki.

**Comment by geedsen** [comment]
I look into that. Thanks. I noticed the last few days that data from the Volvo just becomes 'Unavailable' for some time. Where could I check what goes wrong. Is the  Volvo api not working, something else? Where would I be able to check that.

**Comment by Dielee** [comment]
This could be an API limit. How many vccapikeys are you using?

**Comment by geedsen** [comment]
Two keys

**Comment by Dielee** [comment]
Try three keys..

**Comment by geedsen** [comment]
I added two more keys two days ago. But I just saw that the states of the XC40 are unavailable for the last two days. Where can I check what is wrong?

**Comment by geedsen** [comment]
Removed the two additional keys and it started working again

**Comment by geedsen** [comment]
It was not the two keys. Apparently  Volvo2MQTT was not started after a reboot (although auto start was on) 
Today I also noticed that the 'plug connected/disconnected' does not seem to work. I was connected. It was  charging and those related entities were all correct. But not the plug, it said disconnected.

**Comment by Dielee** [comment]
Volvo had some API issues the last few days. It has nothing to do with my volvo2mqtt addon. Just be patient, it will work again.

**Comment by geedsen** [comment]
> Volvo had some API issues the last few days. It has nothing to do with my volvo2mqtt addon. Just be patient, it will work again.

The interesting part is that is syas 'Disconnected', but at the same time the Volvo App shows it as connected. I would assume it makes use of the same api.

**Comment by Dielee** [comment]
> Any news on when this API will be out of beta? The portal has v2 as beta tag, which I assume is AAOS integration
> 

No, I don't know anything, as Volvo doesn't answer any of my mails....
