### ISSUE TITLE
The engine status is no longer updated

### ISSUE THREAD

**Issue by kristofferbj** [Dielee/volvo2mqtt#117]
The engine status is no longer updated. The last time the status was engineRunning = true was on October 26th. Since then the timestamp updates when the engine turns on, but not the value:

Oct 29 13:39:41 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Oct 29 13:39:41 volvo2mqtt [106] - DEBUG: Response status code: 200
Oct 29 13:39:41 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "9757dd78-be39-4604-b047-e4bfe98f53e9",
  "data" : {
    "engineRunning" : {
      "name" : "engineRunning",
      "value" : "false",
      "timestamp" : "2023-10-29T10:41:35Z"
    }
  }
}

Oct 29 14:01:57 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Oct 29 14:01:57 volvo2mqtt [106] - DEBUG: Response status code: 200
Oct 29 14:01:57 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "9c89755f-5516-498b-947a-cda5fd728aee",
  "data" : {
    "engineRunning" : {
      "name" : "engineRunning",
      "value" : "false",
      "timestamp" : "2023-10-29T13:00:25Z"
    }
  }
}

I am running the latest version of the add-on.

**Comment by Dielee** [comment]
Jep, same here. As this is an API issue, there is nothing I can do for you at this time... Sorry.

**Comment by macjuju** [comment]
I have a similar experience. Some entity did not update, while the others are updating normally. 
I did a restart to the docker and everything works again.

I spotted that due to I did not see the door closed or locked, while Engine State turned off when I review the logbook card

**Comment by kristofferbj** [comment]
Thanks for the tip. I restarted the add-on and it seems to work right now. Let's see if it continues to work.

**Comment by Dielee** [comment]
Works for me again, too. Strange Volvo API....
