### ISSUE TITLE
Climate / Engine remote start

### ISSUE THREAD

**Issue by ChristianNiklasson** [Dielee/volvo2mqtt#118]
Would it be possible to have two climate activate options?
As it works now as far as I can see is that the climate activation does so with the ”leave in 30 min” option ending up with no engine start.

if it is possible i would also like to have a “leave in 15 min” option that would also start the engine.

**Comment by Dielee** [comment]
I don't know what you want, sorry. If you activate the climate, it will start immediately, until the engine starts, or for 30 minutes.

**Comment by ChristianNiklasson** [comment]
If you in the Volvo app start the climate with a 15 minute delay or less the engine will start.

Id you start the climate with a 20 minute or more delay only the heater will start.

So, the effect will also be that if only the heater is started the heated steering wheel will not activate as well as other electric heated functions such as mirrors and so on.

Therefore if it would be possible to also send the "minutes to leave" information that i assume is sent by the native app with the command to start the climate it would automatically force an engine start...

**Comment by Dielee** [comment]
Ah okay, this is a feature I wasn't aware of.
I can't find any API endpoint to support the feature in the HA Add-on, sorry. Feel free to search on your own!

**Comment by ChristianNiklasson** [comment]
There is apparently a sirect command to start the engine

![image](https://github.com/Dielee/volvo2mqtt/assets/123016613/a820868c-03cb-47a7-bfa1-82c753f704a0)

Documentation found here:

https://developer.volvocars.com/apis/connected-vehicle/v1/specification/

**Comment by Dielee** [comment]
Yes, I know, but without any timer function. This is On/Off.

**Comment by ChristianNiklasson** [comment]
Understand, but i took a look in the Volvo app and there aren't some many time options.

So a engine start option would probably be a 15 minute timer and heater start would then be a 30 min timer.

So just to have the engine start option in the integration would solve the issue the way i was looking for from the start.

**Comment by Dielee** [comment]
As I can't test the engine start endpoint, are you able to test some dev releases ?

**Comment by ChristianNiklasson** [comment]
Sure, might need some guidance for the installation though 🙃

**Comment by Dielee** [comment]
Are you using the HA Add-on?

**Comment by ChristianNiklasson** [comment]
Yep 👍🏻

**Comment by Dielee** [comment]
Are you able to start your engine via the volvo devloper portal ?

**Comment by Rustymage** [comment]
The developer portal apparently has runtime minutes if that's of use here?

```
curl -X 'POST' \
  'https://api.volvocars.com/connected-vehicle/v1/vehicles/TESTVIN/commands/engine-start' \
  -H 'accept: application/vnd.volvocars.api.connected-vehicle.commandinvokeresponse.v1+json' \
  -H 'Content-Type: application/vnd.volvocars.api.connected-vehicle.enginestart.v1+json' \
  -d '{
  "runtimeMinutes": 10
}'
```

**Comment by Dielee** [comment]
The engine start uses runtime in minutes, the climate not.

**Comment by ChristianNiklasson** [comment]
Ah, yes and the max would be 15 minutes then

**Comment by ChristianNiklasson** [comment]
> Are you able to start your engine via the volvo devloper portal ?
> 
> 
> 
> Mine isn't starting: 
> 
> ```
> 
> {
> 
>     "error": {
> 
>         "message": "FORBIDDEN",
> 
>         "description": "Access is denied"
> 
>     }
> 
> }
> 
> ```

I received Error 500 internal Server error

**Comment by Dielee** [comment]
Great... This API is real garbage at this time!

**Comment by Dielee** [comment]
If this won't work, I can't implement the engine start, sorry.

**Comment by ChristianNiklasson** [comment]
So i eas able to start the engine via the Volvo Dev site.

It needed both the VIN and authentication with a token from my Volvo ID and the API Key.

So atleast it works there

**Comment by Rustymage** [comment]
I just checked and using the engine start stop end points, it works for me too.

<img width="776" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/19926955/db3068d8-c22c-42a9-b77b-6e604d8e5f4e">

**Comment by Dielee** [comment]
Nice, I will implement it if I have some spare time.

**Comment by Dielee** [comment]
Are your Cars phevs or mild hybrids ? Or even bevs are working?

**Comment by ChristianNiklasson** [comment]
Mine is Mild-hybrid

**Comment by Rustymage** [comment]
> Are your Cars phevs or mild hybrids ? Or even bevs are working?

Mild hybrid. B5.

**Comment by Dielee** [comment]
So please send me your response from this endpoint:

`https://api.volvocars.com/connected-vehicle/v2/vehicles/<YOUR VIN>/commands`

**Comment by Rustymage** [comment]
```
{
  "data": [
    {
      "command": "LOCK_REDUCED_GUARD",
      "href": "/v2/vehicles/VIN/commands/lock-reduced-guard"
    },
    {
      "command": "LOCK",
      "href": "/v2/vehicles/VIN/commands/lock"
    },
    {
      "command": "UNLOCK",
      "href": "/v2/vehicles/VIN/commands/unlock"
    },
    {
      "command": "ENGINE_START",
      "href": "/v2/vehicles/VIN/commands/engine-start"
    },
    {
      "command": "ENGINE_STOP",
      "href": "/v2/vehicles/VIN/commands/engine-stop"
    }
  ]
}
```

**Comment by Dielee** [comment]
> ```
> {
>   "data": [
>     {
>       "command": "LOCK_REDUCED_GUARD",
>       "href": "/v2/vehicles/VIN/commands/lock-reduced-guard"
>     },
>     {
>       "command": "LOCK",
>       "href": "/v2/vehicles/VIN/commands/lock"
>     },
>     {
>       "command": "UNLOCK",
>       "href": "/v2/vehicles/VIN/commands/unlock"
>     },
>     {
>       "command": "ENGINE_START",
>       "href": "/v2/vehicles/VIN/commands/engine-start"
>     },
>     {
>       "command": "ENGINE_STOP",
>       "href": "/v2/vehicles/VIN/commands/engine-stop"
>     }
>   ]
> }
> ```

Climate isn't supported by your car, interesting. Can you confirm this ?

There is a new feature container available. Please test the engine start feature: 
`ghcr.io/dielee/volvo2mqtt:engine_start_feature`

**Comment by Rustymage** [comment]
> > ```
> 
> > {
> 
> >   "data": [
> 
> >     {
> 
> >       "command": "LOCK_REDUCED_GUARD",
> 
> >       "href": "/v2/vehicles/VIN/commands/lock-reduced-guard"
> 
> >     },
> 
> >     {
> 
> >       "command": "LOCK",
> 
> >       "href": "/v2/vehicles/VIN/commands/lock"
> 
> >     },
> 
> >     {
> 
> >       "command": "UNLOCK",
> 
> >       "href": "/v2/vehicles/VIN/commands/unlock"
> 
> >     },
> 
> >     {
> 
> >       "command": "ENGINE_START",
> 
> >       "href": "/v2/vehicles/VIN/commands/engine-start"
> 
> >     },
> 
> >     {
> 
> >       "command": "ENGINE_STOP",
> 
> >       "href": "/v2/vehicles/VIN/commands/engine-stop"
> 
> >     }
> 
> >   ]
> 
> > }
> 
> > ```
> 
> 
> 
> Climate isn't supported by your car, interesting. Can you confirm this ?
> 
> 
> 
> There is a new feature container available. Please test the engine start feature: 
> 
> `ghcr.io/dielee/volvo2mqtt:engine_start_feature`
> 
> 
> 
> There will be two new entities:
> 
> 
> 
> 1.  Engine Runtime number
> 
> 2.  Engine State switch

I have climate, see photo.

![image](https://github.com/Dielee/volvo2mqtt/assets/19926955/3cfb6df8-41ca-464e-a4db-154a5392183d)

I don't have a start/stop option in the app, however the developer portal climate API doesn't work, yet start/stop does...

Will try the feature when I'm home.

**Comment by Dielee** [comment]
The climate api doesn't work, this is what I wanted to know. 
If you delete the mqtt device in HA and run the new 1.9.0, the climate entity will not even appear anymore,
as it isn't supported by your car.

**Comment by Dielee** [comment]
If you start the climate with "Leave in" minutes, the motor starts immediately?

**Comment by Rustymage** [comment]
> If you start the climate with "Leave in" minutes, the motor starts immediately?

In the Volvo app, yes. The hazards flash and car starts. It stays locked and needs the key and a twist of the internal 'start/stop dial' the fully unlock and allow driving.

**Comment by Dielee** [comment]
Alright, than the changes should do what you want! But I can't test it, as my BEV doesn't support engine start. So if something is not working, please provide debug logs.

**Comment by ChristianNiklasson** [comment]
Could you guide me on how to install the package?

**Comment by Dielee** [comment]
If you are using the HA Addon, there is no way. You have to install dev containers via docker.

**Comment by ChristianNiklasson** [comment]
Noted, so i will just wait for the next uppdate then?

**Comment by Dielee** [comment]
I need some testers... If nobody can test this, I will not merge this into main...

**Comment by Rustymage** [comment]
> I need some testers... If nobody can test this, I will not merge this into main...

I'll take a look when I'm home and get back to you.

**Comment by ChristianNiklasson** [comment]
> I have climate, see photo.
> 
> ![image](https://user-images.githubusercontent.com/19926955/284843592-3cfb6df8-41ca-464e-a4db-154a5392183d.png)
> 
> I don't have a start/stop option in the app, however the developer portal climate API doesn't work, yet start/stop does...
> 
> Will try the feature when I'm home.
> 
> Thank you!

I would say that you dont have the extra fuel warmer on your car, thats why you cant choose more than 15 minutes, in my example i have the diesel warmer that i can use instead of turning the car on.
So the effect will be that the "start climate" will start the dieselwarmer for a 30 min runtime.

So:
1-15 minutes leave time will start the engine.  (/vehicles/{vin}/commands/engine-start)
30 minutes will start the climate (fuel/diesel warmer)

**Comment by Rustymage** [comment]
I'd hope mine didn't have a diesel warmer as it's a petrol ;)

**Comment by Rustymage** [comment]
Here's the log:

```
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Starting volvo2mqtt version v1.9.0
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Using VCCAPIKEY: KEY
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Vin: ['VIN'] found!
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Battery Charge Level (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Battery Charge Level (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Electric Range (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Estimated Charging Time (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Charging System Status (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Charging Connection Status (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Estimated Charging Finish Time (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Odometer (sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Last Data Update (sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Active schedules (sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Window Front Left (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Window Front Right (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Window Rear Left (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Window Rear Right (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Door Front Left (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Door Front Right (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Door Rear Left (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Door Rear Right (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Tailgate (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Engine Hood (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Tank Lid (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Sunroof (binary_sensor) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Failed, Air Conditioning (switch) is unfortunately not supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Engine State (switch) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Leave in (number) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Lock state (lock) is supported by your vehicle.
Nov 22 19:13:40 volvo2mqtt [1] - INFO: Success! Force Update Data (button) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Location (device_tracker) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Tire Front Left (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Tire Front Right (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Tire Rear Left (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Tire Rear Right (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Fuel Level (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Average Fuel Consumption (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Failed, Average Energy Consumption (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Distance to Empty Tank (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Failed, Distance to Empty Battery (sensor) is unfortunately not supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Average Speed (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Hours to Service (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Distance to Service (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Time to Service (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Service warning status (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! Washer Fluid Level warning (sensor) is supported by your vehicle.
Nov 22 19:13:41 volvo2mqtt [1] - INFO: Success! API Backend status (sensor) is supported by your vehicle.
Nov 22 19:13:43 volvo2mqtt [1] - INFO: Sending mqtt update...
Nov 22 19:13:44 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 300 seconds.
Nov 22 19:13:51 volvo2mqtt [1] - ERROR: API Call failed. Status Code: 403. Error: {
  "error" : {
    "message" : "FORBIDDEN",
    "description" : "Access is denied"
  }
}
```

<img width="341" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/19926955/105cd525-3cf2-4334-8adc-5a2e90e67418">

<img width="985" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/19926955/d10ca192-1e86-4d92-a0a7-de3ef76f4f6c">

**Comment by Dielee** [comment]
Okay, we have some API issues. The 403 is the start engine switch ?

**Comment by Rustymage** [comment]
Enabling `CONF_debug` doesn't get me further detail..?

The below just repeats and toggling state doesn't change the output - happy to do something different if asked.

```
Nov 22 19:22:46 volvo2mqtt [1] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 22 19:22:46 volvo2mqtt [1] - DEBUG: Response status code: 200
Nov 22 19:22:46 volvo2mqtt [1] - DEBUG: {

  "data" : {
    "serviceWarning" : {
      "value" : "NO_WARNING",
      "timestamp" : "2023-11-22T16:29:59.366Z"
    },
    "engineHoursToService" : {
      "value" : 598,
      "unit" : "h",
      "timestamp" : "2023-11-22T16:29:59.366Z"
    },
    "distanceToService" : {
      "value" : 42476,
      "unit" : "km",
      "timestamp" : "2023-11-22T16:29:59.366Z"
    },
    "washerFluidLevelWarning" : {
      "value" : "NO_WARNING",
      "timestamp" : "2023-11-22T16:29:59.366Z"
    },
    "timeToService" : {
      "value" : 10,
      "unit" : "months",
      "timestamp" : "2023-11-22T16:29:59.366Z"
    }
  }
}
```

**Comment by Rustymage** [comment]
> Okay, we have some API issues. The 403 is the start engine switch ?

The 403 is a direct response to switching on the state switch.

**Comment by Dielee** [comment]
Aaah, I have a idea, please wait a few minutes.

**Comment by Dielee** [comment]
The `conve:engine_start_stop` scope is missing from the authentication. Unfortunately the authorization against the used endpoint, is returning an error, if this scope is posted. For now, there is no soloution. I will take a look tomorrow.

**Comment by Rustymage** [comment]
> `conve:engine_start_stop`

I'm not following on whether I can assist in posting the scope or how?

What's `conve:engine_start_stop`?

**Comment by Dielee** [comment]
API authentication stuff.. There is nothing you can do at this time, thanks!

**Comment by ChristianNiklasson** [comment]
You have noted that the API needs an access token from your Volvo ID aswell as the VIN and ofcourse the API key?
Seen as the second autorisation below



![image](https://github.com/Dielee/volvo2mqtt/assets/123016613/b03a0dd2-f5e2-4561-8e47-a0dfed2168a9)

The auth. key for the Volvo ID should be on found here:
https://volvoid.eu.volvocars.com/VolvoLogin/login?resumePath=j6dPwGVjUq&client_id=developervcarsdotcom

![image](https://github.com/Dielee/volvo2mqtt/assets/123016613/fc322461-fe53-4fd2-ae60-4bc9291e2cc6)

**Comment by Dielee** [comment]
Yes Sure, I know the API very good at this time. The authorization is missing the `conve:engine_start_stop` scope. I will try my best.

**Comment by Dielee** [comment]
It looks like the needed scope `conve:engine_start_stop` to start and stop the engine isn't working with the used authentication method. I started an app publication at Volvo. Hopefully, they will review my app. If my app is reviewed and published, I have to implement an oauth2 auth flow. If there is something new, I will keep you updated.

**Comment by Dielee** [comment]
UPDATE: I deep dived into the app authentication. There is something new, which I would be able to implement, but this wouldn't fix the access to the "Engine Start" Resource.

**Comment by Dielee** [comment]
> I just checked and using the engine start stop end points, it works for me too.
> 
> <img width="776" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/19926955/db3068d8-c22c-42a9-b77b-6e604d8e5f4e">
> 

Are those endpoints really starting your engine ? Are you able to confirm this ?

**Comment by Rustymage** [comment]
https://github.com/Dielee/volvo2mqtt/assets/19926955/ad9763ea-f6ee-46cb-9248-e92783cef93e

I failed to set a timer and it seems to lock you out after a few attempts of failing to notice a 0 minute run time.

You get the idea.

**Comment by Dielee** [comment]
Alright, thanks. Currently I'm waiting for Volvo to publish my oauth2 app. Hopefully they will do!

**Comment by FireWizard52** [comment]
Hi @Dielee 

You said:

> Currently I'm waiting for Volvo to publish my oauth2 app. Hopefully they will do!

I do not want to disappoint you, but I'm sorry that I have to say:  "They will not approve your application" 

I'm not a Home Assistant user, but I created my first integration of my Volvo to Domoticz, using MQTT, Node-RED and the Python application, created by 'Molobrakos' See: https://github.com/molobrakos/volvooncall. This is the default HA Integration.
When the Extended API and Connected API were published I created another Node-RED flow and tried to get an access code in a legal way and made a request for publication. They never answered. So I deleted my project and created a new one. That was in January this year. Still no answer. Other developers got a negative answer, because the were a person and as such not a legal entity (a company) or had to submit a business plan first.

So if you have further developments in mind, do not wait for Volvo's approval. 

About 2 weeks ago, I saw a question about authorization and I understand your answer.
But also the scope is in the body of the request.
I noticed that they have changed today the scope of the "Fuel" endpoint and there is a new one: "conve:battery_charge_level".
See: https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/fuel/

However adding this scope to the list of scopes in the body gives an error: invalid scope.

So there are still a few issues. Hope this will give you some information, in case question will arrive, that something isn't working anymore

Regards

**Comment by Dielee** [comment]
Thanks for this answer!
So I will stop the publication and implement the new auth flow, I discovered a few days ago to keep this integration alive. Unfortunately the scope, which is needed for the engine start, doesn't work. Maybe it isn't even working, or it isn't working because of their reverse engineered auth method and the used client id. What do you think ? Is it simply not working ? Maybe we can have some more exchange about this topic at discord or something?

**Comment by FireWizard52** [comment]
Hello

> So I will stop the publication

Well, I would leave it, as it is. Some users  (developers at Domoticz)  has got an answer and not what they wanted.
What I wanted to say, do not wait for an approval, as I made my last request January 12, this year and still no answer.
I know, it is not very polite, but that what it is in bigger companies.

> I discovered a few days ago to keep this integration alive. 

That it is interesting, but a lot of things are not stable and not according to what we should expect from the documentation.

1. As you also discovered, trying to start or stop the engine does not work. It gives:

> error: object
> message: "FORBIDDEN"
> description: "Access is denied"

I do not have that option in my Volvo Cars app, so maybe it does not exist for my car.
It is strange, because it is in the list of available commands, if you query the "commands" endpoit

I realized, that the scope doesn't contain "conve:engine_start_stop"
So I added it, but then the Authorization request returns "invalid scope"

2. I removed a lot of unnecessary items from the scope, so that only "openid", and all the conve and energy items remain.
3. Also the header, I modified, so that it only contains the "magic string"
4. I also receive the location data, while "location:read" is not in the scope and while I use the VCC-API-key of the "Connected" API.
5. I get a valid (200) response from the Energy API, but the data object is empty. Probably due to the fact that my car XC40 PHEV 2023 is not supported, yet
6. After The authorization I receive of course an access token and a refresh token, but it indicates "expires_in: 1799.
Strange as all documentation mentioned 1 hour validity for the access token. This is 30 minutes.
So I send a refresh every 20 minutes and that has worked for me. I have a test running now for approx 3 weeks.
7. Also the new discovered scope for the battery_charge_level gives an error, if you add it to the list of scopes.

> Maybe we can have some more exchange about this topic at discord or something?

Yes we can, but in fact the only issue that we (and all other users) have is how to get access to the API in a clean way in order to integrate it with Home Automation systems.
And that all available scopes really give data. 

Regards

**Comment by BernoldNL** [comment]
> Thanks for this answer! So I will stop the publication and implement the new auth flow, I discovered a few days ago to keep this integration alive. Unfortunately the scope, which is needed for the engine start, doesn't work. Maybe it isn't even working, or it isn't working because of their reverse engineered auth method and the used client id. What do you think ? Is it simply not working ? Maybe we can have some more exchange about this topic at discord or something?

@Dielee I am very interested to hear more about that new auth flow. It doesn't look like it's in your code yet. Can you share how it works?
