### ISSUE TITLE
Multiple Cars: Air Conditioning Switch turn both cars on

### ISSUE THREAD

**Issue by christoph-ng** [Dielee/volvo2mqtt#12]
I'Ve got 2 cars, if I put the AC in one car on, the switch gets activated in the other one, too.

```
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting POST call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/commands/climatization-start
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors

```
![image](https://github.com/Dielee/volvo2mqtt/assets/72380789/a0fdc5ab-c507-4813-b5b1-8928bf53da41)

**Comment by Dielee** [comment]
Yes, u are right. Multiple cars driving me crazy...
I will have a look.

**Comment by christoph-ng** [comment]
I will test it ...  by the way, it's working on an XC90 2023 Hybrid T8

**Comment by Dielee** [comment]
Thanks for the response. Releasing a new version.
