### ISSUE TITLE
Addon stops working after installation 1.8.9

### ISSUE THREAD

**Issue by MK040NL** [Dielee/volvo2mqtt#123]
The addon stopped working after the installation of 1.8.9. 

Not sure if I added the expected logging. 

However it looks to me the sunroof valve is causing the issue. 

      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "tailgate" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "tankLid" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    }
  }
}
Nov 09 23:48:05 volvo2mqtt [105] - INFO: Success! Engine Hood is supported by your vehicle.
Nov 09 23:48:05 volvo2mqtt [105] - DEBUG: Response status code: 200
Nov 09 23:48:05 volvo2mqtt [105] - DEBUG: {
  "data" : {
    "centralLock" : {
      "value" : "LOCKED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "frontLeftDoor" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "frontRightDoor" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "rearLeftDoor" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "rearRightDoor" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
Traceback (most recent call last):
    },
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
    "hood" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "tailgate" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "tankLid" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    }
  }
}
Nov 09 23:48:05 volvo2mqtt [105] - INFO: Success! Tank Lid is supported by your vehicle.
Nov 09 23:48:05 volvo2mqtt [105] - DEBUG: Response status code: 200
Nov 09 23:48:05 volvo2mqtt [105] - DEBUG: {
  "data" : {
    "frontLeftWindow" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "frontRightWindow" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "rearLeftWindow" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "rearRightWindow" : {
      "value" : "CLOSED",
      "timestamp" : "2023-11-09T13:40:01.471Z"
    },
    "sunroof" : {
      "value" : "AJAR",
      "timestamp" : "2023-11-09T13:40:01.471Z"
  File "/volvoAAOS2mqtt/volvo.py", line 56, in authorize
    }
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 254, in check_supported_endpoints
  }
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 359, in api_call
    return parse_api_data(data, sensor_id)
}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 486, in parse_api_data
    return door_states[data["sunroof"]["value"]] if util.keys_exists(data, "sunroof") else None
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'AJAR'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ahammas** [comment]
Get the same. Should have looked here before updating…

@Dielee, it’s a great add-on you’ve built. Understand it’s though to backseat drive the connection to Volvo cars when they constantly change things. Neither of the smart power companies in Sweden (eg Greenely and Tibber) has figured out this integration yet but you’ve done it in your spare time. Amazing!

**Comment by Dielee** [comment]
They have added the `ajar` state... 
If it's fully opened or closed, everything works ?

**Comment by ahammas** [comment]
Yes, after activating debug mode I could see that, in my case, the right rear window was slightly open. That's where my oldest daughter sits and she likes to push buttons when she's bored, both physical and parents :). After closing the window the add-on starts up. Good catch!

**Comment by Dielee** [comment]
Please test v1.8.10 :)

**Comment by AlexZuiderwijk** [comment]
> Please test v1.8.11 :)

Just tested with v1.8.11 and window bit opened (XC60 PHEV 2023) and got same AJAR error, see standard logging below:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Nov 11 11:22:40 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.8.11
Nov 11 11:22:41 volvo2mqtt [106] - INFO: Using VCCAPIKEY: ***********************
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Vin: ['*************'] found!
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Battery Charge Level is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Electric Range is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Charging System Status is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Charging Connection Status is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Odometer is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
Nov 11 11:22:42 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 56, in authorize
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 249, in check_supported_endpoints
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 354, in api_call
    return parse_api_data(data, sensor_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 458, in parse_api_data
    return window_states[data["frontLeftWindow"]["value"]] if util.keys_exists(data, "frontLeftWindow") \
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'AJAR'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by Dielee** [comment]
Oh, they added it for windows as well.. good info! I will fix this in the next hour.

**Comment by Dielee** [comment]
Please try v1.8.12!

**Comment by MK040NL** [comment]
For me the add-on is working again. Thanks for the quick update. 

Only my car is still reporting the roof is open, while it is closed. I know it is not the add-on, but who experience the same? Anyone suggestion to solve it. Opening and closing is not working.

**Comment by Dielee** [comment]
> For me the add-on is working again. Thanks for the quick update. 
> 
> Only my car is still reporting the roof is open, while it is closed. I know it is not the add-on, but who experience the same? Anyone suggestion to solve it. Opening and closing is not working. 

Please share this inside the ha community. I will close this issue as solved. Thanks for testing the changes!

**Comment by AlexZuiderwijk** [comment]
> Please try v1.8.12!

Had to wait for the rain to stop before testing :-), but it works again for the open window, thanks!
Unfortunately the sunroof is still always reported as Closed, even when opened, but probably fault at Volvo's side.

What's strange now (not tested before) is when the front-left door is opened the status of both front-left and rear-left doors is open, while at same moment the Volvo app is correctly showing only front-door left as opend (maybe an issue at Volvo's side again....?). 
BTW, it looks like the Volvo app is getting notified the door is opened, as it shows up almost immediately, which is different from querying the current status I guess.
I also tested it with other doors, but those are shown correctly ;-) 

/Alex

**Comment by Dielee** [comment]
> > Please try v1.8.12!
> 
> Had to wait for the rain to stop before testing :-), but it works again for the open window, thanks!
> Unfortunately the sunroof is still always reported as Closed, even when opened, but probably fault at Volvo's side.
> 
> What's strange now (not tested before) is when the front-left door is opened the status of both front-left and rear-left doors is open, while at same moment the Volvo app is correctly showing only front-door left as opend (maybe an issue at Volvo's side again....?). 
> BTW, it looks like the Volvo app is getting notified the door is opened, as it shows up almost immediately, which is different from querying the current status I guess.
> I also tested it with other doors, but those are shown correctly ;-) 
> 
> /Alex

The sunroof is a Volvo issue, sorry! 

The front-left and rear-left issue is my fault. Good find! I will fix this tomorrow morning.
