### ISSUE TITLE
Volvo App 2FA

### ISSUE THREAD

**Issue by Rustymage** [Dielee/volvo2mqtt#124]
I have just recieved this notification - will this impact the app?

![image](https://github.com/Dielee/volvo2mqtt/assets/19926955/0008a7eb-2c6a-43b8-acfa-f1ffc685f5e3)

**Comment by Dielee** [comment]
I hope not, we will see...

**Comment by Rustymage** [comment]
Happy to leave this open while the 2FA is understood to avoid other questions. If you don't want this, feel free to close.
