### ISSUE TITLE
Failed to save add-on configuration, not a valid value.

### ISSUE THREAD

**Issue by iz3man** [Dielee/volvo2mqtt#126]
I got the same issue, no idea what was set wrong ....

Failed to save add-on configuration, not a valid value. Got {'updateInterval': 300, 'babelLocale': 'de_de', 'TZ': 'Europe/Berlin', 'debug': True, 'disable_logging': False, 'mqtt': {'broker': '192.168.1.11', 'port': 1883, 'username': 'mqtt', 'password': 'xxxxx'}, 'volvoData': {'username': 'schxxxxx@xxxxxx.net', 'password': 'xxxxxxx', 'vin': '', 'vccapikey': ['8918exxxxxxxxxxxce7459'], 'odometerMultiplier': 1, 'averageSpeedDivider': 1, 'averageFuelConsumptionMultiplier': 1}}

_Originally posted by @iz3man in https://github.com/Dielee/volvo2mqtt/issues/106#issuecomment-1816508780_

**Comment by Dielee** [comment]
What's the top-level domain of your email ?

**Comment by iz3man** [comment]
izeman.net. But I can set any common TLD like gmail.com, doesn't work either

**Comment by iz3man** [comment]
![image](https://github.com/Dielee/volvo2mqtt/assets/11553674/b65e2380-5ab8-471d-b06c-ce5a72f21ff1)

**Comment by Dielee** [comment]
Why is your vccapikey only 22 chars long ? It have to be 32...

**Comment by iz3man** [comment]
> Why is your vccapikey only 22 chars long ? It have to be 32...

I shorted it when replacing with xxxxx. Didn't count total characters ;)

**Comment by Dielee** [comment]
Please quote your mqtt broker IP and Port ;)

```
  mqtt:
    broker: "192.168.1.11"
    port: "1883"
    username: "mqtt"
    password: "yourPW"
```

**Comment by iz3man** [comment]
> Please quote your mqtt broker IP and Port ;)
> 
> ```
>     broker: "192.168.1.11"
>     port: "1883"
>     username: "mqtt"
>     password: "yourPW"
> ```

Thank you! That solved it. Interestingly it change it back to this after saving:

![image](https://github.com/Dielee/volvo2mqtt/assets/11553674/ba00fa8f-facc-4691-902e-023d397a79b9)

Don't know why I was the first to run into that issue?!

**Comment by iz3man** [comment]
solved. see post above

**Comment by Dielee** [comment]
You aren't the first,  no worries 😄
