### ISSUE TITLE
API v1 deprecated

### ISSUE THREAD

**Issue by RobPijpers** [Dielee/volvo2mqtt#129]
API v1 deprecated

**Comment by RobPijpers** [comment]
Noticed that api v1 is deprecated from

**Comment by Dielee** [comment]
Thanks for sharing! Happily we are already on v2!

**Comment by RobPijpers** [comment]
> Thanks for sharing! Happily we are already on v2!

Good to hear!

**Comment by Dielee** [comment]
Last endpoint moved to v2!
