### ISSUE TITLE
estimated_charging_time does not go to 0

### ISSUE THREAD

**Issue by RobPijpers** [Dielee/volvo2mqtt#133]
The sensor estimated_charging_time counts down to 5 minutes but does not go to 0 even if the battery is fully loaded to 90% and the charging is completed.
I notices this behavior for several previous version to.

**Comment by Dielee** [comment]
Please enable debug and send some logs.

**Comment by RobPijpers** [comment]
> Please enable debug and send some logs.

Sorry for the delay, you fixed the problem even without the logs. 
Thanks!
