### ISSUE TITLE
Reporting supported vehicle 

### ISSUE THREAD

**Issue by ahammas** [Dielee/volvo2mqtt#134]
I connected my V90 2024, T6 PHEV and from what I can tell (after 4h) there are no issues. 

Function/sensors I’m missing are:
-  Estimated Charging Finish Time
-  Estimated Charging Time
-  Charging connection status
-  Charging status

**Comment by Dielee** [comment]
Thanks for sharing. 
These unsupported sensors are from the energy API, which only works for BEVs.
