### ISSUE TITLE
Charging Connection Status problem

### ISSUE THREAD

**Issue by lumichele** [Dielee/volvo2mqtt#135]
Hi,
I'm testing volvo2mqtt on my XC60 2024 PHEV.
I read all parameter except **Charging Connection Status**.

During recharce period I can read these paremeters with correct values :
charging_system_status (Unpecified, Charging, Idle)
estimated_charging_finish_time
estimated_charging_time

In the same period I can read Charging Connection Status but value remain fixed to : Disconnected

Thanks

**Comment by Dielee** [comment]
The `Charging connection status` isn't working for a long time. This is an API issue, there is nothing I can do.
