### ISSUE TITLE
404 error Does not belong to allowed markets"

### ISSUE THREAD

**Issue by chrismelba** [Dielee/volvo2mqtt#136]
**Describe the bug**
Error 404 means no results (particularly battery) are visible

I understand that there may be nothing you can do about this, just wanted to raise it to see if there's an alternative endpoint.

Version:
Current version: 1.8.19

The version you are using and the method you are using (Docker container/HA Addon/Cloned repo)
HAOS addon

**Logs**:<br>
Nov 24 12:31:53 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 24 12:31:53 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 24 12:31:54 volvo2mqtt [106] - DEBUG: Response status code: 404
Nov 24 12:31:54 volvo2mqtt [106] - DEBUG: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }
}
Nov 24 12:31:54 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Does not belong to allowed markets"
  }

**Comment by macjuju** [comment]
I would add some more information on that.

My last reading from API is around 14 hours ago. After that all returned "Does not belong to allowed markets"
Seems there are some changes on APIs. :-(

**Comment by Dielee** [comment]
Sorry guys. This are API changes by Volvo. I can't do anything for you. Please discuss this at the HomeAssistant thread, not here.

**Comment by cmccambridge** [comment]
(For future readers, that conversation about Volvo side API changes disabling access for US cars starts approx here: https://community.home-assistant.io/t/volvo2mqtt-connect-your-aaos-volvo/585699/193)

**Comment by 19belmont** [comment]
In Aus too :(
