### ISSUE TITLE
Entities are not created in home assistant

### ISSUE THREAD

**Issue by catafalarda** [Dielee/volvo2mqtt#137]
In home assistant the entities are not created, I followed all the steps and it connects to Volvo but then in devices I find nothing

The Log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Nov 25 18:27:23 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.8.19
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Using VCCAPIKEY: 3c8c3fd0118c4938b2b4a7ecd9797fd0
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Vin: ['LYVUZK9V7PB220637'] found!
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Odometer is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Window Front Left is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Window Front Right is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Window Rear Left is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Window Rear Right is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Door Front Left is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Door Front Right is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Door Rear Left is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Door Rear Right is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Tailgate is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Engine Hood is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Tank Lid is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Sunroof is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Lock state is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Location is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Tire Front Left is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Tire Front Right is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Tire Rear Left is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Tire Rear Right is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Fuel Level is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Average Fuel Consumption is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Average Energy Consumption is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Distance to Empty Tank is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Failed, Distance to Empty Battery is unfortunately not supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Average Speed is supported by your vehicle.
Nov 25 18:27:24 volvo2mqtt [106] - INFO: Success! Hours to Service is supported by your vehicle.
Nov 25 18:27:25 volvo2mqtt [106] - INFO: Success! Distance to Service is supported by your vehicle.
Nov 25 18:27:25 volvo2mqtt [106] - INFO: Success! Time to Service is supported by your vehicle.
Nov 25 18:27:25 volvo2mqtt [106] - INFO: Success! Service warning status is supported by your vehicle.
Nov 25 18:27:25 volvo2mqtt [106] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Nov 25 18:27:25 volvo2mqtt [106] - INFO: Success! API Backend status is supported by your vehicle.
Nov 25 18:27:27 volvo2mqtt [106] - INFO: Sending mqtt update...
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 16, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 219, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 226, in update_car_data
    last_data_update = format_datetime(datetime.now(util.TZ), format="medium", locale=settings["babelLocale"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/dates.py", line 719, in format_datetime
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 319, in parse
    parts = parse_locale(identifier, sep=sep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 1204, in parse_locale
    raise ValueError(f"expected only letters, got {lang!r}")
ValueError: expected only letters, got 'it-it'

I can't find the devices in Mqtt,

**Comment by Dielee** [comment]
Your babel locale is wrong. `it-it` is invalid, as shown in the log. Please use `it_IT`!

**Comment by catafalarda** [comment]
![pol](https://github.com/Dielee/volvo2mqtt/assets/97560751/e5dee434-d655-4a67-9e50-870c0d742d5a)

**Comment by Dielee** [comment]
It is wrong. You are using `it-IT`. Please use `it_IT`

**Comment by catafalarda** [comment]
SORRY !!!!!! 
Now it's fine, no more errors!!!

**Comment by Dielee** [comment]
No problem! Have fun!
