### ISSUE TITLE
API calls failing, "Does not belong to allowed markets"

### ISSUE THREAD

**Issue by diatonic** [Dielee/volvo2mqtt#138]
**Describe the bug**
Integration stopped working, all items say "unfortunately not supported by your vehicle."

I've had this integration working for quite some time, suddenly all items are failing saying "Does not belong to allowed markets". I noticed this after the latest update to 1.8.19, but I still had the same issue after reverting to older versions.

I've been using this with a 2023 Volvo C40 Recharge BEV

Snippet in log:

    Nov 25 13:04:52 volvo2mqtt [106] - INFO: Failed, Average Speed is unfortunately not supported by your vehicle.
    Nov 25 13:04:52 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
    Nov 25 13:04:53 volvo2mqtt [106] - DEBUG: Response status code: 404
    Nov 25 13:04:53 volvo2mqtt [106] - DEBUG: {
      "error" : {
        "message" : "NOT_FOUND",
        "description" : "Does not belong to allowed markets"
      }
    }
    Nov 25 13:04:53 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
      "error" : {
        "message" : "NOT_FOUND",
        "description" : "Does not belong to allowed markets"
      }
    }
**Expected behavior**:<br>
In the past I could monitor the state of my vehicle charge, doors, climate. Now everything reports "Unknown"

**Screenshots**:<br>
<img width="512" alt="Screenshot 2023-11-25 at 1 28 11 PM" src="https://github.com/Dielee/volvo2mqtt/assets/1490527/29715388-8975-4742-9d54-4ce0fc7a3ebe">

**Version info**:<br>
1.8.19 HA Add-on

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
[volvo2mqtt.log](https://github.com/Dielee/volvo2mqtt/files/13465168/volvo2mqtt.log)

**Comment by gottfriedlechner** [comment]
Same here (I'm in Australia with a XC40 BEV 2022) and I assume this is caused by a change of the API on Volvo's side (would be great to confirm).
The [API documentation](https://developer.volvocars.com/apis/connected-vehicle/v2/overview/) says
> However, when published, only cars in the Europe / Middle East / Africa regions are available.

And the [list of supported locations](https://developer.volvocars.com/terms-and-conditions/apis-supported-locations/) does not include Australia (and also not the US as described in #139).

The API documentation also states
> We are working to bring other regions online.

Sounds as we have to wait for Volvo...

**Comment by Dielee** [comment]
Same as #136. This is not a volvo2mqtt issue, sorry guys!

**Comment by 19belmont** [comment]
Just to be clear, the "published" reference is for when an app using the API is published (i.e. released to the public via, say, an App Store), not when the API is published (i.e. available for experimenting/testing, which is explicitly allowed worldwide according to the same page). Generally, "apps" created with credentials used by Volvo2MQTT are not ever "published" in the sense Volvo is using.

**Comment by 19belmont** [comment]
> Any workaround for this? In Australia and would love to be able to use this.

Unfortunately not that I've seen so far. Volvo has been silent to my previous attempt to reach out, I might try again. Very frustrating as I was just getting it all set up.

I've not bothered to reset the API credentials, I don't think that will help.
