### ISSUE TITLE
Add HAOS Addon - testers needed!

### ISSUE THREAD

**Issue by Dielee** [Dielee/volvo2mqtt#14]
As I don't have any HA OS instances, I can't test the add-on. 
Maybe someone could help me test the add-on ?
Please comment if you are able to help.

**Comment by amurray81** [comment]
Hi, Im able but will be out for until tomorrow evening now.

**Comment by Travikxs** [comment]
I am not an expert, just a user, but if I can help with something, here I am

**Comment by sschouten** [comment]
i can try to test it for you

**Comment by Dielee** [comment]
So, it's up and running. Please test!

**Comment by sschouten** [comment]
locks like it is working: 
<img width="614" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/9618c2b6-6cb4-4014-bd87-27cd758135fd">

<img width="527" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/b15564d9-af1a-4176-b478-f4bcab3d1504">

**Comment by Dielee** [comment]
Nice!

**Comment by amurray81** [comment]
@sschouten would you mind posting a screen grab of your configuration page with full details omitted obviously, just for syntax

for broker I have entered mqtt://192.168.0.xxx, no user name or password for now

Also is the Volvo username and pass the info for the volvo app, or is it the username/pass for the API site ?

Thanks

**Comment by sschouten** [comment]
hey this is my settings

<img width="384" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/3d18547b-425c-41e2-93a7-1403f2bdbff6">

**Comment by amurray81** [comment]
think my issue is API side related, If I use website I can manually access all information except the Get vehicle details function.

It results in the same error given in the add on log
![image](https://github.com/Dielee/volvo2mqtt/assets/130550172/d9679821-a8ce-4632-98bb-8264c205d20c)

Very strange as I can get all other APIs to work via site using VIN

**Comment by Dielee** [comment]
Okay, do you have the option to run a prebuild on a docker host without a HA Addon ?

**Comment by amurray81** [comment]
Afraid not, only HA OS here,

Is there anyway I can manually edit a yaml or py locally to temporarily remove the call for

VEHICLE_DETAILS_URL = "https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}"

and the 

def create_ha_devices():
    for vin in volvo.vins:
        car_details = volvo.api_call(VEHICLE_DETAILS_URL, "GET", vin)
?

No worries if not, someone else may be able to help in time.

**Comment by Dielee** [comment]
No, I have to build a new version. Will take a look later or tomorrow.

**Comment by Dielee** [comment]
Done. Please test version 1.1.2!

**Comment by amurray81** [comment]
Hi, 

Pulling data now but I don't have a device or card in mqqt. I'm not home so can't do much more until tonight

` "status" : 200,
  "operationId" : "16978807-7d6f-4b7b-93ba-xxxxxxxxx",
  "data" : {
    "batteryChargeLevel" : {
      "value" : "30.0",
      "unit" : "percentage",
      "timestamp" : "2023-06-22T09:03:12.186Z   `

Thanks for for updating

**Comment by Dielee** [comment]
Are you sure ? The mqtt device should be "Volvo - {yourVIN}". Please recheck!

**Comment by amurray81** [comment]
Hi
All up and running now. Previously my mqtt was configured without a user but now I read anonymous connections are no longer allowed. 
I set this up and how everything is working great.

Thanks so much
