### ISSUE TITLE
Location history not available

### ISSUE THREAD

**Issue by Vinisz** [Dielee/volvo2mqtt#141]
Hi,

Thanks for this , works like a charm, there's only one thing I'm missing.
I can view location of the vehicle without any problem, however, I'm not able to see any history of the location and als no logbook entries of the past.
Any idea what can be the cause of this ?

**Comment by Dielee** [comment]
You mean the HomeAssistant logbook ?

**Comment by Vinisz** [comment]
Kind of, when I click on the "location" of the car i get below...
As you can see, location is there but no history and no log of past locations.
I'm not sure if this is a "HA" thing or not, but I can see an track history of iphones for example (like my kids)

![image](https://github.com/Dielee/volvo2mqtt/assets/49644964/084405d8-455f-4809-9b56-c09e2c7e8a8f)

**Comment by Dielee** [comment]
For me, this works very well. I can't reproduce this issue, sorry!
Try to delete the whole mqtt device and restart the volvo2mqtt addon.

![2023-11-29 14_58_17-Übersicht – Home Assistant](https://github.com/Dielee/volvo2mqtt/assets/45101649/3bcecd8c-136f-48b7-8334-a5e44d7cf929)

**Comment by Rustymage** [comment]
Works for me to. Did a restart work?
