### ISSUE TITLE
Implementation as Integration instead of MQTT

### ISSUE THREAD

**Issue by exbachi** [Dielee/volvo2mqtt#143]
**Is your feature request related to a problem? Please describe.**
I'm curious about the reasons to implement this as an extra service and connect it via MQTT to HA instead of implementing an integration. I assume there are good reasons, but normally i would prefer a direct integration to be able to implement services and get keep my list of add-ons as short as needed.

**Describe the solution you'd like**
I would like to use your code to implement a integration and contribute this. I'm curious if I overlook some issues with this idea and if there is any demand for it?

**Comment by Dielee** [comment]
Feel free to build a direct component, but there is already something under development. [Link](https://github.com/fars-fede-fire/volvoaaos)
