### ISSUE TITLE
Question about "authorize()"

### ISSUE THREAD

**Issue by ktn001** [Dielee/volvo2mqtt#144]
I would like to create a plugin like this one for Jeedom (an other home automation: https://jeedom.com/en/).

But first, I do have to understand how to connect to Volvo API.

I read your code in `volvo.py` and show that your code do not correspond to the case documented on https://developer.volvocars.com/apis/docs/authorisation/

As I understand, the method documented on developper.volvocars.com is not adapted for our usage so I will follow your example.

Could you explain how do you get the key used on `volvo.py` line 35 ?
I would also appreciate if you have some link to a documentation to the method you use. 
 
Thanks

**Comment by Dielee** [comment]
This endpoint is reverse engineered from the app. Currently reverse engineered auth works also for the api.
As of this, I will not give you any advice, sorry.
 
So it works as it is, but, I saw that Volvo already changes the auth mechanism.  Maybe this will not work anymore in a few weeks. 

Currently I'm trying to publish a official app at the Volvo developer portal. Waiting for more than 14 days, without any response...

**Comment by ktn001** [comment]
Thank you for your answer and for your work.

I will use the same endpoint and the same key as you while waiting for a possible evolution of the authentication mechanism by Volvo.

I will probably also try to publish an official app bur this is to hourly for me.
