### ISSUE TITLE
3 more endpoints

### ISSUE THREAD

**Issue by Ilpo55** [Dielee/volvo2mqtt#145]
It would be useful if Volvo would add 3 more endpoints:
1. Climate status
2. Schedule charging on/off
3. Schedule charging times

Those are not issues of volvo2mqtt, so Could there be Discussions tab in here?

Very nice work Dielee.

**Comment by Dielee** [comment]
Climate Status is already there, not as a sensor, but the climate switch represents the climate state. 

Schedule for charging and times are currently not supported by the API. These features are currently only working over the app.

**Comment by Dielee** [comment]
And thanks for the coffee ☕

**Comment by Ilpo55** [comment]
I mean:
If set the Climate on by Volvo Cars app it wil not change the status of climate, that is why I would like to have the sensor.
And yes it is not the issue of volvo2mqtt.

**Comment by Dielee** [comment]
Yes, this is because there is no Info about the climate state. The climate state which is displayed in ha, is always assumed.

**Comment by Ilpo55** [comment]
What do you think about the "Discussions tab" like here under:
![disc](https://github.com/Dielee/volvo2mqtt/assets/120249692/852313b2-a4d3-4b69-97b8-c812a4ad7f32)
