### ISSUE TITLE
Failed to rebuild add-on 

### ISSUE THREAD

**Issue by cperuffo3** [Dielee/volvo2mqtt#146]
I keep getting an error on either re-install or rebuild:

"Failed to rebuild add-on
The command '/bin/ash -o pipefail -c pip install -r requirements.txt' returned a non-zero code: 1"

when attempting to start the add-on I cannot see any logs or anything else and the add-on fails to start with the error:

Failed to start add-on
Image 982ee2c4/aarch64-addon-volvo2mqtt:1.8.20 does not exist for addon_982ee2c4_volvo2mqtt

**To Reproduce**:<br>

Happened while troubleshooting some volvo API permissions but seems unrelated. Originally appeared after removing the add-on and trying to re-install it. After restoring a prior backup this also happens when trying to rebuild the add-on

**Expected behavior**:<br>
The add-on should rebuild successfully and restart.

**Screenshots**:<br>
![Screenshot 2023-12-12 224234](https://github.com/Dielee/volvo2mqtt/assets/87686305/9f1bdda5-6d75-4a8c-a42f-0116ea7629c8)

![Screenshot 2023-12-12 224750](https://github.com/Dielee/volvo2mqtt/assets/87686305/d03905cb-4ff6-49d6-83c4-d9188980982f)

**Version info**:<br>
Using latest HA (happened on previous version as well (11.4))
Add-on version 1.8.20

**Logs**:<br>
It doesnt appear any logs are being generated because the add-on is not able to start.

**Comment by rvbaelen** [comment]
I got the same error message "The command '/bin/ash -o pipefail -c pip install -r requirements.txt' returned a non-zero code: 1" when trying to install the addon V1.8.20

Home Assistant

    Core 2023.12.1
    Supervisor 2023.11.6
    Operating System 11.2
    Frontend 20231208.2

**Comment by KatrinSchaper** [comment]
Same problem here
<img width="643" alt="Screenshot 2023-12-13 at 10 27 27" src="https://github.com/Dielee/volvo2mqtt/assets/108092307/0a97b642-bd55-4f94-bee8-8d1a3fc2a463">

**Comment by Dielee** [comment]
Please share some supervisor logs from the installation

**Comment by cperuffo3** [comment]
I’ve attached the full supervisor logs to this post but the summary log doesn’t seem to show any additional information.

[home-assistant_2023-12-13T11-51-00.577Z.log](https://github.com/Dielee/volvo2mqtt/files/13660347/home-assistant_2023-12-13T11-51-00.577Z.log)

![IMG_2932](https://github.com/Dielee/volvo2mqtt/assets/87686305/ff0ce739-8233-4d48-9cdb-36607858cb15)

**Comment by KatrinSchaper** [comment]
Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 12 December 2023 at 20:43:48 (7 occurrences)
Last logged: 10:27:14

Failed to to call /store/repositories - Can't add https://github.com/Dielee/volvo2mqtt, already in the store
Failed to to call /addons/982ee2c4_volvo2mqtt/install - The command '/bin/ash -o pipefail -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by cperuffo3** [comment]
I now realized you asked for supervisor logs which... in hindsight.... provide WAY more useful information:)

Find these below:

23-12-13 09:01:00 ERROR (MainThread) [supervisor.docker.addon] Can't build 982ee2c4/aarch64-addon-volvo2mqtt:1.8.20: The command '/bin/ash -o pipefail -c pip install -r requirements.txt' returned a non-zero code: 1
23-12-13 09:01:00 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> d524bbcac2d5

Step 3/15 : RUN apk add --no-cache python3 bash py3-pip


 ---> Using cache

 ---> 3b4685aef11d

Step 4/15 : WORKDIR /volvoAAOS2mqtt


 ---> Using cache

 ---> 62913c1f9701

Step 5/15 : RUN wget --no-cache https://raw.githubusercontent.com/Dielee/volvo2mqtt/main/requirements.txt


 ---> Using cache

 ---> 4ca63382c841

Step 6/15 : RUN pip install -r requirements.txt


 ---> Running in 74ebbdee88fe

error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Removing intermediate container 74ebbdee88fe
[supervisor_2023-12-13T14-01-31.360Z.log](https://github.com/Dielee/volvo2mqtt/files/13661502/supervisor_2023-12-13T14-01-31.360Z.log)

**Comment by Dielee** [comment]
Are you using an rpi ?

**Comment by cperuffo3** [comment]
> Are you using an rpi ? And which python version ?

Yes I’m using an RPI on a standard default HASS install. 

whatever version is in Core 2024.12.1 …. I think it’s 3.12?

**Comment by Dielee** [comment]
This is a python 3.11 issue... https://community.home-assistant.io/t/custom-addon-pep668-compliance/654786/2
I will take a look tomorrow how this is fixable.

**Comment by jorgel272** [comment]
Same error here, wanted to start with this awesome integration. I am running HassOS.

Core 2023.12.2
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2
Python 3.11

Looking forward to a fix, let me know if I can test something for you.

**Comment by Dielee** [comment]
Please test v1.8.21!

**Comment by jorgel272** [comment]
Awesome! I've just tested the new version, it's works correctly. I am able to install it without any errors.

**Comment by rvbaelen** [comment]
I'm also able to install without any errors. I did notice that some endpoints are not supported... but they should be? XC40 nl_BE 

Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your

**Comment by Dielee** [comment]
> I'm also able to install without any errors. I did notice that some endpoints are not supported... but they should be? XC40 nl_BE
> 
> Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle. Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle. Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle. Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle. Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle. Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle. Dec 14 10:37:27 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your

This looks like there are some api issues. But please don't hijack this thread for your needs.
