### ISSUE TITLE
energy api not working?

### ISSUE THREAD

**Issue by rvbaelen** [Dielee/volvo2mqtt#147]
**Describe the bug**
I cannot get energy api related endpoints. log's show not supported by your vehicle.
Other endpoints work just fine.

**Expected behavior**:<br>
load endpoints since region (EU/Belgium) is correct set to nl_BE, timezone is set to Europe/Brussels
Vehicle type XC40 Recharge (2024)

**Version info**:<br>
HA addon 1.8.21

**Logs**:<br>
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Odometer is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Window Front Left is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Window Front Right is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Window Rear Left is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Window Rear Right is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Door Front Left is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Door Front Right is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Door Rear Left is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Door Rear Right is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Tailgate is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Engine Hood is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Tank Lid is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Sunroof is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Lock state is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Location is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Tire Front Left is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Tire Front Right is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Tire Rear Left is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Tire Rear Right is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Average Speed is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Hours to Service is supported by your vehicle.
Dec 14 11:04:13 volvo2mqtt [106] - INFO: Success! Distance to Service is supported by your vehicle.
Dec 14 11:04:14 volvo2mqtt [106] - INFO: Success! Time to Service is supported by your vehicle.
Dec 14 11:04:14 volvo2mqtt [106] - INFO: Success! Service warning status is supported by your vehicle.
Dec 14 11:04:14 volvo2mqtt [106] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Dec 14 11:04:14 volvo2mqtt [106] - INFO: Success! API Backend status is supported by your vehicle.<br>

<b>

**Comment by Dielee** [comment]
Please enable debug and send some logs

**Comment by rvbaelen** [comment]
DEBUG: VCCAPIKEY <REDACTED> works!
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: [{'key': '<REDACTED>', 'extended': False, 'extended_until': None, 'in_use': False}]
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Using VCCAPIKEY: <REDACTED>
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: [{'key': '<REDACTED>', 'extended': False, 'extended_until': None, 'in_use': True}]
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Vin: ['<REDACTED>'] found!
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "c7fec1c4-c31a-4c86-873c-e471b8ed720b",
  "data" : { }
}
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "data" : { }
}
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "c7fec1c4-c31a-4c86-873c-e471b8ed720b",
  "data" : { }
}
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "c7fec1c4-c31a-4c86-873c-e471b8ed720b",
  "data" : { }
}
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "c7fec1c4-c31a-4c86-873c-e471b8ed720b",
  "data" : { }
}
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "c7fec1c4-c31a-4c86-873c-e471b8ed720b",
  "data" : { }
}
Dec 14 10:24:40 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Dec 14 10:24:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "c7fec1c4-c31a-4c86-873c-e471b8ed720b",
  "data" : { }
}

**Comment by Dielee** [comment]
The api returns no valid data, so volvo2mqtt says the sensor is unavailable. 
This is an api issue, i can't do anything for you.
