### ISSUE TITLE
Volvo V90 T6 Recharge MY22,5 || Working

### ISSUE THREAD

**Issue by coolximi** [Dielee/volvo2mqtt#150]
Hey 

First of all thank you i was planning to write it my self but then i found your integration witch did al the work for me.
I wanted to let you know it is working for my Volvo V90 T6 Recharge MY 22,5.

the only issue i found is Charging Connection Status is disconnected but the car is plugged in and charging.
<img width="415" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/8785071/fddd13b4-8aaf-4017-b444-8c9039b5db2e">
<img width="427" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/8785071/7d331541-e8aa-403e-974a-13d250d2af89">

first draft of my HA dashboard
![image](https://github.com/Dielee/volvo2mqtt/assets/8785071/891e0ac9-8e2e-4af4-a661-3c830aa6fe32)

**Comment by Dielee** [comment]
This isn't working at this time. Please take a look at #135.
