### ISSUE TITLE
Volvo extra Api endpoints 

### ISSUE THREAD

**Issue by coolximi** [Dielee/volvo2mqtt#151]
Hello Dielee

Thanks again for all your hard work.
I have been playing arround with the volvo api the last few days. i found one more endpoint that is not yet in you library that could be interesting ;-) .

Api call -> "/connected-vehicle/v2/vehicles/$vin/warnings"
https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/warnings/

here is the return i get from the api (V90 T6 Recharge MY 22,5)

{
  "data": {
    "brakeLightCenterWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "brakeLightLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "brakeLightRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "fogLightFrontWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "fogLightRearWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "positionLightFrontLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "positionLightFrontRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "positionLightRearLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "positionLightRearRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "highBeamLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "highBeamRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "lowBeamLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "lowBeamRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "daytimeRunningLightLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "daytimeRunningLightRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "turnIndicationFrontLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "turnIndicationFrontRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "turnIndicationRearLeftWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "turnIndicationRearRightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "registrationPlateLightWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "sideMarkLightsWarning": {
      "value": "NO_WARNING",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "hazardLightsWarning": {
      "value": "UNSPECIFIED",
      "timestamp": "2024-01-01T15:54:24.008Z"
    },
    "reverseLightsWarning": {
      "value": "UNSPECIFIED",
      "timestamp": "2024-01-01T15:54:24.008Z"
    }
  }
}

with kind regards
maxime

**Comment by Dielee** [comment]
Ah, nice. Another API change. 
I will implement this if I have some spare time available.

**Comment by coolximi** [comment]
Great if you need any help for testing let me know.

**Comment by FireWizard52** [comment]
Hi @Dielee,

You wrote:

> Ah, nice. Another API change.

No, this is not a recent change.
This endpoint (https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/warnings/#get-warnings) monitors all available bulbs  In totally 23 bulbs. I paid not much attention to it, as my car shows for all "UNSPECIFIED".

I do not know why, but believe me, my car has lights :)

Happy New Year

**Comment by Dielee** [comment]
Pretty sure this endpoint delivers this data not for a long time. While I started the development of this component, the warnings endpoint were pure garbage. But yes, it's maybe not very recent. 

Happy new Year, too!

**Comment by Dielee** [comment]
This feature is available starting v1.8.24!

**Comment by coolximi** [comment]
Hey Great

ill test it once i'm back from holiday !

with kind regards
maxime
