### ISSUE TITLE
Add-On does not start

### ISSUE THREAD

**Issue by Ilpo55** [Dielee/volvo2mqtt#152]
It was working ok, until today 10:35

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Jan 02 15:43:25 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.8.22
Jan 02 15:43:26 volvo2mqtt [106] - INFO: Using VCCAPIKEY: xxxxxxxx..
Jan 02 15:43:26 volvo2mqtt [106] - INFO: Vin: ['yyyyyy..'] found!
Jan 02 15:43:26 volvo2mqtt [106] - INFO: Success! Battery Charge Level is supported by your vehicle.
Jan 02 15:43:26 volvo2mqtt [106] - INFO: Success! Electric Range is supported by your vehicle.
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 57, in authorize
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 252, in check_supported_endpoints
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 382, in api_call
    return parse_api_data(data, sensor_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 457, in parse_api_data
    charging_system_state = charging_system_states[data["chargingSystemStatus"]["value"]]
                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'CHARGING_SYSTEM_SCHEDULED'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
They added a new charging system state... I will fix this, wait a few minutes.

**Comment by Dielee** [comment]
Please try v1.8.23!

**Comment by Ilpo55** [comment]
Works now.
Thanks, coffee is waiting for you.

Is the there a new endpoint CHARGING SYSTEM SCHEDULED 
Should it be visible?

**Comment by Dielee** [comment]
No new endpoint, just a new state for the charging system status.

**Comment by kentskoglund** [comment]
That did the trick for me. Updated to v1.8.23 and everything looks OK. Thanks!

**Comment by coolximi** [comment]
Did the trick for me as well  Thank you ;-).

**Comment by Dielee** [comment]
> Works now.
> Thanks, coffee is waiting for you.
> 

And thanks for the coffee!!
