### ISSUE TITLE
Only a few of the available entities are pulled to Home Assistant

### ISSUE THREAD

**Issue by paalkr** [Dielee/volvo2mqtt#155]
**Describe the bug**
Volvo2mqtt runs fine and publish data to my mqtt broker each minute, no error messages in the logs. But unfortunately the volvoAAOS2mqtt topic does not contain config for all entities. Home Assistant will only pull in data from topics described in the volvoAAOS2mqtt topic for each domain (sensor, binaray_sensor, switch, lock, device_tracker).

As seen in the screenshot from mqttexplorer, only the doors and engine_state binary sensors contains configuration under the volvoAAOS2mqtt topic in the binary_sensor domain.

**Screenshots**:<br>
![image](https://github.com/Dielee/volvo2mqtt/assets/9726307/7267254b-d652-4228-9017-6a2b3fcf6389)

**Expected behavior**:<br>
All available topics to be displayed as entities in Home Assistant.

**Version info**:<br>
Home Assistant: 2024.1.2
Volvo2mqtt: 1.8.23
Car: Volvo XC40 Recharge 2024

**Logs**:<br>
```
Jan 07 12:29:18 volvo2mqtt [1] - INFO: Starting volvo2mqtt version v1.8.23
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Using VCCAPIKEY: xxx
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Vin: ['xxx'] found!
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Battery Charge Level is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Electric Range is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Charging System Status is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Charging Connection Status is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Odometer is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Last Data Update is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Active schedules is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Window Front Left is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Window Front Right is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Window Rear Left is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Window Rear Right is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Door Front Left is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Door Front Right is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Door Rear Left is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Door Rear Right is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Tailgate is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Engine Hood is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Tank Lid is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Sunroof is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Air Conditioning is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Lock state is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Force Update Data is supported by your vehicle.
Jan 07 12:29:19 volvo2mqtt [1] - INFO: Success! Location is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Tire Front Left is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Tire Front Right is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Tire Rear Left is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Tire Rear Right is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Engine State is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Average Speed is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Hours to Service is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Distance to Service is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Time to Service is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Service warning status is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Jan 07 12:29:20 volvo2mqtt [1] - INFO: Success! API Backend status is supported by your vehicle.
Jan 07 12:29:23 volvo2mqtt [1] - INFO: Sending mqtt update...
Jan 07 12:29:23 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 60 seconds.
```

**Comment by Dielee** [comment]
So you are missing entities ?

**Comment by paalkr** [comment]
Yes. The Volvo2mqtt component connects to the Volvo API and retrieves all available data (as shown in the logs). Also, all the same data is posted each minute to the mqtt broker. But the auto discovery config is missing for most of the topics, so the only entities auto discovered by Home Assistant is the
* Battery Charge Level
* All four doors
* Engine state
* Lock state

**Comment by Dielee** [comment]
I can't reproduce this behavior... 
Please show me your mqtt device inside home assistant.

**Comment by paalkr** [comment]
Sure, thanks for following up. This is how the device looks like in Home Assistant.
![image](https://github.com/Dielee/volvo2mqtt/assets/9726307/115f7d1f-f515-4b5e-8a75-601e3e68b758)

But I believe this has nothing to do with Home Assistant config. The Auto Discovery config topics simply isn't published to the mqtt borker by Volvo2mqtt. As you see in the screenshot in the OP, only a few topics contain the Home Assistant auto discovery config data.

**Comment by Ilpo55** [comment]
I have all the topics, so is not a general bug.

**Comment by paalkr** [comment]
Sure, thanks for following up. This is how the device looks like in Home Assistant.
![image](https://github.com/Dielee/volvo2mqtt/assets/9726307/115f7d1f-f515-4b5e-8a75-601e3e68b758)

But I believe this has nothing to do with Home Assistant config. The Auto Discovery config topics simply isn't published to the mqtt borker by Volvo2mqtt. As you see in the screenshot in the OP, only a few topics contains the Home Assistant auto discovery config data.

**Comment by paalkr** [comment]
I also have all the topics containing the actual data for each entity supported by my car. The problem is the missing auto discovery topics. Is it possible to enable some more debug logging in the Volvo2mqtt?

**Comment by Dielee** [comment]
I can't help you. This has to be a local broker problem, as the integration works fine for everyone else.

**Comment by paalkr** [comment]
So, on your broker you get all the config messages on each update cycle? Are the config messages set to be retained?

**Comment by Dielee** [comment]
Yes, all my entities are updating every update loop. And yes, the config topics are retained.

**Comment by paalkr** [comment]
Hm, are also all config entries updated on each loop in your broker? Because for me only a subset of the config topics is updated on each loop, as highlighted in the screenshot.

**Comment by marmata** [comment]
@paalkr wondering if you managed to understand what's the issue? I've exactly the same problem, no config topic for most of the sensors. I only get Lock, Battery Charge, the 4 door lock status and the engine state. All the data is being pulled from the volvo servers, just the config topics is not updated and so homeassistant does not pickup.
