### ISSUE TITLE
Charging Schedule

### ISSUE THREAD

**Issue by raftheunis87** [Dielee/volvo2mqtt#157]
**Is your feature request related to a problem? Please describe.**
It is possible in the Volvo (Android) app to configure a charging schedule, even for PHEV vehicles. 
It would be nice if it was possible to control this via volvo2mqtt so that we can set a schedule based on for example the amount of sun that there will be in that day (charge when there is a lot of solar overproduction).

**Describe the solution you'd like**
Maybe there is an API to set this, as the app can also do it?

**Additional context**
If there is no API for this available, then of course this is not possible.

**Comment by Dielee** [comment]
No sorry, there is no API endpoint available. But you are able to automate this behavior with HA automations.

**Comment by raftheunis87** [comment]
How so? By connecting your charging station to HA? Since there is no toggle on car level to start/stop the charging?

**Comment by Dielee** [comment]
Yes, indeed you need a charging station which is HA compatible.

**Comment by raftheunis87** [comment]
Ok, I thought so unfortunately. Still need to make a little project of that, since my Alfen Pro Line isn't supported by HA out of the box. So I will have to do some modbus stuff for it to work. 

Thanks for the quick reply man, appreciated!

This ticket can then be closed.
