### ISSUE TITLE
Error max retry;s

### ISSUE THREAD

**Issue by sschouten** [Dielee/volvo2mqtt#16]
I am getting below in the logs and the docker wil not start.
is it possible that there is a limit on how much conections you have to the volvo api ?

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='volvoid.eu.volvocars.com', port=443): Max retries exceeded with url: /as/token.oauth2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f18abe16bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by Dielee** [comment]
Your docker host cannot connect to `volvoid.eu.volvocars.com`. Seems to be a DNS problem...

**Comment by sschouten** [comment]
o how simple it can be ;)
