### ISSUE TITLE
Allow CONF_updateInterval to be configurable after the container starts

### ISSUE THREAD

**Issue by dgthomson** [Dielee/volvo2mqtt#160]
I'd like to be able to change CONF_updateInterval occasionally.

Perhaps this could be done by allowing an MQTT payload to be sent into the container with the number of seconds required.

**Comment by Dielee** [comment]
Yeah, nice feature. 
Maybe I will take a look at this tomorrow.

**Comment by timknowlden** [comment]
Mine doesn't seem to update at all after the initial update from container starting.

**Comment by Dielee** [comment]
This feature is available starting v1.8.24!

**Comment by Ilpo55** [comment]
Could there be "no update". Example interval 0 could be "no update".
This is because it looks that updates uses the 12 V battery. Which is bad in cold weather (-30 C), like what we have had here in Finland.

**Comment by Dielee** [comment]
> Could there be "no update". Example interval 0 could be "no update". This is because it looks that updates uses the 12 V battery. Which is bad in cold weather (-30 C), like what we have had here in Finland.
> 
> Maybe the update itself does not use battery much, but it looks that when there are frequent update requests the car does not go into "sleep mode" and that is why it uses about 0.150 kW all the time when temperature is below -10 C. (0.150 kW is what my chargin station shows.)

This feature is available starting version v1.8.26!

**Comment by Dielee** [comment]
@Ilpo55 thanks for the coffee!
