### ISSUE TITLE
Charging Connection Status set to 'unspecified' when charging

### ISSUE THREAD

**Issue by ezande** [Dielee/volvo2mqtt#161]
**Describe the bug**
Charging Connection Status is set incorrectly to '`unspecified`' when the vehicle (XC40 Recharge) is charging.
You will see the parameter `volvo_<VIN>_charging_connection_status` cycle through: `disconnected` -> `unspecified` -> `disconnected`

**To Reproduce**:<br>
- Connect car using cable
- Start charging
- Disconnect after charging

**Expected behavior**:<br>
Expected status '`connected`'

**Screenshots**:<br>
None.

**Version info**:<br>
Volvo2mqtt version: 1.8.23
HAOS version: 2024.1.3

**Logs**:<br>
None.

**Comment by Dielee** [comment]
This is the current API behavior. I can't do anything for you.
