### ISSUE TITLE
(Synology) Docker Images stops and won't start anymore

### ISSUE THREAD

**Issue by martin072** [Dielee/volvo2mqtt#163]
**Describe the bug**
(Synology) volvo2mqtt Docker images stops running

**To Reproduce**:<br>
restart the docker container, after 1 - 2 minutes it stops. 

**Version info**:<br>
dielee/volvo2mqtt: latest (docker image)

**Logs**:<br>
Unable to retrieve the logs, as the docker image won't start. No further loging available. If there are other means to get the logging out of the docker container, please let me know how (i did enable the DEBUG flag

**Comment by Dielee** [comment]
If you are not able to provide logs, I can't help you.

**Comment by martin072** [comment]
Yes as mentioned. I assume the logs are in the container. Sonia it doesn't start I can't enter it. If you know any other to retrieve the logs then let me know

**Comment by Dielee** [comment]
This is not a volvo2mqtt issue. If the container don't start, you have to look inside the syno logs.

**Comment by martin072** [comment]
Thanks, but running on a dead end, there are no logs I can find in synology, or in Docker. Only thing that pops-up is the following notification. There are no logs anywhere to be found unfortunately.

<img width="661" alt="Screenshot 2024-01-20 at 15 30 04" src="https://github.com/Dielee/volvo2mqtt/assets/24524506/2408ca41-3b43-42d2-bbe0-31c7090aa3bf">
<img width="804" alt="Screenshot 2024-01-20 at 15 32 14" src="https://github.com/Dielee/volvo2mqtt/assets/24524506/b651db18-ad5d-42e5-822f-9b0916452ef5">


One error I received before was the following: 
```
Start container volvo2mqtt failed: {"message":"failed to initialize logging driver: database is locked"}.
```

A tip I found was to copy the container and remove the old one. That worked, but this time there are no Logs as you can see. 

I will close the issue as you say it is not related.

**Comment by martin072** [comment]
Managed to get some loging, see below

<img width="801" alt="Screenshot 2024-01-20 at 18 13 35" src="https://github.com/Dielee/volvo2mqtt/assets/24524506/fc0d811a-6101-4490-97d7-81481db2ac8c">

**Comment by martin072** [comment]
Ok, thank. So how do I get it to update the docker container? When using the script as supplied, with ```volvo2mqtt:latest``` it still loads 1.7.5
