### ISSUE TITLE
INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by Ilpo55** [Dielee/volvo2mqtt#165]
Current version: 1.8.24

I noticed in the morning that there was no new values of data after yesterday.
Restarting the volvo2mqtt solved the issue.

Log:

Jan 22 16:06:21 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "ce91ed76-b280-42f8-b23c-24371c610af4",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jan 22 16:06:57 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jan 22 16:11:57 volvo2mqtt [106] - INFO: Sending mqtt update...
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 16, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 221, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 268, in update_car_data
    state = sum(value == "FAILURE" for value in state.values())
                                                ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by Dielee** [comment]
Thanks, this is a bug. I will fix this later today.
