### ISSUE TITLE
Charging Connection Status not showing Connected

### ISSUE THREAD

**Issue by kernalkue** [Dielee/volvo2mqtt#169]
**Describe the bug**
When my XC40 BEV 2022 is connected to my home charger the "Charging Connection Status" shows "Unspecified". It shows "Disconnected" and "Fault" accurately

**To Reproduce**:<br>
Connect a charger and see the state change for the Charging Connection Status entity

**Expected behavior**:<br>
I would expect it to show something like "Connected". Not sure what the API outputs.

**Screenshots**:<br>
![image](https://github.com/Dielee/volvo2mqtt/assets/7815014/50bdd83b-5bb5-41b9-8734-589d79bfd366)

**Version info**:<br>
HA Addon 1.8.27

**Logs**:<br>
There's nothing in the log around that time other than:
Jan 29 12:50:37 volvo2mqtt [105] - INFO: Sending mqtt update...
Jan 29 12:50:38 volvo2mqtt [105] - INFO: Mqtt update done. Next run in 300 seconds.

which is repeated a lot (probably as expected!)

I'm guessing it's just an API issue, but thought I'd raise it in case

**Comment by Dielee** [comment]
Yes, this a api issue.. we just can wait.

**Comment by FireWizard52** [comment]
Hi @Dielee , Linus

I´m not a Python specialist en try to read the code, as far as possible.
For the "Charging Connection Status", I think you use the following endpoint: https://api.volvocars.com/energy/v1/vehicles/{vin}/recharge-status/charging-connection-status. Is that correct? If so, I see the same and an empty string is returned.

However, if you use https://api.volvocars.com/energy/v1/vehicles/{vin}/recharge-status, I receive, in case the charger is connected,
CONNECTION_STATUS_CONNECTED_AC

In fact this endpoint gives all the data that the other endpoints also give.. Quite strange.
see also the screenshot below (Currently no charger connected)

![Screenshot_Volvo_Charging_Connection_Status](https://github.com/Dielee/volvo2mqtt/assets/46283323/e4ae42d4-4bc5-4e98-99ca-09de7c08d6bc)

At he top the "recharge-status/charging-connection-status" endpoint en below the result of "recharge-status" endpoint.

Regards

**Comment by Dielee** [comment]
We are using the `recharge-status` endpoint. Disconnected works every time, also via the addon. But if it's connected, it says `unspecified`.

**Comment by FireWizard52** [comment]
@Dielee 

For your information: I noticed that (again) Volvo is working on,in this case the Energy API, as I receive an error from that API since February 14, 15:11.
It gives a status 404 error, with the following error message:

```
message: "NOT_FOUND"
description: "Car model is not supported"

```

It has been working for a couple of weeks, without any issues
So let's wait,when it turns back to stable.

Regards

**Comment by HWiese1980** [comment]
> We are using the `recharge-status` endpoint. Disconnected works every time, also via the addon. But if it's connected, it says `unspecified`.

Couldn't you use that as a kind of "fallback"? So basically `if state != disconnected: state = connected`? I mean, we users could do that as well, I suppose.

**Comment by HWiese1980** [comment]
> > We are using the `recharge-status` endpoint. Disconnected works every time, also via the addon. But if it's connected, it says `unspecified`.
> 
> Couldn't you use that as a kind of "fallback"? So basically `if state != disconnected: state = connected`? I mean, we users could do that as well, I suppose.

@Dielee would that be a viable solution?

**Comment by Dielee** [comment]
For me, "Charging connection status" works now as it should. It shows "Connected AC" since the last update. 

Please check this and update your car.

**Comment by HWiese1980** [comment]
> For me, "Charging connection status" works now as it should. It shows "Connected AC" since the last update.
> 
> Please check this and update your car.

Interesting. What car and what version do you have?

**Comment by kernalkue** [comment]
> For me, "Charging connection status" works now as it should. It shows "Connected AC" since the last update.
> 
> Please check this and update your car.

Updated the software on my XC40 BEV 2021 last night and can confirm that I am now getting "Connected AC" when it is plugged into my Zappi charger.

**Comment by Dielee** [comment]
Please update your car to version 2.14.3. 
This will fix the charging connection status.
