### ISSUE TITLE
Add more sensors

### ISSUE THREAD

**Issue by kristofferbj** [Dielee/volvo2mqtt#17]
Great work! If it is possible I would like even more sensors added:

Current GPS position
kWh consumption
Last trip (from where to where, GPS coordinates)
Odometer
Lock status as a sensor
Door and window sensors (open or closed)

**Comment by Dielee** [comment]
The current GPS position will be added as a device_tracker entity. 
The odometer will be added as a sensor. 
Door and window sensors will be added as sensors.

Lock status can be seen from the lock entity and will not be added as a sensor. Why do you need an extra sensor ?
For kWh consumption and the last trip, there is no API data; this can not be added.

**Comment by kristofferbj** [comment]
You're right, I don't need a separate lock sensor.

I'll be waiting for the other sensors, then. Thanks!

**Comment by brownstone666** [comment]
Great job!

**Comment by Dielee** [comment]
Done with release v1.2.0
