### ISSUE TITLE
Phone number as user name not accepted

### ISSUE THREAD

**Issue by larionof** [Dielee/volvo2mqtt#170]
**Describe the bug**
The addon only accepts emails as user name though many of us have been forced to use phone number as user name.

**Screenshots**:<br>
Failed to save add-on configuration, does not match regular expression ^([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)|(\+\d{5,20})$. Got {'updateInterval': 300, 'babelLocale': 'FI', 'TZ': 'Europe/Helsinki', 'debug': False, 'disable_logging': False, 'mqtt': {'broker': 'auto_broker', 'port': 'auto_port', 'username': 'auto_user', 'password': 'auto_password'}, 'volvoData': {'username': 355555555, 'password': 'password', 'vin': '', 'vccapikey': [None], 'odometerMultiplier': 1, 'averageSpeedDivider': 1, 'averageFuelConsumptionMultiplier': 1}.

**Version info**:<br>
The version you are using and the method you are using (Docker container/HA Addon/Cloned repo)

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
<b>If you are using the HA Addon the log location is `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

**Comment by Dielee** [comment]
Please send me your phone number, containing some zeros to make it invalid.

**Comment by Dielee** [comment]
So the regex works for your phone number. There is something else wrong. Please send me a screenshot from your config.

**Comment by larionof** [comment]
I do apologise not getting back to this earlier. Here's my data:
![github-virhe](https://github.com/Dielee/volvo2mqtt/assets/45319388/e7b5a216-724f-415a-93f8-0b471b92b206)

**Comment by Dielee** [comment]
How long is your phone number, including the "+" in front ?

**Comment by larionof** [comment]
Most common phone number format is +358 123 456 7890, so 1+3+10= 14

**Comment by Dielee** [comment]
So you are using whitespaces in your phone number ?

**Comment by larionof** [comment]
No. I wrote the format out without thinking, sorry for that( acc. grammar it is written as above but obviously wherever needed the all 14 marks( numbers, letters, plus sign) are without spaces).

**Comment by Dielee** [comment]
So, i can't help you without beeing able to see your full config. 
Are you able to share me your whole config via PM ?

**Comment by larionof** [comment]
Understood but best I can provide is an example of the settings used( love the work you've done to get the interface to HA and if majority get it to work with email as username, that's acceptable).
 What I will try next is to add an account to the car with an email as username instead of the phone number. I've not bothered to make secondary accounts yet as they're not required to have phones connected 

![github-virhe](https://github.com/Dielee/volvo2mqtt/assets/45319388/251ce0d9-cb4f-4550-b94b-1dc4ca638268)

**Comment by hael69** [comment]
I have the same problem with newly installed HA and version 1.10.5 it will not accept phone number just email ??
<img width="1016" alt="Skärmavbild 2024-11-24 kl  20 31 48" src="https://github.com/user-attachments/assets/dccf3944-1f8f-4764-8e5a-25101d31a60b">
