### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by droidgren** [Dielee/volvo2mqtt#171]
For some reason some of my entites has stopped updating.  For example, battery_charge_level, which is the only one I actually care about. 
I had it working for a week or two, then suddenly some new entites came in ( Odometer etc) , but then some of the old ones stopped updating. 

I tried to delete them all from the MQTT integration to have them recreated, but they are not. 
Is there something I have to do on the Volvo developer portal?

The ones I got are these: 

![image](https://github.com/Dielee/volvo2mqtt/assets/354317/8542935c-3402-4957-9232-bf97c6ddd83f)

**Comment by Dielee** [comment]
Please send some debug logs...

**Comment by droidgren** [comment]
Sure, here is the full log.
[volvo2mqtt (1).log](https://github.com/Dielee/volvo2mqtt/files/14214542/volvo2mqtt.1.log)

**Comment by droidgren** [comment]
For some reason it started to work again. Maybe it was because the charge level changed, I had not been charging my car for a while.

**Comment by Dielee** [comment]
Log seems good also...
