### ISSUE TITLE
Sensor with the group result for windows, doors and hood

### ISSUE THREAD

**Issue by cybermaniapt** [Dielee/volvo2mqtt#173]
Hi there!

Many thanks for your work over this integration!

I'm thinking in preparing an automation that warns me whenever a door, window or anything else is open for a long period without me being near. It would easier if the integration comes with a sensor with everything grouped. I can do it locally as well, just wondering if this is useful to have it integrated.

Again thanks for your effort!

Kind regards

**Comment by Dielee** [comment]
Hello! 

Yes, I understand your opinion, but some people prefer grouped entities, and some prefer single entities. 
At this time, there are only single entities, and for now, it will remain as it is. 

Greets
