### ISSUE TITLE
Update compatibility matrix

### ISSUE THREAD

**Issue by d1nd141** [Dielee/volvo2mqtt#177]
Hi,
This is just to inform, that C40 Recharge 2024 edition also works fine!
Thanks for all the work done!

Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Battery Charge Level is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Electric Range is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Charging System Status is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Charging Connection Status is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Odometer is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Last Data Update is supported by your vehicle.
Mar 03 13:27:40 volvo2mqtt [1] - INFO: Success! Active schedules is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Window Front Left is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Window Front Right is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Window Rear Left is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Window Rear Right is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Door Front Left is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Door Front Right is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Door Rear Left is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Door Rear Right is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Tailgate is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Engine Hood is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Tank Lid is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Sunroof is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Air Conditioning is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Lock state is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Force Update Data is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Location is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Tire Front Left is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Tire Front Right is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Tire Rear Left is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Tire Rear Right is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Engine State is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Average Speed is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Hours to Service is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Distance to Service is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Time to Service is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Service warning status is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! API Backend status is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Update Interval is supported by your vehicle.
Mar 03 13:27:41 volvo2mqtt [1] - INFO: Success! Warnings is supported by your vehicle.
Mar 03 13:27:43 volvo2mqtt [1] - INFO: Sending mqtt update...
Mar 03 13:27:44 volvo2mqtt [1] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment]
Thanks!
