### ISSUE TITLE
[Feature Request] Add Engine state, Tier state, Fuel level, Charge plug status

### ISSUE THREAD

**Issue by larronni** [Dielee/volvo2mqtt#18]
Is it also possible to get the Engine state, Tier state, Fuel level (for non-electric), and Charge Plug status?

**Comment by brownstone666** [comment]
Tires can be retrived on this endpoint:
https://api.volvocars.com/connected-vehicle/v2/vehicles/{{VIN}}/tyres

It would be nice if we can get Battery status from this endpoint also, unfortunly my country (Brazil) is not avaible in EnergyApi:
https://api.volvocars.com/connected-vehicle/v2/vehicles/{{VIN}}/battery-charge-level

**Comment by Dielee** [comment]
> Tires can be retrived on this endpoint:
> https://api.volvocars.com/connected-vehicle/v2/vehicles/{{VIN}}/tyres
> 
> It would be nice if we can get Battery status from this endpoint also, unfortunly my country (Brazil) is not avaible in EnergyApi:
> https://api.volvocars.com/connected-vehicle/v2/vehicles/{{VIN}}/battery-charge-level

Please create a new feature request

**Comment by Dielee** [comment]
> Is it also possible to get the Engine state, Tier state, Fuel level (for non-electric), and Charge Plug status?

Do you mean [this](https://developer.volvocars.com/apis/energy/v1/endpoints/charging-connection-status/) with charge plug status ?

**Comment by Dielee** [comment]
Please test this pre release image: `ghcr.io/dielee/volvo2mqtt:sha-ce1f779`

**Comment by larronni** [comment]
Using the HA addon, so not sure how to test te pre release...?

**Comment by Dielee** [comment]
Okay,  than I have to release a new version first. Wait a sec.

**Comment by Dielee** [comment]
Pls try v1.3.0

**Comment by larronni** [comment]
OK,

Tiers are now a sensor (typo...? )
![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/f193a56f-e4c2-495e-b7bd-197734d383c5)

Engine state is a sensor
![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/21708900-0bd4-4c28-942d-9ccc57d6c460)

Fuel and Charge plug state is not presented...

**Comment by Dielee** [comment]
Why do mean typo ? Whats wrong with Tyre ?
Engine state is a sensor, right, what else ?

Pls show me your full startup log!

**Comment by larronni** [comment]
Fuel level works on 1.3.2

Logs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting volvo2mqtt version v1.3.2
Vin: ['*******************'] found!
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/battery-charge-level
Success! Battery Charge Level is supported by your vehicle.
Failed, Electric Range is unfortunately not supported by your vehicle.
Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Failed, Charging System Status is unfortunately not supported by your vehicle.
Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/odometer
Success! Odometer is supported by your vehicle.
Success! Last Data Update is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/windows
Success! Window Front Left is supported by your vehicle.
Success! Window Front Right is supported by your vehicle.
Success! Window Rear Left is supported by your vehicle.
Success! Window Rear Right is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Success! Door Front Left is supported by your vehicle.
Success! Door Front Right is supported by your vehicle.
Success! Door Rear Left is supported by your vehicle.
Success! Door Rear Right is supported by your vehicle.
Success! Tailgate is supported by your vehicle.
Success! Engine Hood is supported by your vehicle.
Success! Tank Lid is supported by your vehicle.
Success! Air Conditioning is supported by your vehicle.
Success! Lock state is supported by your vehicle.
Success! Force Update Data is supported by your vehicle.
Starting GET call against https://api.volvocars.com/location/v1/vehicles/{0}/location
Success! Location is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Success! Tire Front Left is supported by your vehicle.
Success! Tire Front Right is supported by your vehicle.
Success! Tire Rear Left is supported by your vehicle.
Success! Tire Rear Right is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Success! Engine State is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Success! Fuel Level is supported by your vehicle.
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/battery-charge-level
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/odometer
Starting GET call against https://api.volvocars.com/location/v1/vehicles/{0}/location
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Mqtt update done. Next run in 300 seconds.
```

**Comment by Dielee** [comment]
`Failed, Charging Connection Status is unfortunately not supported by your vehicle.` 
Your car doesn't support the energy api. Therefore you cannot see the `Charging Connection Status` sensor. There is nothing I can do for you, sorry.

**Comment by larronni** [comment]
ok... So there is not possible to read from two different API pending on the car type some sort.... ? 
I can see a sensor in the Volvo Integration in HA called "V90 plug status" (state Unplugged / plugged in)

**Comment by Dielee** [comment]
Possible yes, but not the intention from this component. The component here were build for the new AAOS cars.

**Comment by larronni** [comment]
ok - have to go and buy a new car then 😝

But the rest looks nice now - so thanks
