### ISSUE TITLE
Enable / Disable charge planning

### ISSUE THREAD

**Issue by svdstra** [Dielee/volvo2mqtt#182]
Whan at home I would like to charge my car at night but when I am in a public plice I can charge any time. In the Volvo app there is a possibility  to toggle between using a charge planning and always charge.
Is there a possibility to make this switch available in Home Assistant so I can create a automation  for this?

Thanks!!
Sander

**Comment by Dielee** [comment]
No, sorry. This is an "app only" feature at this time, as Volvo doesn't provide any endpoint in their public API, which delivers this functionality.

**Comment by svdstra** [comment]
That's to bad, but thanks for the response :-). And thanks for all the work
you put into  this!!! 👍👍

Sander

Op za 30 mrt 2024 07:34 schreef Linus Dietz ***@***.***>:
