### ISSUE TITLE
VIN and entity names

### ISSUE THREAD

**Issue by KeningGruttePier** [Dielee/volvo2mqtt#188]
First of all thank you for your effort with this integration with Volvo On Call APIs.

I drive MY19 V60, Sensus PHEV and partly working, all are reported in Homeassistant except for the Charging and Battery entities.

My request is to have the VIN not in the entity names and apply an attribute name from the configuration file provided. This way I can keep the VIN out of my dashboard and automation and script yamls! Thank you!

P.s. Of course I could manually rename each of them in Homeassistant, but by default upon creation would save many people the effort.

**Comment by Dielee** [comment]
This isn't an option, as it is possible to have multiple cars. For this reason there has to be the VIN inside the entity ID.

**Comment by KeningGruttePier** [comment]
Hi Dielee, thank you for the response.

I also found why my V60 MY19 does not report the battery range and level - that's due to the API used. Energy API does not work with these older PHEV models, the Connected Vehicle API does report more attributes for my platform. Any quick option for you to have that configured by the general addon configuration too?
