### ISSUE TITLE
Question on Volvo V2 API

### ISSUE THREAD

**Issue by jobe39** [Dielee/volvo2mqtt#189]
Sorry, since there is no discussion section here and I do not know how I could contact you, I am writing my question here. If I understand the otp branch correct, this one is using the v2 version of the Volvo API. 

Did you have to "Publish" your application on the volvo developer account? If I understand the API documentation correct, in testing mode there is no chance for refreshing the token, you get from oauth2 authentification. Or do I understand it wrong?

If you had to publish it, how did you manage that? In the evcc.io project we get complaints about missing privacy statement and such stuff from Volvo, thus the application can not be published. So we are stuck here. If you could share some light here, how to get over that process, that would really help.

See the discussion here: https://github.com/evcc-io/evcc/discussions/12481

Thanks a lot and br,
   Gernot

**Comment by Dielee** [comment]
Let us talk about this in private. 
Maybe you can send me your email address ?
