### ISSUE TITLE
OTP with French language 

### ISSUE THREAD

**Issue by zigomatichub** [Dielee/volvo2mqtt#191]
Hello Dielee, 
First thank you for this Integration which is really appreciate 

About Version 1.9.1 with the OTP entity, I was not able to get the success with the process.
Either using developer tool to update the OTP entity or either the UI - entity dashboard to update the value.

I saw that error:
/volvoAAOS2mqtt/mqtt.py:56: SyntaxWarning: invalid escape sequence '\d'
  "pattern": "\d{6}",

Workaround :
Put English instead of French as language 
Go to UI entity and update the code
Result OK
 
It's not an issue but FYI

Regards,
Zigomatic

**Comment by Dielee** [comment]
This isn't an error, just a warning from python 3.12.
