### ISSUE TITLE
OTP bug version 1.9.1

### ISSUE THREAD

**Issue by RobPijpers** [Dielee/volvo2mqtt#192]
**Describe the bug**
OTP token does not work after update interval of 300 sec.

**To Reproduce**:<br>
The API connection is working as soon the OTP token is entered in the proposed entity. After the update interval (300 sec) the API is failing and a new token must entered.

**Expected behavior**:<br>
Enter OTP once during configuration

**Screenshots**:<br>
na

**Version info**:<br>
1.9.1

**Logs**:<br>
May 27 15:39:50 volvo2mqtt [106] - INFO: Success! Update Interval is supported by your vehicle.
May 27 15:39:50 volvo2mqtt [106] - INFO: Success! Warnings is supported by your vehicle.
May 27 15:39:52 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 15:39:53 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
May 27 15:44:53 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 15:44:53 volvo2mqtt [106] - ERROR: Error getting data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
May 27 15:44:55 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
May 27 15:49:55 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 15:49:55 volvo2mqtt [106] - ERROR: Error getting data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
May 27 15:49:58 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
May 27 15:54:58 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 15:54:58 volvo2mqtt [106] - ERROR: Error getting data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
May 27 15:55:00 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by RobPijpers** [comment]
After restarting the Addon the connection is working, keep you updated asap.

**Comment by RobPijpers** [comment]
After a few succesfull updates the connection is failed again:

May 27 16:01:54 volvo2mqtt [106] - INFO: Success! Update Interval is supported by your vehicle.
May 27 16:01:55 volvo2mqtt [106] - INFO: Success! Warnings is supported by your vehicle.
May 27 16:01:58 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 16:01:59 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
May 27 16:06:59 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 16:07:03 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
May 27 16:12:03 volvo2mqtt [106] - INFO: Sending mqtt update...
May 27 16:12:03 volvo2mqtt [106] - ERROR: Error getting data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
May 27 16:12:05 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment]
This has nothing to do with the otp auth. May the API or your internet be unstable at this time.

**Comment by RobPijpers** [comment]
Oké, thanks for looking in to this issue. I’m very happy with this addon and thanks for your fast support!
