### ISSUE TITLE
Updates do not resume after adding OTP token

### ISSUE THREAD

**Issue by canoben** [Dielee/volvo2mqtt#193]
I followed the instructions for version 1.9 to add the OTP token that Volvo sent me this morning at 10:30. Since then, there have been no further updates and it seems like the integration does no longer run. Here are the last lines of the log file of volvo2mqtt:
`May 27 10:30:18 volvo2mqtt [107] - INFO: Waiting for otp code... Please check your mailbox and post your otp code to the following mqtt topic "volvoAAOS2mqtt/otp_code". Retry 12/15
May 27 10:30:23 volvo2mqtt [107] - INFO: Waiting for otp code... Please check your mailbox and post your otp code to the following mqtt topic "volvoAAOS2mqtt/otp_code". Retry 13/15
May 27 10:30:28 volvo2mqtt [107] - INFO: Waiting for otp code... Please check your mailbox and post your otp code to the following mqtt topic "volvoAAOS2mqtt/otp_code". Retry 14/15
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 71, in authorize
    response = send_otp(auth_session, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 155, in send_otp
    raise Exception ("No OTP found, exting...")
Exception: No OTP found, exting...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

I only rectified the OTP situation now (8 hours later), but whatever I try (restart the integration, restarting HA), no further log entries are produced and the dashboard shows all the sensors as not available.

**Comment by Dielee** [comment]
You have to fill in the otp code immediately after the addon starts, not a few hours later.

**Comment by canoben** [comment]
Well, as I missed it, what can I do now?

**Comment by micvdh** [comment]
> You have to fill in the otp code immediately after the addon starts, not a few hours later.

although following the instruction, setting up the OTP code in the text value, I still systematically end-up with the following : 

May 27 19:57:36 volvo2mqtt [106] - INFO: Waiting for otp code... Please check your mailbox and post your otp code to the following mqtt topic "volvoAAOS2mqtt/otp_code". Retry 23/24
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 73, in authorize
    response = send_otp(auth_session, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 157, in send_otp
    raise Exception ("No OTP found, exting...")
Exception: No OTP found, exting...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped

**Comment by golf1025** [comment]
Same here. Also not clear how the text.volvo_opt should look like after pasting opt as per instruction step 6. Should it read text.xxxxx ?

**Comment by Dielee** [comment]
Maybe HA is a bit buggy firing the otp input.
Please try to post your otp manually to this topic via mqtt:

`volvoAAOS2mqtt/otp_code`

**Comment by micvdh** [comment]
> volvoAAOS2mqtt/otp_code

It worked indeed, calling MQTT publish service solved the issue

service: mqtt.publish
data:
  topic: volvoAAOS2mqtt/otp_code
  payload: XXXXXX

**Comment by Dielee** [comment]
Yes, thanks for testing. This is indeed an HA bug... I will think about a better solution tomorrow.

**Comment by canoben** [comment]
Before reading the solution above, I reinstalled the VOC plugin (after removing it), but now I'm unable to re-add my car.

**Comment by Pieter1979** [comment]
HI, 
first of all thanks for all your efforts! I have a small question: I have the latest version but I don't find the entity ID text.volvo_otp. I rebooted, installed all the latest versions. I only see Volvo2Mqtt Update. I receive the OTP password on mail, so the connection is made but I don't find the place where I can place it. 
I work with the Mosquitto broker. 

thanks!

**Comment by Dielee** [comment]
Please try to post your otp manually to this topic via mqtt:

volvoAAOS2mqtt/otp_code

**Comment by ahlburg** [comment]
Ni ideas what's forcing the value back to 000000 as soon as it is changed (to somethiing else) via mqtt.publish?
<img width="558" alt="Skärmavbild 2024-05-29 kl  07 59 03" src="https://github.com/Dielee/volvo2mqtt/assets/2930823/58fb05bd-d9db-4aaf-875c-021b6d1cfb5a">

**Comment by Peacem4kr** [comment]
Hi, i have this integration active for months now.
I updated HA to 2024.05, restarted and it stopped working, noticed in the addon log the same error as mentioned above "missing otp".

I tried to execute the above aswell:
![image](https://github.com/Dielee/volvo2mqtt/assets/78316232/eb003994-abaa-4369-be0d-ec6bd3a76097)
Is this even correct what i am doing here please?

I also checked the state:
![image](https://github.com/Dielee/volvo2mqtt/assets/78316232/7e2cf225-4a7b-4402-ba10-e1dba4ca5fe3)

Is also 000000 like Ahlburg.

Any idea what i can do please?

Thank you!

**Comment by ahlburg** [comment]
I believe this must be a bug because EVERY time I start/restart the addon, the value of "text.volvo_otp" changes to "000000". Doesn't matter if I successfully change the value to something else before (or after) starting the addon...

**Comment by Dielee** [comment]
> I believe this must be a bug because EVERY time I start/restart the addon, the value of "text.volvo_otp" changes to "000000". Doesn't matter if I successfully change the value to something else before (or after) starting the addon...
> 

Do you have to enter the otp every time the addon restarts ?

**Comment by Ilpo55** [comment]
I updated to version 1.9.2 and it is working also after restart OK.
I used "Paste your OTP into the text entity and press Enter" without any problems.

**Comment by ahlburg** [comment]
> > I believe this must be a bug because EVERY time I start/restart the addon, the value of "text.volvo_otp" changes to "000000". Doesn't matter if I successfully change the value to something else before (or after) starting the addon...
> 
> Do you have to enter the otp every time the addon restarts ?

I have never been able to try that because when I try to set the text.volvo_otp, the addon tries to start, changes the value to 000000 and then complains about wrong passcode and dies... If I then set the otp to value sent in email and then tries againg to start the addon changes the value back på 000000 and then dies with same error...

**Comment by ahlburg** [comment]
> I updated from version 1.8.27 to version 1.9.2 and it is working also after restart OK. I used "Paste your OTP into the text entity and press Enter" without any problems.

Did you set the OTP before starting the addon?

**Comment by Peacem4kr** [comment]
Not sure what is happening for me then, maybe its not the update but something else, not sure tbh, but its the same error :)
I was hardly able to set this up initially, so was happy once this worked :)
Is there something i can test?

Is OTP the volvo app password actually?
Where can i find: "Paste your OTP into the text entity and press Enter"
i see this:
![image](https://github.com/Dielee/volvo2mqtt/assets/78316232/b9cc9208-1e80-48ff-a34b-aa22884bd6b8)

**Comment by Ilpo55** [comment]
> > I updated from version 1.8.27 to version 1.9.2 and it is working also after restart OK. I used "Paste your OTP into the text entity and press Enter" without any problems.
> 
> Did you set the OTP before starting the addon?

First I started the add on and then I entered the code while add on was running.

**Comment by ahlburg** [comment]
> Not sure what is happening for me then, maybe its not the update but something else, not sure tbh, but its the same error :) I was hardly able to set this up initially, so was happy once this worked :) Is there something i can test?
> 
> Is OTP the volvo app password actually? Where can i find: "Paste your OTP into the text entity and press Enter" i see this: ![image](https://private-user-images.githubusercontent.com/78316232/334769369-b9cc9208-1e80-48ff-a34b-aa22884bd6b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODAxNzIsIm5iZiI6MTcxNjk3OTg3MiwicGF0aCI6Ii83ODMxNjIzMi8zMzQ3NjkzNjktYjljYzkyMDgtMWU4MC00OGZmLWEzNGItYWEyMjg4NGJkNmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEwNTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZWI2NjBkMWZlNGY1OWQ1OGM1NjlkM2IwYzg1MDMxMzM2NjdhMDQ5NWFkYjgyNmJmMmExZjU1OTk3M2QyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lt-LbSvki07Wg8V8mzCTE74mTEeYuq-m9mr29VBBVKI)

The "OTP" shoul be sent to your email address from Volvo when you start the addon...

**Comment by Peacem4kr** [comment]
kinda thought that, but i didnt receive any emails.
Where did you define the email address to use?

**Comment by Ilpo55** [comment]
> > Not sure what is happening for me then, maybe its not the update but something else, not sure tbh, but its the same error :) I was hardly able to set this up initially, so was happy once this worked :) Is there something i can test?
> > Is OTP the volvo app password actually? Where can i find: "Paste your OTP into the text entity and press Enter" i see this: ![image](https://private-user-images.githubusercontent.com/78316232/334769369-b9cc9208-1e80-48ff-a34b-aa22884bd6b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODAxNzIsIm5iZiI6MTcxNjk3OTg3MiwicGF0aCI6Ii83ODMxNjIzMi8zMzQ3NjkzNjktYjljYzkyMDgtMWU4MC00OGZmLWEzNGItYWEyMjg4NGJkNmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEwNTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZWI2NjBkMWZlNGY1OWQ1OGM1NjlkM2IwYzg1MDMxMzM2NjdhMDQ5NWFkYjgyNmJmMmExZjU1OTk3M2QyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lt-LbSvki07Wg8V8mzCTE74mTEeYuq-m9mr29VBBVKI)
> 
> The "OTP" shoul be sent to your email address from Volvo when you start the addon...

Setting, Devices and Services, Entities

**Comment by ahlburg** [comment]
> > > I updated from version 1.8.27 to version 1.9.2 and it is working also after restart OK. I used "Paste your OTP into the text entity and press Enter" without any problems.
> > 
> > 
> > Did you set the OTP before starting the addon?
> 
> First I started the add on and then I entered the code while add on was running.

For me, the addon quits because the otp-code is wrong so I never have the chance to add while the addon is running. If I try to set it to restart autimatically I get one email from Volvo everytime it restarts with a new code...

**Comment by ahlburg** [comment]
> kinda thought that, but i didnt receive any emails. Where did you define the email address to use?

Your Volvo-ID includes your email-address... https://developer.volvocars.com/

**Comment by Peacem4kr** [comment]
> > kinda thought that, but i didnt receive any emails. Where did you define the email address to use?
> 
> Your Volvo-ID includes your email-address... https://developer.volvocars.com/

When i start the addon (which stops automatically after 24 retries) i do not get any emails tbh.

**Comment by Peacem4kr** [comment]
> > kinda thought that, but i didnt receive any emails. Where did you define the email address to use?
> 
> Your Volvo-ID includes your email-address... https://developer.volvocars.com/

I see, that is my gmail account. nothing received when starting the addon (which stops automatically after 24 retries)

In the addon config is a different email address tho, could this be an issue?
![image](https://github.com/Dielee/volvo2mqtt/assets/78316232/29b66bac-16eb-42be-8f6c-14b66b6a708e)

**Comment by ahlburg** [comment]
Everytime I try to start the addon:
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 73, in authorize
    response = send_otp(auth_session, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 164, in send_otp
    raise Exception(message["details"][0]["userMessage"])
Exception: This passcode is invalid or has expired.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

So obviously no chance to set value of otp while running... I also see  that the value is set back to "000000" in the log for otp:
Loggbok
[Visa mer](http://homeassistant.local:8123/logbook?entity_id=text.volvo_otp&start_date=2024-05-27T22%3A00%3A00.000Z&back=1)
29 maj 2024
Ändrades till 000000
13:03:06 - För 2 minuter sedan
Ändrades till 123456
13:03:05 - För 2 minuter sedan
Ändrades till 000000
13:01:55 - För 3 minuter sedan
Ändrades till 123456

**Comment by ahlburg** [comment]
> > > kinda thought that, but i didnt receive any emails. Where did you define the email address to use?
> > 
> > 
> > Your Volvo-ID includes your email-address... https://developer.volvocars.com/
> 
> I see, that is my gmail account. nothing received when starting the addon, never have tbh
> 
> In the addon config is a different email address tho, could this be an issue? ![image](https://private-user-images.githubusercontent.com/78316232/334772890-29b66bac-16eb-42be-8f6c-14b66b6a708e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODEwMTIsIm5iZiI6MTcxNjk4MDcxMiwicGF0aCI6Ii83ODMxNjIzMi8zMzQ3NzI4OTAtMjliNjZiYWMtMTZlYi00MmJlLThmNmMtMTRiNjZiNmE3MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZTIxOWUzYmRjZTY0YmJkZjNiYjAzNGFkMmQ3NzU1YjhhZTE5NjcyMDcxZWY1NmM2ODI4MjhhMjg0ODFhMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sGCmlQEF9laxkcg_X5y6upOz4PfUW-3yIKFZIrE2nw)

I also use Google-account for Volvo (authentication) but have a different email-address for messages. Works fine...

**Comment by ahlburg** [comment]
> > So obviously no chance to set value of otp while running... I also see that the value is set back to "000000" in the log for otp:
> 
> as this is the same behavior as me just putting in my volvo password (in other words -> a faulthy, not recognized password), then i restarted and the pw is back to 00000. Maybe yours is just not recognized?

Correct, that is my issue; the addon changes the value of "otp" to "000000" and dies before I'm able to set the new value of otp that is sent from Volvo...

**Comment by Peacem4kr** [comment]
For me, i just dont get why suddenly it starts asking for OTP when the addon has been in use for ages.
I also never received any emails about OTP, or any email for that matter while i was setting this up, it just kind a worked.
I feel (could be wrong) that i have not changed anything that could impact such behavior.

Can you/we fully resinstall this addon and would that be of any help?

**Comment by Ilpo55** [comment]
> For me, i just dont get why suddenly it starts asking for OTP when the addon has been in use for ages. 

Do you have Auto update ON? That could be the reason.

**Comment by ahlburg** [comment]
> For me, i just dont get why suddenly it starts asking for OTP when the addon has been in use for ages. I also never received any emails about OTP, or any email for that matter while i was setting this up, it just kind a worked. I feel (could be wrong) that i have not changed anything that could impact such behavior.
> 
> Can you/we fully resinstall this addon and would that be of any help?

I have done that without any difference... From what I understand the new version needs "OTP" because of changes in Volvos API authentication. In your case you need to find out how to get the emails from Volvo. Maybe it will work for you if you put in the correct OTP. But if your addon also chenges the value back to "000000" and crashes in one second you will have the same problem as I do...

**Comment by Peacem4kr** [comment]
Ok need to rephrase due too stupidity..
Its working now, i was actually receiving a code... but on my volvo app user account, not on my volvo dev account.
But as you are receiving emails, this woul dnot be applicable to you.

i fixed my issue with the solutions provided above.

What i did:
Started the addon volvo2mqtt
Opened: Settings - Devices & Service - Entities
Searched for: OTP
Open the entity and provided the newly received code.

Side remark, first time i did this.. my addon was just stopped and i noticed the code changed back to 0.
Did the same, but a bit faster.
Code remains the same now..

All this is without any restarts.

**Comment by ahlburg** [comment]
> Ok, need to rephrase due too my stupidity.. Its working now, i was actually receiving a code... but on my volvo app user account, not on my volvo dev account. But as you are receiving emails, this would not be applicable to you.
> 
> i fixed my issue with the solutions provided above.
> 
> What i did: Started the addon: volvo2mqtt Opened: Settings - Devices & Services - Entities Searched for: OTP Open the entity and provided the newly received code + enter, and close
> 
> Side remark, first time i did this.. my addon just stopped and i noticed the code changed back to 0. Did the same, but a bit faster. Code remains the same now..
> 
> All this is without any restarts.

OK, lucky you ;-) I have done the exact same thing many times (added the new code within a few seconds) but the addon changes the value to 000000 and crashes (within milliseconds I believe).

**Comment by Dielee** [comment]
> > Ok, need to rephrase due too my stupidity.. Its working now, i was actually receiving a code... but on my volvo app user account, not on my volvo dev account. But as you are receiving emails, this would not be applicable to you.
> > 
> > i fixed my issue with the solutions provided above.
> > 
> > What i did: Started the addon: volvo2mqtt Opened: Settings - Devices & Services - Entities Searched for: OTP Open the entity and provided the newly received code + enter, and close
> > 
> > Side remark, first time i did this.. my addon just stopped and i noticed the code changed back to 0. Did the same, but a bit faster. Code remains the same now..
> > 
> > All this is without any restarts.
> 
> OK, lucky you ;-) I have done the exact same thing many times (added the new code within a few seconds) but the addon changes the value to 000000 and crashes (within milliseconds I believe).

The addon resets the otp to 000000 only if the OTP mechanism starts. Please share some debug logs.

**Comment by ahlburg** [comment]
> > > Ok, need to rephrase due too my stupidity.. Its working now, i was actually receiving a code... but on my volvo app user account, not on my volvo dev account. But as you are receiving emails, this would not be applicable to you.
> > > i fixed my issue with the solutions provided above.
> > > What i did: Started the addon: volvo2mqtt Opened: Settings - Devices & Services - Entities Searched for: OTP Open the entity and provided the newly received code + enter, and close
> > > Side remark, first time i did this.. my addon just stopped and i noticed the code changed back to 0. Did the same, but a bit faster. Code remains the same now..
> > > All this is without any restarts.
> > 
> > 
> > OK, lucky you ;-) I have done the exact same thing many times (added the new code within a few seconds) but the addon changes the value to 000000 and crashes (within milliseconds I believe).
> 
> The addon resets the otp to 000000 only if the OTP mechanism starts. Please share some debug logs.

Can you guide me to where I can find such?

**Comment by ahlburg** [comment]
> > > Ok, need to rephrase due too my stupidity.. Its working now, i was actually receiving a code... but on my volvo app user account, not on my volvo dev account. But as you are receiving emails, this would not be applicable to you.
> > > i fixed my issue with the solutions provided above.
> > > What i did: Started the addon: volvo2mqtt Opened: Settings - Devices & Services - Entities Searched for: OTP Open the entity and provided the newly received code + enter, and close
> > > Side remark, first time i did this.. my addon just stopped and i noticed the code changed back to 0. Did the same, but a bit faster. Code remains the same now..
> > > All this is without any restarts.
> > 
> > 
> > OK, lucky you ;-) I have done the exact same thing many times (added the new code within a few seconds) but the addon changes the value to 000000 and crashes (within milliseconds I believe).
> 
> The addon resets the otp to 000000 only if the OTP mechanism starts. Please share some debug logs.

This is what I get from the addon (not debug log):
May 29 13:56:02 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.2
May 29 13:56:02 volvo2mqtt [106] - DEBUG: MQTT Credentials - Host core-mosquitto Port: 1883 User: addons Pass: juubeo5pithaiCooph0baereeP1zafeuthoopoonuk1iech6Ahphiteequai7uur
May 29 13:56:02 volvo2mqtt [106] - INFO: Starting login with OTP
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 73, in authorize
    response = send_otp(auth_session, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 164, in send_otp
    raise Exception(message["details"][0]["userMessage"])
Exception: This passcode is invalid or has expired.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
This is the Volvo API response. Either your OTP is wrong, expired or used somewhere else.

**Comment by ahlburg** [comment]
> This is the Volvo API response. Either your OTP is wrong, expired or used somewhere else.

How do you mean? How shall I be able to input the correct OTP from email that I receive when the addon crashes before I can do that? The addon crashes because OTP is wrong? Catch 22 here. Can you please guide me how to start the addon and have it running for more than 1 second to be able to input the OTP that I receive from Volvo when I (try to) start the addon? Is there any way to "start over" and get rid of the addon and start from scratch? Something is obviously broken here...

**Comment by ahlburg** [comment]
Can you please explain; should it be possible to change the value of "text.volvo_otp" without the addon running? 
The addon is not running here. If I post a new value to "volvoAAOS2mqtt/otp_code" with mqtt, is there any way I can see if that works? Is it supposed to change the value of "text.volvo_otp"-entity?

**Comment by ahlburg** [comment]
1. Starting the addon to get a new email with the 6-digit code from Volvo.¨
2. 1 second later copy/pasting that code into a "push" with mqtt as per your instructions. (888212)
3. starting the addon again after it crashed due to wrong code under step 1.
4. Looking at the log for the "text.volvo_otp"-entity that correctly shows my 6-digits and the second after changing it to 000000 and crashing the addon once again.

What is wrong here? 

<img width="549" alt="Skärmavbild 2024-05-29 kl  16 38 10" src="https://github.com/Dielee/volvo2mqtt/assets/2930823/0b594c34-8fe6-46e2-86c9-4e2245216e0b">

**Comment by Dielee** [comment]
If the otp is isn't valid, the addon restarts and tries again. That's the reason for 000000 after reboot. I don't know why the Volvo API don't want your OTP.

**Comment by ahlburg** [comment]
Do you know where I can test the "OTP" function? Very little informaion about Volvo and OTP...
Any ideas how I can use this addon?

**Comment by Dielee** [comment]
There is no possibility to "test".
OTP is only valid for a few seconds. Have you tried to wait a few seconds before pasting the OTP?

**Comment by ahlburg** [comment]
I think I have tried everything. What is the order of things here? 1. Start the addon so it calls for a new OTP from Volvo API. 2. Watch the addon crash because it can't find a correct OTP. 3. Open email, paste the received code and push it with mqtt. 4. Start the addon and hope for the best?

**Comment by ahlburg** [comment]
Do you mean that Volvo has a system that have OTPs that only works for "a few seconds"? Sounds like a very strange policy...

**Comment by ahlburg** [comment]
Hmmm, wait now... Everytime the addon is started, it tells Volvo to send out a new OTP, which means the old one becomes obsolete, which means that this can never work... We are missing something in our communication here. Can you please one more time tell me how this is supposed to work?

**Comment by Dielee** [comment]
1. Install the addon 
2. Fill in your credentials, which are working for the Volvo app
3. Fill in all the other settings, mqtt, TZ, etc..
4. Start the addon
5. The addon now starting the otp auth
6. You are getting an email
7. Fill the either into the text entity or post it via mqtt service
8. Have fun

**Comment by ahlburg** [comment]
> 1. Install the addon
> 2. Fill in your credentials, which are working for the Volvo app
> 3. Fill in all the other settings, mqtt, TZ, etc..
> 4. Start the addon
> 5. The addon now starting the otp auth
> 6. You are getting an email
> 7. Fill the either the otp into the text entity or post it via mqtt service
> 8. Have fun

Thank you, but one step is missing. When the addon starts and requesting the otp auth it crashes and the next time I try to start it , it request a new code, which means the old one is incorrect (obsolete) and the addon crashes again... Because you know how the addon works. Why does it crash, instead of waitng for a correct OTP?

**Comment by Dielee** [comment]
So you start your addon and it crashes immediately without doing anything?

**Comment by ahlburg** [comment]
> So you start your addon and it crashes immediately without doing anything?

May 29 17:48:37 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.2
May 29 17:48:37 volvo2mqtt [106] - INFO: Starting login with OTP
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 73, in authorize
    response = send_otp(auth_session, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 164, in send_otp
    raise Exception(message["details"][0]["userMessage"])
Exception: This passcode is invalid or has expired.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
Is it possible that you are sending your otp codes as "retained" message ? Or even send a "retained" message before to this topic?

**Comment by ahlburg** [comment]
> Is it possible that you are sending your otp codes as "retained" message ? Or even send a "retained" message before to this topic?

That is possible. Not sure what that means? I see there is a checkbox (currently checked) in the mqtt publish.

**Comment by ahlburg** [comment]
Makes absolutely no difference when set to false...

**Comment by Dielee** [comment]
> Makes absolutely no difference when set to false...

Sure, as the message is already retained inside the mqtt broker. Please read how mqtt retain works and clear the retained message.

**Comment by ahlburg** [comment]
> > Makes absolutely no difference when set to false...
> 
> Sure, as the message is already retained inside the mqtt broker. Please read how mqtt retain works and clear the retained message.

That made it!!! Thank you for your patience and support!

**Comment by Dielee** [comment]
Fixed this issue with version v1.9.3.
