### ISSUE TITLE
2014 V60 D6 PHEV battery data not completely populated since 1.9.0

### ISSUE THREAD

**Issue by bigbadbitbasher** [Dielee/volvo2mqtt#194]
**Describe the bug**
Some battery properties for my 2014 V60 D6 Plug-in Hybrid are broken since version 1.9.0. They used to work fine in 1.8.9.
These properties are populated _correctly_ in 1.9.1:

- V60 Battery Capacity
- V60 Distancy to Empty Battery
 
But these are broken since 1.9.0:
- V60 Battery Charge Level
- V60 Charging Connection Status
- V60 Charging System Status

**To Reproduce**:
(add a 2014 V60 D6 in the Volvo account being used :-))
-- I am aware this cannot be easily reproduced -- please contact me if you need debug data --

**Expected behavior**:
The properties:

- V60 Battery Charge Level
- V60 Charging Connection Status
- V60 Charging System Status

Should be populated correctly, like they used to do in 1.8.9.

**Version info**:<br>
1.9.0 and 1.9.1 in Homeassistant as Add-On.

**Logs**:
...
May 27 18:33:44 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
May 27 18:33:44 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "790e23db-6a2f-4636-ae0c-2403c9042644",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "Car model is not supported"
  }
}
...

**Comment by Dielee** [comment]
This has nothing to do with the new authentication. Volvo may work on the API. Just wait and maybe restart the addon some times.

**Comment by Dielee** [comment]
The 404, comes from the Volvo API. Your "Charging connection status" isn't supported by your car.

**Comment by Dielee** [comment]
Nothing else, than the auth changed in 1.9.0. Charging connection status comes form the energy API, which only works for fully electric cars.
