### ISSUE TITLE
getting Volvo ID verification code mails from Volvo since latest update

### ISSUE THREAD

**Issue by sgbossinga** [Dielee/volvo2mqtt#195]
Integration is not working and getting Volvo ID verification code mails from Volvo since latest update, every 2 minutes.
Mails contain six digit numbers.

Version: 1.9.1

**Comment by Dielee** [comment]
Then the plugin waits for authentication....

**Comment by sgbossinga** [comment]
where can I find this?

**Comment by Dielee** [comment]
Please read the readme.

**Comment by sgbossinga** [comment]
thanks got it
