### ISSUE TITLE
Add DOCS.md + update CHANGELOG.md on release

### ISSUE THREAD

**Issue by gurtjun** [Dielee/volvo2mqtt#199]
**Is your feature request related to a problem? Please describe.**
1. Currently there is no "Documentation" tab on the add-on's page in Home Assistant. 
2. Changelog is outdated.

**Describe the solution you'd like**
1. It would be nice to have the documentation (currently available on Github) in the "Documentation" tab on Home Assistant. This can be done by adding `DOCS.md` to `/src` in your repository.
2. Update `CHANGELOG.md` everytime a new version is released.

**Describe alternatives you've considered**
None

**Additional context**
The "Documentation" tab can help people configuring their add-on in Home Assistant.

**Comment by Dielee** [comment]
Yes, i missed the changelog. Will fix this now. 
Documentation is here at github.

**Comment by gurtjun** [comment]
> Yes, i missed the changelog. Will fix this now. Documentation is here at github.

Documentation is indeed here at GitHub but adding it to a `DOCS.md` file will also make it available at Home Assistant. 
I believe this would have prevented all the current complaints at community.home-assistant.io.

**Comment by Dielee** [comment]
Maybe, but this thing is already huge and needs much care. I don't want to add another file, sorry.
