### ISSUE TITLE
RasPi build?

### ISSUE THREAD

**Issue by HWiese1980** [Dielee/volvo2mqtt#2]
Hey, thanks for the extension. I would like to ask if you could build an arm/v7 version of the image to be run on a Raspberry Pi 4. That's where my Home Assistant is running. 

Thank you very much!

**Comment by Dielee** [comment]
Yes, I will have a look later this day!

**Comment by HWiese1980** [comment]
That is awesome and greatly appreciated :-)

**Comment by Dielee** [comment]
Starting the last release (v1.0.1.1) multi arch is supported. Please test!

**Comment by amurray81** [comment]
Hi. Eager to test this on a C40 but not yet experienced enough in HA to know how to installl this.
Im using  a Pi and have HA OS 10.3 with many integrations already working. 
Any other installation instructions on how to set this up, or make it an add on would be appreciated.
Thank You

**Comment by Dielee** [comment]
Yes, HA Addon is planed. But not yet ready.

**Comment by Travikxs** [comment]
> Yes, HA Addon is planed. But not yet ready.

Great! when we have the HA Addon I'll test with XC60 2023
Thank you :)

**Comment by Dielee** [comment]
Maybe take a look at #14

**Comment by Travikxs** [comment]
> 

It is working perfectly :) Thank you
