### ISSUE TITLE
No "Tank Lid" sensor changes

### ISSUE THREAD

**Issue by Elekesey** [Dielee/volvo2mqtt#203]
**Describe the bug**
Tank Lid doesn't rise any status other than "off" on european Volvo XC40 Recharge (full EV).

**To Reproduce**:<br>
1. Open tank lid of the vehicule.
2. Check status of sensor "XC40 (2024) - YV1XZEPT8R******* Tank Lid" and see it doesn't change.

**Expected behavior**:<br>
When I open tank lid, I expect to see status of sensor switch to "on".

**Version info**:<br>
- Volvo2Mqtt 1.9.3
- Core 2024.6.2
- Supervisor 2024.06.0
- Operating System 12.3
- User interface 20240610.0
- HA Docker version

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
<b>If you are using the HA Addon the log location is `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

**Comment by Dielee** [comment]
Please send debug logs from opened and closed tank lid

**Comment by FireWizard52** [comment]
Hi,

On my XC40 PHEV 2023 I see  for tankLid, when quering: https://api.volvocars.com/connected-vehicle/v2/vehicles/"Volvo_VIN"/doors for value "UNSPECIFIED".
So obviously it is not implemented for all cars.

Regards

**Comment by Elekesey** [comment]
Hi,

Sorry for ma late answer. I would love to send you debug logs but cannot find the way to transfer it from HA machine... In the meantime, I enabled API debug log and see this :

![image](https://github.com/Dielee/volvo2mqtt/assets/125213620/53900c8a-83c5-4e2e-91ee-52036f7374a0)

**Comment by Elekesey** [comment]
> Hi,
> 
> On my XC40 PHEV 2023 I see for tankLid, when quering: [https://api.volvocars.com/connected-vehicle/v2/vehicles/"Volvo_VIN"/doors](https://api.volvocars.com/connected-vehicle/v2/vehicles/%22Volvo_VIN%22/doors) for value "UNSPECIFIED". So obviously it is not implemented for all cars.
> 
> Regards

Tried to execute that but didn't found how to pass the full authentication. It says :
```
{
  "error": {
    "message": "Unauthorized",
    "description": "Full authentication is required to access this resource"
  }
}
```

**Comment by JohanLanderholm** [comment]
I have a new EX30, and my "tank lid" is always indicated as Open. 
I assume it's a buggy API, as there are so many bugs in the onboard system in the EX30.

**Comment by Elekesey** [comment]
I was wondering if it could be a broken sensor on the tank lid of the car. But can’t find enough information on web about that…

**Comment by JohanLanderholm** [comment]
I think the whole Volvo API is very much "work-in-progress" so I guess we'll see some fixes in tve future.

**Comment by andynash** [comment]
I have an XC90 T8, ie a PHEV, so there are two 'tank lids', one for petrol, one for charging.

This API value works for me, but only for the petrol tank lid (which is a shame because the one I occasionally leave open is the charging one).

I would expect therefore that this sensor is specifically for the petrol tank lid in PHEV and petrol-only vehicles - full EVs won't get any info regarding their 'charging lid'.
