### ISSUE TITLE
Target battery charge level and charging current limit

### ISSUE THREAD

**Issue by mhpleite** [Dielee/volvo2mqtt#204]
Would like to have new energy API endpoints implemeted like:
1. Target battery charge level
2. Charging current limit

See https://developer.volvocars.com/apis/energy/v1/endpoints/target-battery-charge-level/

 Many thanks in advance.

**Comment by Dielee** [comment]
As said in #181, the new endpoints are not working at this time, sorry.

**Comment by Dielee** [comment]
It's not working from the API itself.. only from the Volvo page, sorry.

**Comment by bmesuere** [comment]
I suspect they will add a new endpoint (to the documentation) since the app now allows you to set the target battery percentage. The endpoints described in this issue only offer getters.

**Comment by Dielee** [comment]
Not all app functionality will be available as an endpoint....
