### ISSUE TITLE
Combine Charging Connection Status and Charging System Status

### ISSUE THREAD

**Issue by mmierke** [Dielee/volvo2mqtt#213]
**Describe the solution you'd like**
Combine Charging Connection Status and Charging System Status into a single sensor with the values disconnected, connected, charging

**Describe alternatives you've considered**
Today I use a helper template sensor to achieve the same
{% if is_state("sensor.volvo_..._charging_connection_status","Disconnected")-%}
  disconnected
{%- else -%}
  {% if is_state("sensor.volvo_..._charging_system_status","Charging")-%}
    charging
  {%- else -%}  
    connected
  {%- endif %}
{%- endif %}

**Additional context**

**Comment by Dielee** [comment]
Volvo2mqtt only delivers raw API data, I will not change this. Sorry.
