### ISSUE TITLE
Temperature at car

### ISSUE THREAD

**Issue by darek203** [Dielee/volvo2mqtt#214]
**Is your feature request related to a problem? Please describe.**
Not a problem at all, rather and enhancement request based on that I've recently found in the iOS APP.

**Describe the solution you'd like**
1. In the "Climate" section of the iOS app there is "Temperature at car" visible (2023 XC40 BEV). Would it be possible to pull that information into the HA?
2. I believe there is as well an external temperature sensor available. Would it be possible to pull that into the HA?
3. Is there any possibility to remotely open a window in the car? It's "status" is already visible in the iOS app.

**Describe alternatives you've considered**
No alternative solutions or features as of now.

**Additional context**
Attaching screenshots.
![temp at car](https://github.com/user-attachments/assets/d9a53b0f-cd61-480f-b4c0-e7187b7a02ec)
![external temp](https://github.com/user-attachments/assets/2329b95f-eb93-4187-a1e7-97d73e9995f8)

**Comment by Dielee** [comment]
They removed the API endpoint for the outside temperature with V2. So we can't get this data.

**Comment by darek203** [comment]
How about inside temp? Was that also removed? I'm interested specifically into the inside temp...

**Comment by Dielee** [comment]
There wasn't any endpoint for the inside temp, sorry

**Comment by darek203** [comment]
oh.. I understand... I assume that's the same one... they just showing that in two different places in the app. One last question regarding point #3 -> Is there any possibility to remotely open a window in the car? It's "status" is already visible in the iOS app.

**Comment by Dielee** [comment]
No, the API only provides states for the windows, no option to open or close...
