### ISSUE TITLE
Enteties become unavailable

### ISSUE THREAD

**Issue by ericedberg** [Dielee/volvo2mqtt#215]
**Describe the bug**
Several times a day entetis become unavailable for no reason. Reboot volvo2mqtt resolve problem but att few minutes its unavailable again

**To Reproduce**:<br>
Just happens

**Expected behavior**:<br>
Work as it would. 

**Screenshots**:<br>

**Version info**:<br>
Version 1.9.4 HA-addon 
Core version 2024.7.2
**Logs**:<br>
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:44:02 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "70095149-3e47-40ef-8e5f-15224cf2e308",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:44:03 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "70095149-3e47-40ef-8e5f-15224cf2e308",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:44:08 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:44:13 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 20 08:49:13 volvo2mqtt [106] - INFO: Sending mqtt update...
Jul 20 08:49:18 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "246a4151-5c6f-46fd-9440-9d1ca74f7ca2",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:19 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "246a4151-5c6f-46fd-9440-9d1ca74f7ca2",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:19 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "246a4151-5c6f-46fd-9440-9d1ca74f7ca2",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:19 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "246a4151-5c6f-46fd-9440-9d1ca74f7ca2",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:19 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "246a4151-5c6f-46fd-9440-9d1ca74f7ca2",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:19 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "246a4151-5c6f-46fd-9440-9d1ca74f7ca2",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:24 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:49:29 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 20 08:54:29 volvo2mqtt [106] - INFO: Sending mqtt update...
Jul 20 08:54:35 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 500. Error: {
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
Jul 20 08:54:41 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 20 08:59:41 volvo2mqtt [106] - INFO: Sending mqtt update...
Jul 20 08:59:42 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 20 09:04:42 volvo2mqtt [106] - INFO: Sending mqtt update...
Jul 20 09:04:43 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 20 09:09:43 volvo2mqtt [106] - INFO: Sending mqtt update...
Jul 20 09:09:45 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 20 09:14:45 volvo2mqtt [106] - INFO: Sending mqtt update...
Jul 20 09:14:45 volvo2mqtt [106] - INFO: Refreshing credentials
Jul 20 09:14:47 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.Ja

**Comment by Dielee** [comment]
This is a Volvo API error.. just wait.

**Comment by ericedberg** [comment]
> This is a Volvo API error.. just wait.

It’s been for a week or so. Anyone else has the problem too?

**Comment by rubenv** [comment]
Strange thing is that a restart of the pod seems to fix things.

**Comment by PolarFox** [comment]
For me this seems to happen when the Volvo API rate limit is being hit when refreshing too often.
