### ISSUE TITLE
Entity_Picture attribute on Device_Tracker entity

### ISSUE THREAD

**Issue by denkyem** [Dielee/volvo2mqtt#217]
Would be perfect if the device_tracker entity had an entity_picture attribute, that way the image of the car would be show on the map instead of the name initial

Thanks

**Comment by Dielee** [comment]
Starting which ha version is this feature available?

**Comment by denkyem** [comment]
I don't know for sure, but I have that on my motorcycle tracker for almost 2 years now.
I used customize.yaml to do it, I can do the same for the car, but since the addon already have the image url, it's just a matter of putting the same attribute on the device_tracker entity.

This is my motorcycle
<img width="211" alt="image" src="https://github.com/user-attachments/assets/75f0e2f8-aa7f-49fa-b73b-326bdae3e98f">

![image](https://github.com/user-attachments/assets/8bb798a8-5a0f-4c7a-b61d-d76004150d66)

**Comment by Dielee** [comment]
HomeAssistant does not support setting the entity_picture for the mqtt device_tracker entity. 
So there is no option to add this feature at this time, sorry.

Available options are:
https://www.home-assistant.io/integrations/device_tracker.mqtt/

**Comment by denkyem** [comment]
> HomeAssistant does not support setting the entity_picture for the mqtt device_tracker entity. So there is no option to add this feature at this time, sorry.
> 
> Available options are: https://www.home-assistant.io/integrations/device_tracker.mqtt/

Oh, too bad.
I'll do it with the customize.yaml

Thank you for trying 👍
