### ISSUE TITLE
Exterior and interior images keep getting broken

### ISSUE THREAD

**Issue by sammyke007** [Dielee/volvo2mqtt#219]
**Describe the bug**
Hi
First: tnx for this GREAT addon!

1 question: most of the time my exterior and interior images get broken:

<img width="155" alt="image" src="https://github.com/user-attachments/assets/e189bb9b-4d18-4db4-90fc-cc23ff5ceb87">

Sometimes refreshing the browser works, but not always.
If I try to browse to the images URL, I receive a "500: Internal Server Error"
Any hint/idea why this happens please?

**Comment by parisfox** [comment]
Hi,

Same here. Started 2 days ago...

**Comment by Dielee** [comment]
I would like to help you, unfortunately this is an API issue. If the images can't be reached on the Volvo servers, the images seem to be broken. Maybe I will take a look and download the files at the first addon start.
 
Is this issue already there ?

**Comment by sammyke007** [comment]
> I would like to help you, unfortunately this is an API issue. If the images can't be reached on the Volvo servers, the images seem to be broken. Maybe I will take a look and download the files at the first addon start.
> 
> Is this issue already there ?

Tnx for looking into this. 

Both after reloading the addon and even after a full HAOS restart, I can't get it to load the images anymore. It would be nice if I could download them somewhere and just put it offline available.

**Comment by Dielee** [comment]
I will check if the images are available at all...

**Comment by Dielee** [comment]
Please try version 1.9.6. Volvo has severely restricted access to the images. It is very difficult to get the pictures back...

**Comment by sammyke007** [comment]
Fixed! I'll try to save a copy offline, tnx!

**Comment by Dielee** [comment]
The addon saves a copy ;) So the images are only downloaded if you update or recreate the addon.
