### ISSUE TITLE
Odometer is off by a power of 10

### ISSUE THREAD

**Issue by kristofferbj** [Dielee/volvo2mqtt#22]
My odometer in the car shows 2154 km but volvo2mqtt shows 215 km.

Received 9:17:24 PM
QoS: 0
Payload: 215

**Comment by Dielee** [comment]
Thanks! Will check this tomorrow.

**Comment by Dielee** [comment]
You are right... The API delivers not the exact value. I multiply the value by ten. There is nothing more I can do at this time. Sorry...

**Comment by kristofferbj** [comment]
Hm, what do you mean? If you multiply 215 by 10 you get 2150. That would be close enough. But 215 instead of 2154 is not really close ... 😉

**Comment by Dielee** [comment]
Yes, you are right. But the api should deliver the full odometer value. It's very odd...

**Comment by kristofferbj** [comment]
Yes. But multiplying by 10 works for me. Thanks for the quick fix.
