### ISSUE TITLE
decoder.py error

### ISSUE THREAD

**Issue by Corsw** [Dielee/volvo2mqtt#220]
**Describe the bug**
Sins 2 days the addon doesnt connect anymore, it seems to be some error with the stored login credentials?

**Version info**:<br>
1.9.5

**Logs**:<br>

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Aug 07 21:33:46 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.5
Aug 07 21:33:46 volvo2mqtt [106] - INFO: Using login from token file
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 43, in authorize
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
Please enable debug and send the logs

**Comment by Corsw** [comment]
[volvo2mqtt.log](https://github.com/user-attachments/files/16539900/volvo2mqtt.log)
 Here is the requested log

**Comment by Dielee** [comment]
This contains no debug informations.. Please enable debug!

**Comment by Corsw** [comment]
There is something odd then, the debug is enabled:
![Debug enabled](https://github.com/user-attachments/assets/90e94549-9bce-476b-b250-b1d4cd147fbd)
But even after rebooting HA and manualy starting the addon i dont see changes in the log:
[volvo2mqtt.log](https://github.com/user-attachments/files/16540625/volvo2mqtt.log)

**Comment by Dielee** [comment]
Please reinstall the addon. Maybe the token file is corrupted

**Comment by Corsw** [comment]
Would it be possible to manually replace the file with one from a backup? i'm not looking forward to renaming the entities after a reinstall :)

**Comment by Dielee** [comment]
No, the file is stored inside the container. Entities will remain while reinstalling

**Comment by Corsw** [comment]
Reinstalling the add-on doesn't fix the issue. After removing the add-on I have rebooted HA to confirm the add-on was gone, and installed it again. Unfortunately, I keep getting the same issue. After the reinstall of the add-on I expected to have to relogin, but that wasn't possible. Can i force this in another way?

**Comment by Dielee** [comment]
Please delete the following file and start the addon:   "/addons/volvo2mqtt/token/.token"

**Comment by Corsw** [comment]
After deleting this fiile the OTP request came through and all is working like before.

Thank you very much for your fast responses, and for this awsome add-on!

**Comment by Dielee** [comment]
I will take care of this issue inside the code. Thanks for the coffee ☕.
