### ISSUE TITLE
climate control not working

### ISSUE THREAD

**Issue by silkyclouds** [Dielee/volvo2mqtt#226]
**Describe the bug**
in short, the car can be locked / unlocked without any issue, but I cannot start the climate control. I'd like to figure out a way to enable the climate for my car like we can do it in the volvo app, for a specific amount of time. 

I have an XC60 2022, with the option to start/stop the climate working from the official volvo app. 

As winter will be back soon, I'd like to automate the warming of my car upfront leaving to work / drive my kids to school, if a specifically setup temperature is met outside. 

**To Reproduce**:<br>
Go to HA, find the climate button : 

<img width="419" alt="image" src="https://github.com/user-attachments/assets/4bc89bef-1ea0-4675-8ba7-e0ebf81820dc">

click on the climate button and see it going "on" 

<img width="437" alt="image" src="https://github.com/user-attachments/assets/554ec8d9-bb9b-4448-a4c1-f1254485c552">

**Expected behavior**:<br>
when the button is pressed, the car should start climatising (either cooling or warming the car)

**Screenshots**:<br>
see above

**Version info**:<br>
latest version always updated and running through add-ons

**Logs**:<br>
Aug 26 12:56:07 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "climatization-start is not supported by this vehicle"
  }
}
Aug 26 12:56:29 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "climatization-stop is not supported by this vehicle"

**Comment by Dielee** [comment]
So, the API says your car don't support climate start and stop, I can't do anything for you. Sorry.

**Comment by silkyclouds** [comment]
Hi @Dielee  and thanks for the fast answer :) 

I understand the API rejects my requests, but I believe this is more something "blopcked" by volvo than a real incapacity to start the climate control. 

So I was more thinking "are we sure the right API call gets triggered?" than "my car can"t do it, period" :) 

As this feature Is part of the very limited set of possible actions in the volvo app (I basically can lock/unlock the car, which works through volvo2mqtt, and start climate), I'm currious why these XC 60 models wouldn't be allowed to act on it through the API.

I legitimetely think that opening the car is 100% as insecure as starting the climate to be honest, it is therefore weird volvo allows the first through the API, and not the second.
