### ISSUE TITLE
Update from 1.9.5 to 1.9.6 fails: The command [...] returned a non-zero code: 2

### ISSUE THREAD

**Issue by westlund** [Dielee/volvo2mqtt#227]
The update from 1.9.5 to 1.9.6 fails - similar to #201 

`The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2`

when attempting update from 1.9.5 to 1.9.6.

**Supervisor log**

```
2024-08-23 12:30:35.473 ERROR (MainThread) [supervisor.docker.addon] Can't build 982ee2c4/aarch64-addon-volvo2mqtt:1.9.6: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2
2024-08-23 12:30:35.474 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> 5323f8eef0b6

Step 3/15 : RUN apk add --no-cache python3 bash py3-pip


 ---> Running in 8e0cf987a122

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz

**WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)**

ERROR: unable to select packages:
  py3-pip (no such package):
    required by: world[py3-pip]
  python3 (no such package):
    required by: world[python3]

 ---> Removed intermediate container 8e0cf987a122

```

**My system**
```
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0
```

The error has persisted since the 1.9.6 upgrade. At the time I was running a Home Assistant Green with Core 2024.7.0+, which I just updated to Yellow by restoring a backup to it.

When I try fetching `https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz` with curl it works, I can download the file to both my HA instance as well as locally on my own client (macOS) using

`curl -o file.tar.gz https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz`

@Dielee: I have waited a few weeks reporting this to see if this eventually disappears with time (just as it did the last time) or after my planned hardware update to HA Yellow, but to no avail. Do you have any clue where to look next or if this is an issue for the core or supervisor teams? I have had no there problems whatsoever updating the system or other addons/integrations. I am managing one more similar HA and that system updated without a blink. I am in despair!

**Comment by Dielee** [comment]
The reason your update isn't working, is the missing "py3-pip" package inside upstream v3.20 main repo from alpine. 
https://pkgs.alpinelinux.org/packages?name=py3-pip&branch=v3.20&repo=main&arch=aarch64&maintainer=

I added the community repo inside the docker file. Please try again to build the addon. 
Make sure the new Dockerfile will be used!

**Comment by westlund** [comment]
I Thanks! will get back ASAP after I have time to try it.

**Comment by Dielee** [comment]
So the addon management form HA should do this. 
Just remove the addon and try to reinstall.
