### ISSUE TITLE
Issue, but not a bug,

### ISSUE THREAD

**Issue by geedsen** [Dielee/volvo2mqtt#229]
I lost my HA SSD. I managed to get one part of a recent backup  from it.  I reinstalled HA and restored the backup. Most started working immidiately. But not the Volvo2MQTT part. It is there but all entities are unavailable. So I went Add Ons and added Volvo2Mqtt again. 
But now I need the vccapikey.  So I log in to the volvo developer portal.  I assumed I should see this on "my API applications" but the only thing I get is 
![image](https://github.com/user-attachments/assets/221aad09-61fd-46fc-92f6-be48c8d7a118)
Should I indeed just wait? 

Thanks

  Ben

**Comment by Dielee** [comment]
It looks like you just have to wait...
