### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by larronni** [Dielee/volvo2mqtt#23]
It looks like some of the sensors are not updated for a Volvo V90 T8
![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/9043d814-9405-411f-a5fe-032547076c09)

If I look at the Volvo On Call integration in Home Assistant, these sensors are updated...
![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/9bc54f1e-6ede-4f37-b089-29f889873213)
![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/99c08dcd-d4f2-4c39-85d6-039c0db44344)

**Comment by Dielee** [comment]
Is your addon running ? 
Are there any exceptions inside the logs ?

**Comment by larronni** [comment]
All other sensors are updated, so the addon is running (and it is updated every 300 sec).

**Comment by larronni** [comment]
With v 1.3 the battery status is updated
![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/ccb0ed16-aa6f-43d8-b964-037818ecd5bd)

**Comment by Dielee** [comment]
Okay, maybe a bug in the old version.
