### ISSUE TITLE
JSON decode error at addon start

### ISSUE THREAD

**Issue by gerliczky** [Dielee/volvo2mqtt#232]
**Describe the bug**
I get an error message after validateing VCCPAPIKEY.

**To Reproduce**:<br>
1. Exception happens, at addon start.

**Version info**:<br>
1.9.6 HA Addon

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
<b> s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Sep 14 06:30:11 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.6
Sep 14 06:30:11 volvo2mqtt [106] - DEBUG: MQTT Credentials - Host core-mosquitto Port: 1883 User: addons Pass: saez1ienohr1sohx5aiw8eetohdesheequiethaewahsh1Ooshoopie5zaeQuuth
Sep 14 06:30:11 volvo2mqtt [106] - INFO: Using login from token file
Sep 14 06:30:11 volvo2mqtt [106] - INFO: Refreshing credentials
Sep 14 06:30:11 volvo2mqtt [106] - DEBUG: VCCAPIKEY <REDACTED> works!
Sep 14 06:30:11 volvo2mqtt [106] - DEBUG: [{'key': <REDACTED>, 'extended': False, 'extended_until': None, 'in_use': False}]
Sep 14 06:30:11 volvo2mqtt [106] - INFO: Using VCCAPIKEY: <REDACTED>
Sep 14 06:30:11 volvo2mqtt [106] - DEBUG: [{'key': <REDACTED>, 'extended': False, 'extended_until': None, 'in_use': True}]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 106, in authorize
    get_vehicles()
  File "/volvoAAOS2mqtt/volvo.py", line 208, in get_vehicles
    data = vehicles.json()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Sep 14 06:30:16 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.9.6
Sep 14 06:30:16 volvo2mqtt [106] - DEBUG: MQTT Credentials - Host core-mosquitto Port: 1883 User: addons Pass: saez1ienohr1sohx5aiw8eetohdesheequiethaewahsh1Ooshoopie5zaeQuuth
Sep 14 06:30:16 volvo2mqtt [106] - INFO: Using login from token file
Sep 14 06:30:16 volvo2mqtt [106] - INFO: Refreshing credentials
Sep 14 06:30:16 volvo2mqtt [106] - DEBUG: VCCAPIKEY <REDACTED> works!
Sep 14 06:30:16 volvo2mqtt [106] - DEBUG: [{'key': '<REDACTED>', 'extended': False, 'extended_until': None, 'in_use': False}]
Sep 14 06:30:16 volvo2mqtt [106] - INFO: Using VCCAPIKEY: <REDACTED>
Sep 14 06:30:16 volvo2mqtt [106] - DEBUG: [{'key': <REDACTED>, 'extended': False, 'extended_until': None, 'in_use': True}]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 106, in authorize
    get_vehicles()
  File "/volvoAAOS2mqtt/volvo.py", line 208, in get_vehicles
    data = vehicles.json()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
It looks like the vehicle's url response with some garbage. You have two options:

1. Retry the endpoint from time to time until Volvo fixes this behavior.

2. Work around this endpoint and provide your VIN manually.

**Comment by KristianAndersson** [comment]
Same issue here. The workaround with adding the VIN number in the config, made it start up correctly.

**Comment by gerliczky** [comment]
Thanks for your quick response. The entering the VIN solved the issue.
