### ISSUE TITLE
allow 2 logins (volvo "normal" app and ex30 app)

### ISSUE THREAD

**Issue by tretabyte** [Dielee/volvo2mqtt#236]
**Is your feature request related to a problem? Please describe.**
I have 2 Volvos, one XC40 BEV (2024) and a EX30, each one uses a different app which makes it a pain to manage.

**Describe the solution you'd like**
Allow the addon, similar to what already has related to multiple keys, to have multiple accounts.

**Describe alternatives you've considered**
I could try to clone the addon and run it twice but it might generate other issues or concurrency errors somewhere within HA.

**Additional context**
This is more like a feature/enhancement request, since somehow EX30 now works also :)

**Comment by Dielee** [comment]
This would require a lot of rework. 
You have two options:

1. Run volvo2mqtt twice with different credentials
2. Try to add both cars to one Volvo Account

**Comment by tretabyte** [comment]
Hi,
option 2 doesn't work for me because the second car needs to be on my wife's account :|
option 1, do you mean run another instance of the add-on with a different set of credentials?

**Comment by Dielee** [comment]
Volvo offers to add the car to multiple Accounts, just select "Add Car" in your Volvo app and connect it.
