### ISSUE TITLE
API: Service not enabled

### ISSUE THREAD

**Issue by geedsen** [Dielee/volvo2mqtt#240]
Probably not a bug.
I had to rebuild HA from a (partial) backup I had. It installed the Volvo2MQTT but lost the configuration.
So I added this again. 
But I only get this in the log as a result:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[19:15:19] ERROR: Got unexpected response from the API: Service not enabled
Sep 30 19:15:20 volvo2mqtt [107] - INFO: Starting volvo2mqtt version v1.10.1
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 13, in <module>
    set_mqtt_settings()
  File "/volvoAAOS2mqtt/util.py", line 159, in set_mqtt_settings
    raise Exception("MQTT connection could not be established. Please check if your MQTT Add-On is running!")
Exception: MQTT connection could not be established. Please check if your MQTT Add-On is running!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

I see others with the same errors, but dont see what their solution really was.  I verified the username and password to login again in the app, no problem.  I went to the volvo developer portal, and loged in. But their I did not see a 'application' so I created a new one and used the vccapikey. But the results is still in the log. I did set the Volvo2Mqtt on 'start on boot' and rebooted, But in the log I could see it never tried starting.  I assume this "lease check if your MQTT Add-On is running!"  is talking about Volvo2MQTT?

ALso when I start it, I get the error in the log. But the UI stays like this: 
![image](https://github.com/user-attachments/assets/c565b351-fa67-4743-9bd6-8940ad17b4e2)
But a refresh page shows the add-on as not started.

**Comment by Dielee** [comment]
As the log said, please check if your mqtt broker is running.

**Comment by geedsen** [comment]
Interessting, I lost the Mosquitto broker as well. So I just reinstalled it.
And indeed when I now Volvo2MQTT, I get the otp mail. But when I set the text.volvo_otp to the value, the log shows that it just continues asking for it:
![image](https://github.com/user-attachments/assets/817844d6-4a88-43e7-b21d-179878ca9abc)

**Comment by geedsen** [comment]
And the broker: 
![image](https://github.com/user-attachments/assets/dd0eddf5-efb0-4f1c-a698-187df22c8f55)

**Comment by geedsen** [comment]
Tried again today, managed to set the otp value when the log showed it was at attempt 4/24 to find it. But the log still just continues....

**Comment by geedsen** [comment]
I removed the volvo2mqtt, and the mosquitto broker. Then installed the broker and then volvo2mqtt, configured it, started it, received the otp value, set the text.volvo_otp value and still, the log shows that it is waiting for the otp value.

**Comment by geedsen** [comment]
And then I noticed that now MQTT needed to be configured again. So I went to Configure...and that  resulted in the otp entity showing. So when I filled in the value there, it all started
