### ISSUE TITLE
some data never update

### ISSUE THREAD

**Issue by Surki69** [Dielee/volvo2mqtt#244]
**Describe the bug**
Almost all data regularly update but data on average speed and average energy consumption never updated since I installed the Volvo2mqtt and pulled data first time. A force update did not change it.

**To Reproduce**:<br>
It's just there, I cannot reproduce.

**Expected behavior**:<br>
I expect all data to update frequently and completely.<br>

**Screenshots**:<br>
If applicable, add screenshots to help explain your problem.<br>

**Version info**:<br>
HA Mosquitto broker 6.4.1, HA 10.1, Volvo2mqtt 1.10.1<br>

**Logs**:<br>
None. <br>
<b>If you are using the HA Addon the log location is `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

**Comment by Dielee** [comment]
So this may be not supported by your car. Please enable debug and send startup logs.

**Comment by Dielee** [comment]
Enable the debug option and send your logs please. Pretty sure the API doesn't update the values...

**Comment by Surki69** [comment]
Since the latest update of the Volvo2mqtt the problem vanished. I got an update of the  2 parameters, maybe it really had to do with the multipliers that were in the configuration script.

**Comment by Dielee** [comment]
I'm going to close this issue. If the issue persists, please reopen.
