### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by FireWizard52** [Dielee/volvo2mqtt#245]
Hi,

As you might know, I do not use your application in HA, but I use Node-RED. I take the freedom to contact you.

Today I discovered that after a reboot of my Raspberry Pi, needed because some other Node-RED nodes have been updated, I was not able to authorize anymore. The authorization procedure is equal for all applications, regardless, if it is for HA, Domoticz, OpenHab, IObroker, etc.

I received a statusCode 400 and an error message "unauthorized_client".
This has been working for about a year, without a glitch.
I'm afraid they closed a hole and authorizing with only username/password has been terminated.

Do you experience the same?

Regards

**Comment by Dielee** [comment]
What version are you using ?

**Comment by FireWizard52** [comment]
Hello Linus.

Thanks for your response.

As said, I do not use your application, but I use a Node-RED flow. So a version number is not relevant
Since the reboot, I'm not able to authorize anymore. So I'm interested in your experience..
Can you still authorize and do you receive an access token. Or is your application still running with the refresh token?

Regards

**Comment by scholdan** [comment]
Funny you said that my volvo2mqtt works fine but EVCC.io says unauthorized_client
played around a little and now both is unhappy

**Comment by Dielee** [comment]
So both of you are using the otp auth ?

**Comment by Troubadix1986** [comment]
Same problem here. Didn't change any settings though. Maybe volvo is having some issues?

**Comment by Dielee** [comment]
> Same problem here. Didn't change any settings though. Maybe volvo is having some issues?

You are using the Volvo2mqtt addon?

**Comment by Troubadix1986** [comment]
Yes. Using the addon (which works) and evcc (where it won't connect since today). Both use same authentification if i remember right

**Comment by Troubadix1986** [comment]
Correction: volvo2mqtt lost connection too...

**Comment by Dielee** [comment]
Maybe not.. evcc may not use the otp auth. Someone tried to remove the token file and restart OTP auth?

**Comment by Dielee** [comment]
Alright, please enable debug and share the logs.

**Comment by Troubadix1986** [comment]
see log attached.
noticed now that volvo2mqtt is also crashing when starting.
[volvo2mqtt.txt](https://github.com/user-attachments/files/17383303/volvo2mqtt.txt)

**Comment by Dielee** [comment]
Alright. I will take a look tomorrow.

**Comment by FireWizard52** [comment]
Hi all,

I do not know, if this contributes to the discussion and the issues that you experience, but I posted my question not only in this thread, but also on the Github page of a Domoticz developer.

See: https://github.com/akamming/Domoticz_VolvoRecharge_Plugin/issues/10

Volvo enforces now to use 2FA and does not accept anymore the classic method, but as far as I know, @Dielee has implemented it and that all of you use the latest version.

I have not implemented 2FA in my Node-RED flow yet, and will try to do that tomorrow or the day after.

**Comment by Dielee** [comment]
Volvo2mqtt works as designed. @FireWizard52 please add OTP Auth to your NodeRed flow an you will be fine.
