### ISSUE TITLE
Where is this text.volvo_otp?

### ISSUE THREAD

**Issue by dazza120** [Dielee/volvo2mqtt#247]
**Describe the bug**
Sorry i have searched in every bit of HA that i could type and this text.volvo_otp does not come up, I'm using Mosquito MQTT and it sends the code to my email i just have no idea where to paste it? I looked at the script option and as a newb its very confusing what i should do ive read the read me about ten or more times its still very confusing, by all accounts i just need to fine text.volvo_otp to enter my code and then im done but for the life of me i cant find it and no one else seems to have the problem?

HA 2024.10.2 
Ive had to turn it off now as i got about 15 or so emails from volvo can anyone help me get this intergrated please?

**Comment by triple-it** [comment]
Looks like volvo deleted the used client_id h4Yf0b and accompanying secret?
 
```
$ curl -X GET 'https://volvoid.eu.volvocars.com/as/authorize?client_id=h4Yf0b&response_type=code&acr_values=urn:volvoid:aal:bronze:2sv&response_mode=pi.flow&scope=openid%20vehicle:attributes%20energy:recharge_status%20energy:battery_charge_level%20energy:electric_range%20energy:estimated_charging_time%20energy:charging_connection_status%20energy:charging_system_status%20conve:fuel_status%20conve:odometer_status%20conve:environment' -H 'Authorization: Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc=' -H 'User-Agent: vca-android/5.37.0' -H 'Accept-Encoding: gzip' -H 'Content-Type: application/json; charset=utf-8'
<!DOCTYPE html>


<!-- template name: http.error.page.template.html -->



$ 

```

**Comment by dazza120** [comment]
Hi Triple ive managed to add it, OK so ive managed to get this to link to volvo and it pulls the car image but everything is unavailable it is a Volvo XC60 PHEV MY2025

**Comment by triple-it** [comment]
Ok..So one step further.
I thought you were either hitting #238, or maybe my suspicion that Volvo is working/changing/securing some API access regarding the use of client_id "h4Yf0b"

(Connected Api)

Do you see any relevant errors in the log? 
When it tries to obtain an access token?
`
   session.headers.update({"authorization": "Bearer " + token_data["access_token"]})`

**Comment by dazza120** [comment]
SO this is the log which it says its all supported but its all unavailable

Oct 18 21:39:14 volvo2mqtt [106] - INFO: Success! Battery Charge Level is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Battery Capacity is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Electric Range is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Charging System Status is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Charging Connection Status is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Odometer is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Window Front Left is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Window Front Right is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Window Rear Left is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Window Rear Right is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Door Front Left is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Door Front Right is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Door Rear Left is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Door Rear Right is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Tailgate is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Engine Hood is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Tank Lid is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Sunroof is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Lock state is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Location is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Tire Front Left is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Tire Front Right is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Tire Rear Left is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Tire Rear Right is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Fuel Level is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Average Fuel Consumption is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Average Energy Consumption is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Distance to Empty Tank is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Average Speed is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Hours to Service is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Distance to Service is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Time to Service is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Service warning status is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! API Backend status is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Update Interval is supported by your vehicle.
Oct 18 21:39:15 volvo2mqtt [106] - INFO: Success! Warnings is supported by your vehicle.
Oct 18 21:39:18 volvo2mqtt [106] - INFO: Sending mqtt update...
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 16, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 295, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 305, in update_car_data
    last_data_update = format_datetime(datetime.now(util.TZ), format="medium", locale=settings["babelLocale"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/babel/dates.py", line 719, in format_datetime
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/babel/core.py", line 391, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'gb'
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/volvoAAOS2mqtt/mqtt.py", line 179, in on_message
    lock_car(vin)
  File "/volvoAAOS2mqtt/mqtt.py", line 241, in lock_car
    update_car_data(False, {"entity_id": "lock_status", "vin": vin, "state": "LOCKING"})
  File "/volvoAAOS2mqtt/mqtt.py", line 305, in update_car_data
    last_data_update = format_datetime(datetime.now(util.TZ), format="medium", locale=settings["babelLocale"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/babel/dates.py", line 719, in format_datetime
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/babel/core.py", line 391, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'gb'

**Comment by Dielee** [comment]
Your babel locale 'gb' is unsupported. Please check: https://www.ibm.com/docs/en/radfws/9.7?topic=overview-locales-code-pages-supported to get your right locale. The locale is case sensitive.

**Comment by dazza120** [comment]
Hi thanks mate, it’s working well I can see everything now, it doesn’t seem to change the unlock/lock status, but it does actually unlock and lock the vehicle. Thank you

**Comment by nikagersonlohman** [comment]
Anyone find a way to "revoke" the authorization? In my case the authorization flow returns:

1. USERNAME_PASSWORD_REQUIRED (after  /as/authorization.oauth2)
2. COMPLETED (after action=checkUsernamePassword)
3. An access_token (after token.oauth2)
4. But when using the access token it returns:

{
  "status" : 403,
  "operationId" : "1cbf623f-5516-4f96-acd2-a5f1d268d5ed",
  "error" : {
    "message" : "FORBIDDEN",
    "description" : "Access Denied"
  }
}

So the token returned somehow is incorrect. When I do the same from Postman, all is ok...

**Comment by nikagersonlohman** [comment]
A header in one of the other calls caused the access_token to be invalid (even though it was generated)
