### ISSUE TITLE
where to find the topics to control clima and doorlock?

### ISSUE THREAD

**Issue by git5any** [Dielee/volvo2mqtt#248]
**Describe the solution you'd like**

I set up the volvo2mqtt on a proxmox-machine and it works perfectly. I receive all the data from my car (btw: XC40 recharge ER MY24). I do not use Homeassistant, just the mqtt feature to get the data.
Publishing the OTP to volvoAAOS2mqtt/otp_code worked. But how can I switch the clima on and off or lock/unlock the car? I can't figure out the right topics. Could you please put them into the description?

Thank you very much for your work.

**Comment by Dielee** [comment]
This isn't supported, but here you go:

Climate state topic:
homeassistant/switch/<your VIN>_climate_status/state

Climate command topic:
homeassistant/switch/<your VIN>_climate_status/command

Climate Payload:
ON/OFF

Lock state topic:
homeassistant/lock/<your VIN>_lock_status/state

Lock command topic:
homeassistant/lock/<your VIN>_lock_status/command

Lock Payload:
LOCK/UNLOCK

**Comment by git5any** [comment]
Thank you for the fast answer. I got it working now, also found the topics to change the update_interval:

homeassistant/number/(VIN)_update_interval/command

Payload:
300 600 3600 whatever in seconds

and to force an update:

homeassistant/button/(VIN)_update_data/command

Paylod:
PRESS

however with the update_interval I'm not shure if its possible to set higher values than 30min (1800 sec), due to the renewal of the authentication. If its the same loop the setting cant be higher than almost 30 min, if not it wouldn't matter. 
If it is the same timer maybe you could make the authentication seperate?

Once more thank you very much.
