### ISSUE TITLE
Not possible to handover the otp

### ISSUE THREAD

**Issue by radebold** [Dielee/volvo2mqtt#249]
Hi,

I'm using not a HA, but run with iobroker the mqtt. 
Installed the docker on my synology and the mqtt server is my iob instance.
MQTT is working i have some objects:

![grafik](https://github.com/user-attachments/assets/e77a4a05-6cb5-4aa3-bf64-d0021e5b20db)

I have tryed to put in the otp in all of this items, but it dosen't work.

what is wrong, where exactly I have to put in the otp ?

It's possible to use the env variables for this?

Thx.
Thomas

**Comment by Dielee** [comment]
Otp topic:

`volvoAAOS2mqtt/otp_code`

**Comment by radebold** [comment]
> volvoAAOS2mqtt

also possible to put it in a env in the docker container?
I mean you can include it in the next version?

Thx
Thomas

**Comment by Dielee** [comment]
No, as the otp changes so frequently and will only send after the container started.

**Comment by radebold** [comment]
> No, as the otp changes so frequently and will only send after the container started.

it dosen't work for me.
I Started it in a docker container and in the protocol it wait for the otp.
I put it in the field in my broker but it dosen't receive it in the container.

![grafik](https://github.com/user-attachments/assets/ace23094-15b9-4702-9a57-76d910b4aebc)

any tip?

**Comment by Dielee** [comment]
No sorry. Try to publish via mosquito. The payload has to be not retained!

**Comment by Dielee** [comment]
Your topic is wrong. It has to be `otp_code` not`volvo_otp`.

**Comment by radebold** [comment]
> Your topic is wrong. It have to be `otp_code` not`volvo_otp`.

I saw it, was my fault, had created it manually.
I think I'll give up, I have no experience with HA and I can't get the MQTT things created with the correct states in the IOBroker and thus also set otp_code. I'm too stupid or it just doesn't work

**Comment by Dielee** [comment]
Sorry, I can't help you. Maybe just start with mqtt mosquito without iobroker. Just simple mqtt.

**Comment by Dielee** [comment]
`mosquitto_pub -h YourBrokerIP -p YourBrokerPort -t volvoAAOS2mqtt/otp_code -m "YOU OTP"`
