### ISSUE TITLE
Odometer is wrong after last update (1.3)

### ISSUE THREAD

**Issue by larronni** [Dielee/volvo2mqtt#25]
Looks like the car is ready for the scrap yard now... 😂

![image](https://github.com/Dielee/volvo2mqtt/assets/49139069/c5ae9d55-c060-45bb-9fff-20fba99a5b46)

**Comment by Dielee** [comment]
Nice, odomenter seems to deliver strange values. Pls enable debug an show me the API response from odometer.

**Comment by larronni** [comment]
hmm. The log is to long for HA to display it (in the addon section). Do you know where I can get the full log ?

**Comment by Dielee** [comment]
No, sorry. I don't use the HA Addon. If you divide the odometer km by 10, the value is right ?

**Comment by Dielee** [comment]
Please use v1.3.2 and set your own multiplier

**Comment by larronni** [comment]
Nice - works just fine now. Thanks
