### ISSUE TITLE
Schaffe es nicht einen externen MQTT Broker zu verwenden

### ISSUE THREAD

**Issue by Robbi12** [Dielee/volvo2mqtt#253]
Hallo.

Vielleicht kann mir jemand helfen. Ich habe es unter Homeassistant eingerichtet.

Würde jedoch einen externen MQTT Broker verwenden. Hier scheitere ich. Keine Verbindung.

Was muss ich genau eingeben?

Habe die Internetadresse schon in verschiedenen Formaten eingegeben. Auch mit ""

**Comment by Dielee** [comment]
Please ask your question here [link](https://community.home-assistant.io/t/volvo2mqtt-connect-your-aaos-volvo/585699)
