### ISSUE TITLE
Update doc : Volvo2mqtt works fine with Volvo EX30

### ISSUE THREAD

**Issue by jlpower68** [Dielee/volvo2mqtt#254]
I've installed Volvo2mqtt to manage my EX30, and it works fine. Some data unvailables, so it works partially (but its cool anyway).
Thanks for this usefull developpment !

Here is the list of what is supported and unsupported :
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Battery Charge Level is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Battery Capacity is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Electric Range is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Charging System Status is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Charging Connection Status is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Estimated Charging Finish Time is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Odometer is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Last Data Update is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Active schedules is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Window Front Left is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Window Front Right is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Window Rear Left is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Window Rear Right is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Door Front Left is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Door Front Right is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Door Rear Left is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Door Rear Right is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Tailgate is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Engine Hood is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Tank Lid is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Sunroof is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Air Conditioning is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Lock state is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Force Update Data is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Location is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Tire Front Left is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Tire Front Right is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Tire Rear Left is supported by your vehicle.
Oct 27 09:03:25 volvo2mqtt [1] - INFO: Success! Tire Rear Right is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Engine State is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Average Energy Consumption is unfortunately not supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Distance to Empty Tank is unfortunately not supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Distance to Empty Battery is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Average Speed is unfortunately not supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Hours to Service is unfortunately not supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Distance to Service is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Time to Service is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Service warning status is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Washer Fluid Level warning is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! API Backend status is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Success! Update Interval is supported by your vehicle.
Oct 27 09:03:26 volvo2mqtt [1] - INFO: Failed, Warnings is unfortunately not supported by your vehicle.

PS : Docker installation on my Qnap NAS, via Contenair Station app.

**Comment by Dielee** [comment]
Thanks!
