### ISSUE TITLE
Implement "Lock doors with reduced guard" as a variant of "lock doors"

### ISSUE THREAD

**Issue by jlpower68** [Dielee/volvo2mqtt#258]
It seems Volvo API also include a fnction to lock lock doors with reduced guard (alarme with less sensivity) 👍 https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/doors-windows-locks/#lock-doors-with-reduced-guard
It is usefull in some noisy environement, to avoid the siren trigger for no reasons (and for some EX30 owner, with a too sensitive volumetric sensor).

post :
https://api.volvocars.com/connected-vehicle/v2/vehicles/{vin}/commands/lock-reduced-guard

**Comment by MrAdam** [comment]
I use this feature in the Volvo app every time I take the car on a ferry, so would be nice to be able to set this through the addon.

**Comment by MrAdam** [comment]
This feature would still be nice to have, so no need for this issue to become stale
