### ISSUE TITLE
How to use the /commands API to create switches?

### ISSUE THREAD

**Issue by keeganwatkins** [Dielee/volvo2mqtt#259]
**Is your feature request related to a problem? Please describe.**
With our 2023 xc40 Mild-hybrid it's not possible to use the `switch.volvo_{vin}_climate_status` entity that is created by `volvo2mqtt`, because the vehicle is gas and must be started first.

The `https://api.volvocars.com/connected-vehicle/v2/vehicles/{vin}/commands` endpoint will return a list of commands for a given vehicle, for our vehicle I see this in the response:
```json
{
  "data": [
    ...
    {
      "command": "ENGINE_START",
      "href": "/v2/vehicles/{vin}/commands/engine-start"
    },
    {
      "command": "ENGINE_STOP",
      "href": "/v2/vehicles/{vin}/commands/engine-stop"
    }
  ]
}
```

I am wondering if it's possible to create a new switch entity from this data, such that updating the switch value in HA invokes the correct API request for the command.

**Describe the solution you'd like**
At this point I am just wondering what is possible, any advice would be appreciated!

**Describe alternatives you've considered**

**Additional context**

**Comment by Dielee** [comment]
Not possible at this time #118
