### ISSUE TITLE
Add poll to EVCC to check if vehicle is connect before quirying the API

### ISSUE THREAD

**Issue by MartijnvanGeffen13** [Dielee/volvo2mqtt#260]
Currently you poll the vehicle every 5 mins even in the night waking up the vehicle to send SOC information 

If this is only used to feed EVCC for SOC it would be nice to have a poll to EVCC and check if the vehicle is actually connected to the charger and only if connected send out a SOC API query, 

This would drastically limit the API usage and battery drain on the vehicle. EVCC API can provide you with the if connected part. 

So a parameter is EVCC only would be needed so we can skip almost all API pulls only battery related would be needed. and at the same time if this is set a EVCC pull would determine if the vehicle is connected and if connected we can querry the API and at a higher pace like default every 2 min.

**Comment by Dielee** [comment]
As this is an homeassistant addon, I will not implement any evcc functionality, sorry. Maybe someone builds an evcc plugin.

**Comment by MartijnvanGeffen13** [comment]
ok fair, 

Would it be ok if i would do  that based on your work using this module ?

**Comment by Dielee** [comment]
Sure!! Feel free to fork!

**Comment by ivanfmartinez** [comment]
> ok fair,
> 
> Would it be ok if i would do that based on your work using this module ?

You can change the poll time from homeassistant 

```
action: number.set_value
metadata: {}
data:
  value: "{{ periodo }}"
target:
  entity_id: number.volvo_xxxxx_update_interval
```
