### ISSUE TITLE
Provide vehicle location like the Volvo Ex30 app

### ISSUE THREAD

**Issue by Aspyryan** [Dielee/volvo2mqtt#278]
**Is your feature request related to a problem? Please describe.**
Right now in Home Assistant, I can only see "Location" as "Away" for my Volvo EX30, is there any way to get the lat / long or location name from the API?

**Comment by dennistd4** [comment]
It's already there, in the attributes of the location entity:

source_type: gps
latitude: 52.xxxxxx
longitude: 7.xxxxxxx
gps_accuracy: 1
icon: mdi:map-marker-radius
friendly_name: EX30 (2024) - YV12ZEL9xxxxxxxxx Location

**Comment by Aspyryan** [comment]
How do I extract the attributes to a seperate entity?

I also don't see a 'friendly_name'

![image](https://github.com/user-attachments/assets/c0b1f72f-c466-4523-a506-a10a8075261e)

**Comment by dennistd4** [comment]
You can use for example this on a entities card:

`entities:
  - type: attribute
    name: Latitude
    entity: device_tracker.volvo_yv12zel9xxxxxxxxxxx_location
    attribute: latitude`
