### ISSUE TITLE
VCCAPIKEY

### ISSUE THREAD

**Issue by m3rsok3** [Dielee/volvo2mqtt#285]
I have a issue where I cant get my VCCAPIKEY to get  working. I rebooted the Volvo2Mqtt beacuse I could not get the loaction to work and that affected my automations. I have changed the VCCAPIKEY both the primay and the secondary but I still get this issue from the log. 

Dec 09 09:02:34 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.10.5
Dec 09 09:02:34 volvo2mqtt [106] - INFO: Using login from token file
Dec 09 09:02:34 volvo2mqtt [106] - INFO: Refreshing credentials
Dec 09 09:02:34 volvo2mqtt [106] - WARNING: VCCAPIKEY "my api" isn't working! Access denied due to invalid token. The sub claim contains an array instead of a plain string.
Dec 09 09:02:34 volvo2mqtt [106] - WARNING: No working VCCAPIKEY found, waiting 10 minutes. Then trying again!

**Comment by m3rsok3** [comment]
I really hope there will be a fix soon :)

**Comment by mitkovetta** [comment]
I have the same issue. Had the same thing before, the keys just started working after some time.  I think this is on Volvo's side and issue with their API.

**Comment by sschouten** [comment]
Found it,
I had to delete the token file in de addon ,
First stop the addon go to : \addons\volvo2mqtt\token,
the delete the .token file start the addon, and i wil ask for a new token to put in the OTP Field

**Comment by m3rsok3** [comment]
Stupid question but where can the token? I cant find the addon

**Comment by m3rsok3** [comment]
> Found it, I had to delete the token file in de addon , First stop the addon go to : \addons\volvo2mqtt\token, the delete the .token file start the addon, and i wil ask for a new token to put in the OTP Field

Many thanks, I did the same and it works :)
