### ISSUE TITLE
Mqtt port other than 1883

### ISSUE THREAD

**Issue by exxoff** [Dielee/volvo2mqtt#29]
I can’t connect to broker on port 1888. 

**Describe the solution you'd like**
Either a colon separated host:port solution or add a ”port” element to the JSON config.

**Comment by Dielee** [comment]
Yep, I will fix this

**Comment by Dielee** [comment]
Released in version 1.4.1.

**Comment by exxoff** [comment]
World class!

**Comment by Dielee** [comment]
Have fun!
