### ISSUE TITLE
Change mqtt prefix for multiple volvo cars

### ISSUE THREAD

**Issue by christoph-ng** [Dielee/volvo2mqtt#3]
Is it possible to change the mqtt prefix. I want to use mutiple volvo cars.

**Comment by Dielee** [comment]
Please test release v1.0.2. You can now set multiple vins, or leave it empty. It should show every car linked to your account.

**Comment by christoph-ng** [comment]
after inserting. the api key and pulling the new image it's hanging ....

Vin: XXXXXXXXXXXXX found!
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Starting POST call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/commands/lock
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors

**Comment by Dielee** [comment]
It's hanging ? What's your update interval ? 
Do you have inserted a vin manually ?

**Comment by christoph-ng** [comment]
I've tried each VON separately, after each other - works.

For inserting both vin's I don't know the correct syntax, this one is wrong ....
CONF_volvoData='@json {"username": "XXXXXX", "password": "X", "vin": ["XXXVIN1XXX", "XXXXVIN2XXXXX"]", "vccapikey": "ZZZZZ"}'

**Comment by Dielee** [comment]
Yes, this is wrong.

Try this:

`CONF_volvoData='@JSON {"username": "XXXXXX", "password": "X", "vin": ["XXXVIN1XXX", "XXXXVIN2XXXXX"], "vccapikey": "ZZZZZ"}'|

Have you tried to leave the vin empty ? The addon should use all found vins inside your account.

**Comment by christoph-ng** [comment]
Without empty vin string I only get one, here's the output of your suggestion

docker  run   --pull=always -e CONF_updateInterval=300 -e CONF_babelLocale='de' -e CONF_mqtt='@json {"broker": "zzzzz", "username": "", "password": ""}' -e CONF_volvoData='@JSON {"username": "XXXXXXX", "password": "XXXX", "vin": ["VIN1", "VIN1"], "vccapikey": "XXXXXXXXX"}' -e TZ='Europe/Berlin' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest
latest: Pulling from dielee/volvo2mqtt
Digest: sha256:9350ff8ceac562898643cfac7e8abfe5be81183db7143ff1b1a1123034023d5c
Status: Image is up to date for ghcr.io/dielee/volvo2mqtt:latest
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 1, in <module>
    from volvo import authorize
  File "/volvoAAOS2mqtt/volvo.py", line 11, in <module>
    "vcc-api-key": settings["volvoData"]["vccapikey"],
TypeError: string indices must be integers

**Comment by Dielee** [comment]
Your config is wrong. The error `TypeError: string indices must be integers`  is because @JSON needs to be lower case, as described in the README. 

Please run this and nothing else:

`docker run --pull=always -e CONF_updateInterval=300 -e CONF_babelLocale='de' -e CONF_mqtt='@json {"broker": "", "username": "", "password": ""}' -e CONF_volvoData='@json {"username": "", "password": "", "vin": "", "vccapikey": ""}' -e TZ='Europe/Berlin' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest`

If you want to use every vehicle inside your volvo account, leave the vin as it is. If you have multiple cars and only want to use two of them, use `"vin": ["VIN1", "VIN2"]`

**Comment by christoph-ng** [comment]
looks good now - thanks.

root@vm-docker:~# docker run --pull=always -e CONF_updateInterval=300 -e CONF_babelLocale='de' -e CONF_mqtt='@json {"broker": "xxxxxxxx", "username": "", "password": ""}' -e CONF_volvoData='@json {"username": "xxxxxxx", "password": "xxxxx", "vin": "", "vccapikey": "xxxxxxxxxxx"}' -e TZ='Europe/Berlin' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest
latest: Pulling from dielee/volvo2mqtt
Digest: sha256:dadb83e7e8799a775b50eccd6bbcadd8012c8fb863569ccf18ca323e728c8bec
Status: Image is up to date for ghcr.io/dielee/volvo2mqtt:latest
Starting volvo2mqtt version v1.0.4
Vin: ['aaaaaaa', 'bbbbb'] found!
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors

**Comment by Dielee** [comment]
Nice! I will close this issue now. Feel free to reopen.

**Comment by christoph-ng** [comment]
Something is still wrong :-(

If I run the command with empty vin it's just running once and getting an error. If I put both vins in the command ( "vin": ["VIN1", "VIN2"]) it's the same

```
root@vm-docker:/data/docker/volvo2mqtt# docker run --rm=true  --pull=always -e CONF_updateInterval=30 -e CONF_babelLocale='de' -e CONF_mqtt='@json {"broker": "", "username": "", "password": ""}' -e CONF_volvoData='@json {"username": "XXXX", "password": "XXXX", "vin": "", "vccapikey": "XXXX"}' -e TZ='Europe/Berlin' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest
latest: Pulling from dielee/volvo2mqtt
Digest: sha256:15806260614d8f899fab82afd0ed3e2759e77daea771d5192bbca6f94d43ea62
Status: Image is up to date for ghcr.io/dielee/volvo2mqtt:latest
Starting volvo2mqtt version v1.0.5
Vin: ['VIN1', 'VIN2'] found!
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 9, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 76, in update_loop
    update_car_data()
  File "/volvoAAOS2mqtt/mqtt.py", line 107, in update_car_data
    state = volvo.api_call(sensor["url"], "GET", vin, sensor["id"])
  File "/volvoAAOS2mqtt/volvo.py", line 129, in api_call
    response = recharge_response[vin]
KeyError: 'VIN2'
```

If I run this separately its working fine for both vin's

```
root@vm-docker:/data/docker/volvo2mqtt# docker run --rm=true  --pull=always -e CONF_updateInterval=30 -e CONF_babelLocale='de' -e CONF_mqtt='@json {"broker": "XXX", "username": "", "password": ""}' -e CONF_volvoData='@json {"username": "XXX", "password": "XXX", "vin": "VIN1", "vccapikey": "XXX"}' -e TZ='Europe/Berlin' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest
latest: Pulling from dielee/volvo2mqtt
Digest: sha256:15806260614d8f899fab82afd0ed3e2759e77daea771d5192bbca6f94d43ea62
Status: Image is up to date for ghcr.io/dielee/volvo2mqtt:latest
Starting volvo2mqtt version v1.0.5
Vin: ['VIN1'] found!
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Mqtt update done. Next run in 30 seconds.
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Mqtt update done. Next run in 30 seconds.

```


```
root@vm-docker:/data/docker/volvo2mqtt# docker run --rm=true  --pull=always -e CONF_updateInterval=30 -e CONF_babelLocale='de' -e CONF_mqtt='@json {"broker": "XXX", "username": "", "password": ""}' -e CONF_volvoData='@json {"username": "XXX", "password": "XXX", "vin": "VIN2", "vccapikey": "XXX"}' -e TZ='Europe/Berlin' --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest
latest: Pulling from dielee/volvo2mqtt
Digest: sha256:15806260614d8f899fab82afd0ed3e2759e77daea771d5192bbca6f94d43ea62
Status: Image is up to date for ghcr.io/dielee/volvo2mqtt:latest
Starting volvo2mqtt version v1.0.5
Vin: ['VIN2'] found!
Starting GET call against https://api.volvocars.com/connected-vehicle/v1/vehicles/{0}
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Mqtt update done. Next run in 30 seconds.
```
