### ISSUE TITLE
UTC time is shown as local time

### ISSUE THREAD

**Issue by westlund** [Dielee/volvo2mqtt#31]
**Describe the bug**
The estimated charging finish time shown is UTC and not local time.

**To Reproduce**
1. Start charging the car.
2. Examine the sensor.estimated_charging_finish_time entity
3. It will show the time in UTC rather than the local time.

**Expected behavior**
The time should be shown as local time.

**Screenshots**
N/A

**Version info**
hassio 2023.6.3

**Additional context**
Additional info can be supplied on request as well as testing if nessecary.

**Comment by Dielee** [comment]
Ahhh, will have a look later!

**Comment by Dielee** [comment]
Is your "Last Data Update" timestamp right ?

**Comment by westlund** [comment]
> Is your "Last Data Update" timestamp right ?

No it is Aldo in UTC, ie offset with 2 hours from CET in my case.

**Comment by westlund** [comment]
You probably want to look into [HA UTC & Time zone awareness](https://www.home-assistant.io/blog/2015/05/09/utc-time-zone-awareness/) as you probably get the correct time in UTC from the VCC API but need to adapt it

**Comment by Dielee** [comment]
Please test v1.5.1!

**Comment by westlund** [comment]
Works fine now!
