### ISSUE TITLE
Need a property for average speed - off by a power of 10

### ISSUE THREAD

**Issue by kristofferbj** [Dielee/volvo2mqtt#33]
**Describe the bug**
My average speed is 283 km/h. That's really fast ... :) In reality it's 28.3 km/h.

**To Reproduce**
The API is delivering 283.

**Expected behavior**
Should be 28.3.

**Screenshots**

**Version info**
1.5.4.

**Additional context**
We need a property where you can specify divider.

**Comment by Dielee** [comment]
This API is really garbage some times....

**Comment by kristofferbj** [comment]
Yes.

**Comment by Dielee** [comment]
Here you go. Please test v1.5.5

**Comment by kristofferbj** [comment]
Works fine.
