### ISSUE TITLE
Extended vehicle API resources

### ISSUE THREAD

**Issue by d1nc174** [Dielee/volvo2mqtt#37]
Can you please add the Extended vehicle API resources for the non electric mild hybrids with AAOS, with the distance to empty and other resources. Thnx.

**Comment by Dielee** [comment]
Please describe precisely which resources you need.  [Link](https://developer.volvocars.com/apis/extended-vehicle/v1/resources/)

**Comment by Dielee** [comment]
Okay! Would you please send me your response from `https://api.volvocars.com/extended-vehicle/v1/vehicles/{vin}/resources`

**Comment by d1nc174** [comment]
Sorry for the question cause I'm new to this.. 
Do I need to publish my application so I can obtain the client_id and a client_secret, so i can then obtain the access-token for the query to get my resources response? Or there is another way without me publishing the app which is not needed for obtaining the vcc-api-key?

**Comment by d1nc174** [comment]
I figured it out..
This is the response:

  "resources" : [ {
    "version" : "1.0",
    "name" : "averageFuelConsumption",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/averageFuelConsumption"
  }, {
    "version" : "1.0",
    "name" : "averageSpeed",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/averageSpeed"
  }, {
    "version" : "1.0",
    "name" : "brakeFluid",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/brakeFluid"
  }, {
    "version" : "1.0",
    "name" : "carLocked",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/carLocked"
  }, {
    "version" : "1.0",
    "name" : "distanceToEmpty",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/distanceToEmpty"
  }, {
    "version" : "1.0",
    "name" : "engineCoolantLevel",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/engineCoolantLevel"
  }, {
    "version" : "1.0",
    "name" : "engineHoursToService",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/engineHoursToService"
  }, {
    "version" : "1.0",
    "name" : "frontLeftDoorOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/frontLeftDoorOpen"
  }, {
    "version" : "1.0",
    "name" : "frontLeftTyrePressure",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/frontLeftTyrePressure"
  }, {
    "version" : "1.0",
    "name" : "frontLeftWindowOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/frontLeftWindowOpen"
  }, {
    "version" : "1.0",
    "name" : "frontRightDoorOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/frontRightDoorOpen"
  }, {
    "version" : "1.0",
    "name" : "frontRightTyrePressure",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/frontRightTyrePressure"
  }, {
    "version" : "1.0",
    "name" : "frontRightWindowOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/frontRightWindowOpen"
  }, {
    "version" : "1.0",
    "name" : "fuelAmount",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/fuelAmount"
  }, {
    "version" : "1.0",
    "name" : "hoodOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/hoodOpen"
  }, {
    "version" : "1.0",
    "name" : "kmToService",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/kmToService"
  }, {
    "version" : "1.0",
    "name" : "odometer",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/odometer"
  }, {
    "version" : "1.0",
    "name" : "oilLevel",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/oilLevel"
  }, {
    "version" : "1.0",
    "name" : "rearLeftDoorOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/rearLeftDoorOpen"
  }, {
    "version" : "1.0",
    "name" : "rearLeftTyrePressure",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/rearLeftTyrePressure"
  }, {
    "version" : "1.0",
    "name" : "rearLeftWindowOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/rearLeftWindowOpen"
  }, {
    "version" : "1.0",
    "name" : "rearRightDoorOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/rearRightDoorOpen"
  }, {
    "version" : "1.0",
    "name" : "rearRightTyrePressure",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/rearRightTyrePressure"
  }, {
    "version" : "1.0",
    "name" : "rearRightWindowOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/rearRightWindowOpen"
  }, {
    "version" : "1.0",
    "name" : "serviceWarningStatus",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/serviceWarningStatus"
  }, {
    "version" : "1.0",
    "name" : "serviceWarningTrigger",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/serviceWarningTrigger"
  }, {
    "version" : "1.0",
    "name" : "sunRoofOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/sunRoofOpen"
  }, {
    "version" : "1.0",
    "name" : "tailGateOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/tailGateOpen"
  }, {
    "version" : "1.0",
    "name" : "tankLidOpen",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/tankLidOpen"
  }, {
    "version" : "1.0",
    "name" : "tripMeter1",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/tripMeter1"
  }, {
    "version" : "1.0",
    "name" : "tripMeter2",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/tripMeter2"
  }, {
    "version" : "1.0",
    "name" : "washerFluidLevel",
    "href" : "https://api.volvocars.com/extended-vehicle/v1/vehicles/YV1XZK7V0P2982574/resources/washerFluidLevel"
  } ]

**Comment by Dielee** [comment]
> Sorry for the question cause I'm new to this.. Do I need to publish my application so I can obtain the client_id and a client_secret, so i can then obtain the access-token for the query to get my resources response? Or there is another way without me publishing the app which is not needed for obtaining the vcc-api-key?

No, you only need your vcc-api-key. After you created the volvo app, your vcc-api-key exists.

**Comment by d1nc174** [comment]
Thhnx for the reply.. I figured it out. I got the test access token and got the resources listed (see above).

When I try to get the resources needed from the API I see that Average fuel consumption, Average speed and External temperature are not available cause the response is not valid yet..

but distanceToEmpty, Washer fluid level and Carlocked are valid!

**Comment by Dielee** [comment]
Are you able to lock/unlock the car at this time ?
And are some of the connected-car api sensors working ?

**Comment by d1nc174** [comment]
Yes I'm able to lock/unlock the car. Haven't tried the AC switch yet.

Other sensors of the connected-car api that are working:
- door sensors
- window sensors
- odometer (x10)
- tyre sensors
- fuel level

**Comment by d1nc174** [comment]
I'm mostly happy with the location api working now cause prior to that i had to use the airtag to get the location.. and to get the airtag into homeassistant there is an app for the MacOS but it needs to be open all the time.. so it was a hassle to use.

**Comment by Dielee** [comment]
Nice, If those work, I will add only `distanceToEmpty` and `washerFluidLevel` as car lock status is available via the connected car api. Okay ?

**Comment by Dielee** [comment]
Done with v1.6.1!

**Comment by d1nc174** [comment]
Hi again,
I installed the v1.6.1. but it doesnt work..

The log says:
Failed, Average Speed is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/distanceToEmpty
Failed, Distance to Empty is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/washerFluidLevel
Failed, Washer Fluid Level is unfortunately not supported by your vehicle.

But when When I try to get these resources directly from the API I can get them.
What may be the problem?

**Comment by Dielee** [comment]
Please enable debug and send me the log

**Comment by d1nc174** [comment]
Where can I find the log? I have it installed as addon on HAOS .

**Comment by d1nc174** [comment]
This is the log file from HA Logs..

[982ee2c4_volvo2mqtt_2023-06-29T17-25-30.555Z.log](https://github.com/Dielee/volvo2mqtt/files/11908739/982ee2c4_volvo2mqtt_2023-06-29T17-25-30.555Z.log)

**Comment by Dielee** [comment]
Nothing. The log is truncated by the webinterface. Until now, I do not have a solution for this. 
BUT, the two new sensors are the last. So the startup log should contain the necessary data for me.

**Comment by Dielee** [comment]
And, pls show me your output from

`https://api.volvocars.com/extended-vehicle/v1/vehicles/{vin}/resources/distanceToEmpty`

**Comment by d1nc174** [comment]
This is from the startup log..

Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/distanceToEmpty
Failed, Distance to Empty is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/washerFluidLevel
Failed, Washer Fluid Level is unfortunately not supported by your vehicle.

The output from:
curl -X GET 'https://api.volvocars.com/extended-vehicle/v1/vehicles/{vin}/resources/distanceToEmpty' \
-H 'accept: application/json' \
-H 'authorization: Bearer <your-access-token>' \
-H 'vcc-api-key: <your-vcc-api-key>'

is

{
  "distanceToEmpty" : {
    "value" : "390",
    "unit" : "kilometers",
    "timestamp" : 1688057559572
  }
}%

**Comment by Dielee** [comment]
Which return code does the API deliver ? 200 ? 201 ?

**Comment by Dielee** [comment]
Would you please try this:

`curl -X GET 'https://api.volvocars.com/extended-vehicle/v1/vehicles/{vin}/resources/distanceToEmpty' -H 'accept: */*' -H 'authorization: Bearer <your-access-token>' -H 'vcc-api-key: <your-vcc-api-key>'`

**Comment by d1nc174** [comment]
it only gives me this response

{
  "distanceToEmpty" : {
    "value" : "390",
    "unit" : "kilometers",
    "timestamp" : 1688057559572
  }
}%

**Comment by d1nc174** [comment]
btw i´m doing it on terminal

**Comment by Dielee** [comment]
I don't know what's wrong here. As my car is not allowed to communicate with the extended API, I can't test anything. 
I will build a version with more logging later today to see what's going on here....

**Comment by d1nc174** [comment]
ok.. thnx

**Comment by d1nc174** [comment]
I managed to get this from your deubug log..

Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/statistics
{
  "status" : 200,
  "operationId" : "7ae013b8-5e72-4e79-9567-c5a3b1754311",
  "data" : {
    "tripMeter1" : {
      "value" : "0",
      "unit" : "kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "tripMeter2" : {
      "value" : "0",
      "unit" : "kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "averageFuelConsumption" : {
      "value" : "0.0",
      "unit" : "liters_per_100_kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "distanceToEmpty" : {
      "value" : "390",
      "unit" : "kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "averageSpeed" : {
      "value" : "1",
      "unit" : "kilometers_per_hour",
      "timestamp" : "2023-06-29T16:52:39Z"
    }
  }
}
Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
{
  "status" : 200,
  "operationId" : "7ae013b8-5e72-4e79-9567-c5a3b1754311",
  "data" : {
    "tripMeter1" : {
      "value" : "0",
      "unit" : "kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "tripMeter2" : {
      "value" : "0",
      "unit" : "kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "averageFuelConsumption" : {
      "value" : "0.0",
      "unit" : "liters_per_100_kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "distanceToEmpty" : {
      "value" : "390",
      "unit" : "kilometers",
      "timestamp" : "2023-06-29T16:52:39Z"
    },
    "averageSpeed" : {
      "value" : "1",
      "unit" : "kilometers_per_hour",
      "timestamp" : "2023-06-29T16:52:39Z"
    }
  }
}
Failed, Average Speed is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/distanceToEmpty
Failed, Distance to Empty is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/washerFluidLevel
Failed, Washer Fluid Level is unfortunately not supported by your vehicle.

As you can see the.. 
https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/statistics
returns also the **distanceToEmpty** value correctly so we can get it from there..

I also see that in my Volvo API  when I select the Connected Vehicle API I have v1 in the request address (not v2 as in yours)
https://api.volvocars.com/connected-vehicle/v1/vehicles/{vin}/statistics'
so I think everything has to do with the version of API (v1 vs v2) which depends of type of vehicle (Recharge or PHEV or Mild Hybrid - MHEV)

**Comment by d1nc174** [comment]
I think I found the problem.. maybe.. ))
In your code you check for the  response 
"status" : 200
from the server to check if something is supported or not.. am I right?
but in  extended-vehicle resources the server doesn't return the
**"status" : 200**
it only returns
{
  "distanceToEmpty": {
    "value": "300",
    "unit": "kilometers",
    "timestamp": 1603174518633
  }
}
so you get the 
**Failed, Distance to Empty is unfortunately not supported by your vehicle**
and maybe you only have to bypass the "status" : 200 check for those resources?

**Comment by Dielee** [comment]
Sure.. Those are http codes. I'm building a new version right now. Please wait a few more minutes.

**Comment by Dielee** [comment]
So, please updat to v1.6.2, enable debug and send me your log from `\\<Your HA IP>\addons\volvo2mqtt\log\volvo2mqtt.log`.

**Comment by d1nc174** [comment]
ok.. done.. here the log..
[volvo2mqtt.log](https://github.com/Dielee/volvo2mqtt/files/11915255/volvo2mqtt.log)

**Comment by d1nc174** [comment]
yes i figured it and deleted them.. my bad.. here the log again if you need it
[volvo2mqtt.log](https://github.com/Dielee/volvo2mqtt/files/11915319/volvo2mqtt.log)

**Comment by Dielee** [comment]
The api returns 
`Jun 30 11:40:33 volvo2mqtt [79] - INFO: Failed, Distance to Empty is unfortunately not supported by your vehicle.

Jun 30 11:40:33 volvo2mqtt [79] - DEBUG: Starting GET call against https://api.volvocars.com/extended-vehicle/v1/vehicles/{0}/resources/washerFluidLevel

Jun 30 11:40:33 volvo2mqtt [79] - DEBUG: https://api.volvocars.com:443 "GET /extended-vehicle/v1/vehicles/XXXXXXXXXXXXXXX/resources/washerFluidLevel HTTP/1.1" 403 None

Jun 30 11:40:33 volvo2mqtt [79] - DEBUG: Response status code: 403

Jun 30 11:40:33 volvo2mqtt [79] - DEBUG: {
  "exveErrorId" : "403",
  "exveErrorMsg" : "Access is denied"
}`

This is the reason why the sensors are not coming up. 

It looks like the token I recive from the api, is not valid for the extended-vehicle api. Maybe there is nothing I can do at this time.

**Comment by d1nc174** [comment]
ok.. but can you please add at least distanceToEmpty from the statistics part of connected-vehicle api
its showing the distanceToEmpty as you can see in the log..

**Comment by Dielee** [comment]
Yes, this is the reason. With the test API token from the volvo developer page, the requests are working. 
I'm planning to move to the "real" oauth2 authentication, but not yet. So at this time, there is nothing I can do for you, except add distanceToEmpty to the connected-vehicle API.

**Comment by d1nc174** [comment]
ok.. thnx again.. you are great!

**Comment by Dielee** [comment]
Please try v1.6.3. And don't forget to disable debug ;)

**Comment by d1nc174** [comment]
ok. i'll try now and let you know.. ))

**Comment by d1nc174** [comment]
Success! Distance to Empty is supported by your vehicle.
You can now finally close this issue! ))

**Comment by Dielee** [comment]
Nice!
