### ISSUE TITLE
2023 XC90 B6 - Missing sensors - USA

### ISSUE THREAD

**Issue by sco0ts** [Dielee/volvo2mqtt#38]
I am missing:
Sensor "Engine Status"
Sensor "Odometer"
Sensor "Fuel Status"
Sensor "Average Fuel Consumption"
Sensor "Average Speed"
and 
Car Device Tracker shows unknown.

Is this expected with an 2023 XC90 B6, a misconfiguration, or a bug?

**Comment by sco0ts** [comment]
Yes, mild hybrid.

I turned on API debug mode in the Volvo2Mqtt config.
When I check the log tab, it looks truncated.  Is there another location that has the full log?

**Comment by Dielee** [comment]
If it's mild hybrid, this may be related to #38. Please check which resources are working for you here: `https://api.volvocars.com/extended-vehicle/v1/vehicles/{vin}/resources`.

If odometer and the other missing sensors are working here, I have to add some more logic to the mild hybrids.

**Comment by sco0ts** [comment]
I am real novice in all this.  So I went into developer.volvocars.com using my account and VCC, was able to generate an accessToken for EXTENDED VEHICLE API.  

When I used their sandbox, https://api.volvocars.com/extended-vehicle/v1/vehicles does show my VIN.
When I https://api.volvocars.com/extended-vehicle/v1/vehicles/(xxxxHidingMyVinxxx)/resources, I get response. 

> {
  "resources": []
}

**Comment by Dielee** [comment]
This looks not good. Without resources from the extended API, we can't get any data from the extended API.
Please enable debug and send me the full startup log.

**Comment by sco0ts** [comment]
I turned on API debug mode in the Volvo2Mqtt config.
When I check the log tab, it looks truncated. Is there another location that has the full log?

**Comment by sco0ts** [comment]
This is the log without API debug enabled
> s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting volvo2mqtt version v1.6.0
Vin: ['xxxxxxxxxxxxxx'] found!
Starting GET call against https://api.volvocars.com/energy/v1/vehicles/{0}/recharge-status
Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/battery-charge-level
Success! Battery Charge Level is supported by your vehicle.
Failed, Electric Range is unfortunately not supported by your vehicle.
Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Failed, Charging System Status is unfortunately not supported by your vehicle.
Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/odometer
Failed, Odometer is unfortunately not supported by your vehicle.
Success! Last Data Update is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/windows
Success! Window Front Left is supported by your vehicle.
Success! Window Front Right is supported by your vehicle.
Success! Window Rear Left is supported by your vehicle.
Success! Window Rear Right is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/doors
Success! Door Front Left is supported by your vehicle.
Success! Door Front Right is supported by your vehicle.
Success! Door Rear Left is supported by your vehicle.
Success! Door Rear Right is supported by your vehicle.
Success! Tailgate is supported by your vehicle.
Success! Engine Hood is supported by your vehicle.
Success! Tank Lid is supported by your vehicle.
Success! Sunroof is supported by your vehicle.
Success! Air Conditioning is supported by your vehicle.
Success! Lock state is supported by your vehicle.
Success! Force Update Data is supported by your vehicle.
Starting GET call against https://api.volvocars.com/location/v1/vehicles/{0}/location
API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "8dd6c7df-26e5-4fab-a05a-0b27844ac913",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
Success! Location is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/tyres
Success! Tire Front Left is supported by your vehicle.
Success! Tire Front Right is supported by your vehicle.
Success! Tire Rear Left is supported by your vehicle.
Success! Tire Rear Right is supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Failed, Engine State is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Failed, Fuel Level is unfortunately not supported by your vehicle.
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/statistics
Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Failed, Average Speed is unfortunately not supported by your vehicle.
Sending mqtt update...
Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/battery-charge-level
Starting GET call against https://api.volvocars.com/location/v1/vehicles/{0}/location
API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "ea5478a7-12d8-465c-92a9-119623abe536",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment]
Okay, better than nothing. With debug enabled the log is truncated? 

I think there is nothing I can do for you unfortunately. As some sensors work, some do not. There are no resources we can add from the extended API.
You should contact Volvo and ask for some help I think.

**Comment by Dielee** [comment]
Location API seems to be not supported for your car...


```
This API is available for the following cars:
XC40 fully electric, model years between 2015 and 2021.
C40 fully electric, model year 2022.
XC60, S90, V90, V90CC and XC40, model year 2022.
```

[Source](https://developer.volvocars.com/apis/location/v1/overview/)

**Comment by Dielee** [comment]
> I turned on API debug mode in the Volvo2Mqtt config.
> When I check the log tab, it looks truncated. Is there another location that has the full log?

This is on my to-do list for the next days.

**Comment by sco0ts** [comment]
Sorry .  attached above. thank you!

**Comment by Dielee** [comment]
> Thank you for making the log available at '\\addons\volvo2mqtt\log'
> 
> My log as follows:
> 
> EDIT: Shorten thread

It looks like the api simply does not deliver data.
Many api responses are just empty. I can't do anything for you, as the extend-api does not work at this time with volvo2mqtt.

**Comment by sco0ts** [comment]
understood. thank you for taking the time to investigate. and thank you for creating and maintaining the add on

**Comment by Dielee** [comment]
I'm using HA for so many years. It's time to give something back to the community. 
If you need any advice, open a new issue!

**Comment by Dielee** [comment]
I'm using HA for so many years. It's time to give something back to the community. 
If you need any advice, open a new issue!

**Comment by sco0ts** [comment]
As of v1.7.5 my 2023 XC90 Mild Hybrid B6 in the US now show a ton more sensors.  
This includes all sensors I previously said were not working with the exception of Location (not important to me).

**Comment by Dielee** [comment]
Updated to 2.10?

**Comment by sco0ts** [comment]
Updated to Volvo2Mqtt version: 1.7.5
