### ISSUE TITLE
ODO shows just first 4 digits

### ISSUE THREAD

**Issue by duniol** [Dielee/volvo2mqtt#42]
Hi @Dielee , thanks for this add-on!
Everything works fine on my '22 XC60 except for the ODO value - it shows only the first 4 digits (e.g. the distance is 12345 and 1234 is presented). I tried to find any config issues, no luck.

Cheers

**Comment by Dielee** [comment]
This is an API restriction I guess. To be safe, please enable debug and send me the log!

**Comment by duniol** [comment]
How to get the full log of the addon? It shows just the last page in the viewer and the odometer is not there.

**Comment by Dielee** [comment]
As you don't fillet the issue template. I don't know your platform... So, are you using the addon or a single docker container ?

**Comment by duniol** [comment]
Addon on raspberry pi

**Comment by Dielee** [comment]
Starting v1.6.2 the full addon log is located here `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

**Comment by MK040NL** [comment]
I also experience the same issue. I also miss the last digit of the odometer. I can use the multiplier, but this results in the wrong number as it is rounding down to 10-fold.

**Comment by Dielee** [comment]
Same as above. Please enable debug an send some logs. This is pretty sure an API limitation.

**Comment by duniol** [comment]
I checked the API log on 1.65 and the value was trimmed. Now I have installed 1.72 and the addon is not working at all. When I want to start it is says: "Go to config. not a valid value." . I haven't changed anything there, but if I try it can't be saved.
It says:
`The addon config can't be saverd, not a valid value`

**Comment by Dielee** [comment]
Please take a look at the v1.7.0 release. 
`NOTE: The mqtt broker port is now a string. Just quote your port like this port: "1883"`

**Comment by duniol** [comment]
I works, thank you. Now I found the changelog here. It would be cool if it was available from the addon card (it's empty at my setup)

**Comment by MK040NL** [comment]
> Same as above. Please enable debug an send some logs. This is pretty sure an API limitation.

It shows indeed as a 4 digit number. I would not expect the odometer to get trunked. But it looks it in limited. 

Jul 03 22:11:37 volvo2mqtt [80] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/odometer
Jul 03 22:11:37 volvo2mqtt [80] - DEBUG: Resetting dropped connection: api.volvocars.com
Jul 03 22:11:38 volvo2mqtt [80] - DEBUG: https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/<VIN>/odometer HTTP/1.1" 200 217
Jul 03 22:11:38 volvo2mqtt [80] - DEBUG: Response status code: 200
Jul 03 22:11:38 volvo2mqtt [80] - DEBUG: {
  "status" : 200,
  "operationId" : "<nice ID number>",
  "data" : {
    "odometer" : {
      "value" : "1547",
      "unit" : "kilometers",
      "timestamp" : "2023-07-03T16:07:23Z"
    }
  }
}

**Comment by Dielee** [comment]
Jep, that's my problem too. Hopefully they will fix this issue. For now, there is nothing I can do, sorry!
