### ISSUE TITLE
Lock icon is static - can it open/close with state?

### ISSUE THREAD

**Issue by wixoff** [Dielee/volvo2mqtt#43]
Unlike other MQTT locks I have (via zigbee2mqtt), the Home Assistant icon for the Volvo lock state is static - it doesn't open or close according to the state.

Is this something that can be updated in this project, or is it an issue with some other part of the ecosystem?

Ideally, the icon would be `mdi:lock` when locked, and `mdi:lock-open` when unlocked.

**Comment by Dielee** [comment]
Yes dynamic icons are part of my to-do. Maybe I'll find some time today :)

**Comment by Dielee** [comment]
Done with version v1.6.4. Please test!

**Comment by wixoff** [comment]
I've only tried it with the lock state, but it looks great!  Thanks!
