### ISSUE TITLE
Distance to Empty : Unable to adjust value

### ISSUE THREAD

**Issue by jesuisla91** [Dielee/volvo2mqtt#44]
The "Distance to Empty" entity does not display the correct value and cannot be adjusted using the "odometerMultiplier" parameter.

For example, the real value should be 40km, but "Distance to Empty" shows me 40000km.
I therefore need to set "odometerMultiplier" to 0.001 to obtain 40km (40000 x 0.001 = 40).

Problem : It seems impossible to set a comma value in VolvoToMqtt configuration.
odometerMultiplier: 0**.**001  or odometerMultiplier: 0**,**001

Thank you

**Comment by Dielee** [comment]
As said before, please enable debug and provide some logs!

**Comment by Dielee** [comment]
Volvo optimized their API. Would you please check if this issue persists @jesuisla91 ?
