### ISSUE TITLE
Add-on stops itself after 30 seconds.

### ISSUE THREAD

**Issue by walts22** [Dielee/volvo2mqtt#46]
Hi, 
Thank you for all your development so far on this!

I can't seem to get mine set up, I assume I have done something wrong on my end. The service initial finds my VIN number and says it can read a couple of things, but then stops after a short amount of time.

Any help you be greatly appreciated!

**Comment by Dielee** [comment]
The addon can't connect to your mqtt broker. Please share your mqtt config!

**Comment by walts22** [comment]
> 
Thanks for your help! Below is my config:

<img width="141" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/87230803/2d5a5d58-ec38-4037-803e-4ecfbd6b5e93">

<img width="792" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/87230803/2d813867-77ce-4166-9a94-4c50b2814c85">

**Comment by Dielee** [comment]
`broker: mosquitto` have to contain your broker IP, as said in the description.
So eg. `broker: 192.168.0.5`

**Comment by walts22** [comment]
Sorry for my ignorance, thanks for that!
I have tried with a few broker settings now, including IP address, and adding password details and still no luck.

Do you think it's potentially how I set up my Volvo development account? With this line below?
Jul 03 14:55:39 volvo2mqtt [79] - ERROR: API Call failed. Status Code: 404. Error:

Or still looks Mosquitto broker based?

**Comment by Dielee** [comment]
This `Jul 03 14:55:39 volvo2mqtt [79] - ERROR: API Call failed. Status Code: 404. Error:` has nothing to do with your broker. 
I guess this message came from here, right ? 

```
Jul 03 08:55:23 volvo2mqtt [79] - ERROR: API Call failed. Status Code: 404. Error: {
"status" : 404,
"operationId" : "8151c816-772e-4037-b70f-a6462b5705d5",
"error" : {
"message" : "NOT_FOUND",
"description" : "VIN not found"
}
}
Jul 03 08:55:23 volvo2mqtt [79] - INFO: Failed, Location is unfortunately not supported by your vehicle.
```

If yes, the location API is simply not supported by your car.

**Comment by Dielee** [comment]
Still no luck with what ? Please enter the right broker IP, port, username and password, and send me the logs! 
It's like flying blind for me, if you provide no logs :P

**Comment by walts22** [comment]
Sorry, I'm just a bit fresh with HA, and Mosquito brokers in general. So please bare with me. :D

I have added the IP address to no avail. Which I assumed is the same as my Raspberri Pi HA OS IP address? (probably assumed incorrectly. 

MQTT logs:
<img width="459" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/87230803/97ee804a-0347-4908-8f85-7986cf18f289">

I am just using the stock standard MQTT mosquito broker in an untouched configuration, in which I have a Ring MQTT service functioning correctly through it. 

Bit more info:
Car is a 2013 XC40 Recharge Twin 
Location: Australia

**Comment by Dielee** [comment]
Good hint! Wait a few minutes. I'm working on the MQTT autodiscovery if the mqtt broker runs as HA Addon.

**Comment by walts22** [comment]
Brilliant! Thank you so much for your work.

**Comment by Dielee** [comment]
Ready! Please try v1.7.0. 
After the update, update your mqtt settings to:

![image](https://i.imgur.com/GBamhFn.png) </b>

**Comment by walts22** [comment]
Hi Dielee,
Updated to v1.7.1 and unfortunately getting a similar error.

INFO:root:Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
INFO:root:Failed, Odometer is unfortunately not supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Failed, Odometer is unfortunately not supported by your vehicle.
INFO:root:Success! Last Data Update is supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
INFO:root:Success! Window Front Left is supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Success! Window Front Left is supported by your vehicle.
INFO:root:Success! Window Front Right is supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Success! Window Front Right is supported by your vehicle.
INFO:root:Success! Window Rear Left is supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Success! Window Rear Left is supported by your vehicle.
INFO:root:Success! Window Rear Right is supported by your vehicle.
Jul 03 17:15:16 volvo2mqtt [106] - INFO: Success! Window Rear Right is supported by your vehicle.
INFO:root:Success! Door Front Left is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Door Front Left is supported by your vehicle.
INFO:root:Success! Door Front Right is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Door Front Right is supported by your vehicle.
INFO:root:Success! Door Rear Left is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Door Rear Left is supported by your vehicle.
INFO:root:Success! Door Rear Right is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Door Rear Right is supported by your vehicle.
INFO:root:Success! Tailgate is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Tailgate is supported by your vehicle.
INFO:root:Success! Engine Hood is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Engine Hood is supported by your vehicle.
INFO:root:Success! Tank Lid is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Tank Lid is supported by your vehicle.
INFO:root:Success! Sunroof is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Sunroof is supported by your vehicle.
INFO:root:Success! Air Conditioning is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
INFO:root:Success! Lock state is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Lock state is supported by your vehicle.
INFO:root:Success! Force Update Data is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
ERROR:root:API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "3ae067ec-ece9-47c0-99bc-044470c8ebdc",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
Jul 03 17:15:17 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "3ae067ec-ece9-47c0-99bc-044470c8ebdc",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
INFO:root:Failed, Location is unfortunately not supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Failed, Location is unfortunately not supported by your vehicle.
INFO:root:Success! Tire Front Left is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Tire Front Left is supported by your vehicle.
INFO:root:Success! Tire Front Right is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Tire Front Right is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Tire Rear Left is supported by your vehicle.
INFO:root:Success! Tire Rear Left is supported by your vehicle.
INFO:root:Success! Tire Rear Right is supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Success! Tire Rear Right is supported by your vehicle.
INFO:root:Failed, Engine State is unfortunately not supported by your vehicle.
Jul 03 17:15:17 volvo2mqtt [106] - INFO: Failed, Engine State is unfortunately not supported by your vehicle.
INFO:root:Success! Engine State is supported by your vehicle.
Jul 03 17:15:18 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
INFO:root:Failed, Fuel Level is unfortunately not supported by your vehicle.
Jul 03 17:15:18 volvo2mqtt [106] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
Jul 03 17:15:18 volvo2mqtt [106] - INFO: Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
INFO:root:Failed, Average Fuel Consumption is unfortunately not supported by your vehicle.
Jul 03 17:15:18 volvo2mqtt [106] - INFO: Failed, Distance to Empty is unfortunately not supported by your vehicle.
INFO:root:Failed, Distance to Empty is unfortunately not supported by your vehicle.
Jul 03 17:15:18 volvo2mqtt [106] - INFO: Failed, Average Speed is unfortunately not supported by your vehicle.
INFO:root:Failed, Average Speed is unfortunately not supported by your vehicle.
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 15, in <module>
    update_loop()
  File "/volvoAAOS2mqtt/mqtt.py", line 114, in update_loop
    create_ha_devices()
  File "/volvoAAOS2mqtt/mqtt.py", line 208, in create_ha_devices
    device = volvo.get_vehicle_details(vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 137, in get_vehicle_details
    raise Exception("Getting vehicle details failed. Status Code: " + str(response.status_code) +
Exception: Getting vehicle details failed. Status Code: 500. Error: {
  "status" : 500,
  "operationId" : "875513b3-f09b-45bb-b2ca-e565612732ad",
  "error" : {
    "message" : "INTERNAL_SERVER_ERROR",
    "description" : "Internal Server Error"
  }
}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
No, this is an other error.  The connection to your MQTT Broker is now working.
The addon can't get your vehicle details.
Please enable debug and share the log from `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

**Comment by Dielee** [comment]
Do you have filled your VIN manually ? 
There is a fix for your error already. But it works only if you leave your VIN empty in the configuration!

**Comment by Dielee** [comment]
If VIN is removed, the addon should work ;)

**Comment by walts22** [comment]
My apologies with this. You must have thought your instructions were idiot-proof. 
Not for this idiot :D

I tried to find the log file, but I couldn't navigate to that file. (I have enabled debugging)

Also the car is driving currently. Does this affect it too?


New logs from the add-on itself:


      "name" : "rearLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    },
    "rearRightTyrePressure" : {
      "name" : "rearRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    },
Jul 03 17:32:59 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "85eb133f-52c1-4a9f-861b-fda735f142ab",
  "data" : {
    "rearLeftTyrePressure" : {
      "name" : "rearLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    },
    "rearRightTyrePressure" : {
      "name" : "rearRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    },
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    },
    "frontLeftTyrePressure" : {
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    },
    "frontLeftTyrePressure" : {
      "timestamp" : "2023-07-03T08:01:03Z"
    }
  }
}
INFO:root:Success! Tire Rear Right is supported by your vehicle.
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-03T08:01:03Z"
    }
  }
}
Jul 03 17:32:59 volvo2mqtt [107] - INFO: Success! Tire Rear Right is supported by your vehicle.
Jul 03 17:32:59 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
DEBUG:root:Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Jul 03 17:32:59 volvo2mqtt [107] - DEBUG: https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/LYVXZEDA6PL009989/engine-status HTTP/1.1" 200 225
DEBUG:urllib3.connectionpool:https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/LYVXZEDA6PL009989/engine-status HTTP/1.1" 200 225
Jul 03 17:32:59 volvo2mqtt [107] - DEBUG: Response status code: 200
DEBUG:root:Response status code: 200
DEBUG:root:{
  "status" : 200,
  "operationId" : "2e990151-bef2-4460-a32c-53de73ea2d7c",
  "data" : {
    "engineRunning" : {
      "name" : "engineRunning",
      "value" : "true",
Jul 03 17:32:59 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "2e990151-bef2-4460-a32c-53de73ea2d7c",
      "timestamp" : "1970-01-01T00:00:00Z"
    }
  }
}
  "data" : {
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 13, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 52, in authorize
    check_supported_endpoints()
    "engineRunning" : {
      "name" : "engineRunning",
      "value" : "true",
      "timestamp" : "1970-01-01T00:00:00Z"
  File "/volvoAAOS2mqtt/volvo.py", line 159, in check_supported_endpoints
    }
  }
}
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 250, in api_call
    return parse_api_data(data, sensor_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 369, in parse_api_data
    return engine_states[data["engineRunning"]["value"]] if util.keys_exists(data, "engineRunning") else None
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'true'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Dielee** [comment]
This error is related to #47. Please test v1.7.2!

**Comment by walts22** [comment]
Tested but similar thing happening.

**Comment by Dielee** [comment]
Logs! :D

**Comment by Dielee** [comment]
Please show me your locale setting! This seems to be wrong...

**Comment by walts22** [comment]
Knowing me I probably got this wrong too! 
![Screenshot 2023-07-03 at 6 18 56 pm](https://github.com/Dielee/volvo2mqtt/assets/87230803/91db89d7-5b5d-4491-bb88-b17e41bb383c)

**Comment by Dielee** [comment]
Man, please read the readme! 
As said there, pick your matching code from the "Locale name" column. In your case it should be `en_AU`.
This [link](https://www.ibm.com/docs/en/radfws/9.7?topic=overview-locales-code-pages-supported) can be found there.

**Comment by Dielee** [comment]
Alright! Does it work now ?

**Comment by Travikxs** [comment]
Hi!

Same Issue here, the addon stopped in the morrning and I can't save the new config or the old config

Old config:
![image](https://github.com/Dielee/volvo2mqtt/assets/129509712/0d762ce9-006a-4132-b3f5-4504c711803a)

New config:
![image](https://github.com/Dielee/volvo2mqtt/assets/129509712/69f0830d-74fe-47e2-aa69-8b8ee563ffa7)

I reseted the rapsberry 2 times and the issue is there.

Thank you!!

**Comment by Dielee** [comment]
> Hi!
> 
> Same Issue here, the addon stopped in the morrning and I can't save the new config or the old config
> 
> 
> New config: 
> 
> I reseted the rapsberry 2 times and the issue is there.
> 
> Thank you!!

Please don't hijack this issue for your needs. 
Your Volvo config is incomplete. Here is a basic example:
```
username: null
password: null
vin: ""
vccapikey: null
odometerMultiplier: 1
averageSpeedDivider: 1
averageFuelConsumptionMultiplier: 1

```
Please uninstall the addon and reinstall.

**Comment by walts22** [comment]
> Alright! Does it work now ?

Yes!  Perfect. 
Gets a tonne of info from the Volvo api. Thanks heaps!
