### ISSUE TITLE
Cannot start add-on, nor save config since 1.7

### ISSUE THREAD

**Issue by kernalkue** [Dielee/volvo2mqtt#48]
**Describe the bug**
Cannot start add-on, nor save config. Getting the error "not a valid value"

**To Reproduce**
Using config that worked with v1.6.4
Updated to 1.7.0/1.7.1
Cannot start add-on

When I try to save the config:
`Failed to save add-on configuration, not a valid value. Got {'updateInterval': 300, 'babelLocale': 'en_GB', 'TZ': 'Europe/London', 'debug': False, 'mqtt': {'broker': '192.168.xxx.xxx', 'port': 1883, 'username': 'xxxxx', 'password': 'xxxxx'}, 'volvoData': {'username': 'xxxxx', 'password': 'xxxxx', 'vin': '', 'vccapikey': xxxxx', 'odometerMultiplier': 10, 'averageSpeedDivider': 1, 'averageFuelConsumptionMultiplier': 1}}`

**Comment by Dielee** [comment]
Yep, mqtt port is now a string. There is no other way, sorry!

**Comment by Dielee** [comment]
Added a release note to v1.7.0 ;)

**Comment by sgbossinga** [comment]
> Yep, mqtt port is now a string. There is no other way, sorry!

what do we have to do to resolve this? retype in configuration?

**Comment by Dielee** [comment]
<b>The mqtt broker port is now a string. Just quote your port like this port: "1883"</b>
