### ISSUE TITLE
After the last update 1.7.2 nog working 

### ISSUE THREAD

**Issue by sschouten** [Dielee/volvo2mqtt#50]
Hello,

After the last update the plug-in is not startend anymore.

![IMG_7619](https://github.com/Dielee/volvo2mqtt/assets/30841665/446746c2-bc36-4723-b8d5-3ce6447872f4)

I have not changed Any thing in the config

**Comment by Dielee** [comment]
Please take a look at the v1.7.0 release. 
`NOTE: The mqtt broker port is now a string. Just quote your port like this port: "1883"`
