### ISSUE TITLE
Charging system status description

### ISSUE THREAD

**Issue by RobPijpers** [Dielee/volvo2mqtt#52]
The Charging system status is showing the correct state when my C40 is charging (**Charging**) or charging reached the charge limit of 90% (**Idle**). After disconnecting the charging cable the state changes to **Unspecified**. Can this state description be changed in to for example **Disconnected**?

**Comment by Dielee** [comment]
Maybe possible, but this isn't the state from the API. I would hate to bend the status from the API.

Let me know if the "Charging Connection Status" works for you. It shows "Disconnected" if no charger is plugged in.

**Comment by RobPijpers** [comment]
> Maybe possible, but this isn't the state from the API. I would hate to bend the status from the API.
> 
> Let me know if the "Charging Connection Status" works for you. It shows "Disconnected" if no charger is plugged in.

I totally agree with you not to change the state retrieved from the API. I could use a template sensor to set the state based on the "Charging Connection Status" with any value I would like.

In the Readme.md the Volvo C40 is described as PHEV, this model is only available as BEV.

Nevertheless, I'm very happy with this Addon!

**Comment by RobPijpers** [comment]
> Maybe possible, but this isn't the state from the API. I would hate to bend the status from the API.
> 
> Let me know if the "Charging Connection Status" works for you. It shows "Disconnected" if no charger is plugged in.

I totally agree with you not to change the state retrieved from the API. I could use a template sensor to set the state based on the "Charging Connection Status" with any value I would like.

In the Readme.md the Volvo C40 is described as PHEV, this model is only available as BEV.

Neverteless, I'm very happy with this Addon!

**Comment by Dielee** [comment]
> > Maybe possible, but this isn't the state from the API. I would hate to bend the status from the API.
> > Let me know if the "Charging Connection Status" works for you. It shows "Disconnected" if no charger is plugged in.
> 
> I totally agree with you not to change the state retrieved from the API. I could use a template sensor to set the state based on the "Charging Connection Status" with any value I would like.
> 
> In the Readme.md the Volvo C40 is described as PHEV, this model is only available as BEV.
> 
> Nevertheless, I'm very happy with this Addon!

Thanks! 
I will change this.
