### ISSUE TITLE
Volvo2mqtt terminates unexpectedly after ValueError: invalid literal for int() with base 10: '55.4'

### ISSUE THREAD

**Issue by westlund** [Dielee/volvo2mqtt#53]
**Describe the bug**
Volvo2mqtt terminates with the following error registered in the log.

Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 13, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 52, in authorize
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 159, in check_supported_endpoints
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 250, in api_call
    return parse_api_data(data, sensor_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 372, in parse_api_data
    fuel_amount = int(data["fuelAmount"]["value"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '55.4'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**To Reproduce**:<br>
Attempt to restart generates the same error.

**Expected behavior**:<br>
The service should bee able to handle unexpected API responses and if not, restart according to the user watchdog preferences.

**Screenshots**:
N/A

**Version info**:<br>
1.7.2 in HA Addon in hassio 2023.6.3

**Logs**:<br>
    },
    "rearRightTyrePressure" : {
      "name" : "rearRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    },
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    },
    "frontLeftTyrePressure" : {
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    }
  }
}
Jul 05 18:19:42 volvo2mqtt [107] - INFO: Success! Tire Rear Left is supported by your vehicle.
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: Response status code: 200
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "6078c11b-130e-43e9-9fb3-e48f0f111df6",
  "data" : {
    "rearLeftTyrePressure" : {
      "name" : "rearLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    },
    "rearRightTyrePressure" : {
      "name" : "rearRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    },
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    },
    "frontLeftTyrePressure" : {
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-05T15:03:30Z"
    }
  }
}
Jul 05 18:19:42 volvo2mqtt [107] - INFO: Success! Tire Rear Right is supported by your vehicle.
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/*/engine-status HTTP/1.1" 200 226
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: Response status code: 200
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "25b3c403-5eb8-4d09-bf15-d756f5f01596",
  "data" : {
    "engineRunning" : {
      "name" : "engineRunning",
      "value" : "false",
      "timestamp" : "1970-01-01T00:00:00Z"
    }
  }
}
Jul 05 18:19:42 volvo2mqtt [107] - INFO: Success! Engine State is supported by your vehicle.
Jul 05 18:19:42 volvo2mqtt [107] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/fuel
Jul 05 18:19:43 volvo2mqtt [107] - DEBUG: https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/*/fuel HTTP/1.1" 200 244
Jul 05 18:19:43 volvo2mqtt [107] - DEBUG: Response status code: 200
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/main.py", line 13, in <module>
Jul 05 18:19:43 volvo2mqtt [107] - DEBUG: {
  "status" : 200,
  "operationId" : "809b848e-468c-4610-a045-89d05a0605ee",
  "data" : {
    "fuelAmount" : {
      "name" : "fuelAmount",
      "value" : "55.4",
      "unit" : "liters",
      "timestamp" : "2023-07-05T15:03:30Z"
    }
  }
}
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 52, in authorize
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 159, in check_supported_endpoints
    state = api_call(entity["url"], "GET", vin, entity["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 250, in api_call
    return parse_api_data(data, sensor_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volvoAAOS2mqtt/volvo.py", line 372, in parse_api_data
    fuel_amount = int(data["fuelAmount"]["value"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '55.4'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by d1nc174** [comment]
I got thr same error.. think maybe it´s the value of fuel ammonut that is now getting a decimal place?

**Comment by TrekBonanza** [comment]
Same for me, worked before and after a restart today I get the same error.

**Comment by Dielee** [comment]
v1.7.3 has been released. Please test, as I can't...

**Comment by westlund** [comment]
I can confirm that 1.7.3 works. Many thanks!

**Comment by TrekBonanza** [comment]
Works again for me after 1.7.3. Good job !
