### ISSUE TITLE
Volvo2mqtt terminates unexpectedly

### ISSUE THREAD

**Issue by Renko72** [Dielee/volvo2mqtt#54]
**Describe the bug**
Volvo2mqtt terminates with the following error registered in the log.
![image](https://github.com/Dielee/volvo2mqtt/assets/82279106/34078b65-f5c2-4334-bbe8-df058eb6937f)

**To Reproduce**:<br>
new start of the server gets actual every time the same error 
Login and API Key is still working 
You wrote i should open a bug 
it seems to be the same issue like 
https://github.com/home-assistant/core/issues/61785

**Expected behavior**:<br>

**Version info**:<br>
HA 2023.6.3 in a docker container 
volvo2mqtt 1.7.2 in a docker container
MQTT (Mosquito 2.0.15) in a docker container
CAR = VOLVO XC 60 PHEV 2022 early

**Logs**:<br>

**Comment by Dielee** [comment]
Same error as #53 :)

**Comment by Dielee** [comment]
Thanks for the coffee!
