### ISSUE TITLE
Charge scheduling

### ISSUE THREAD

**Issue by rubenv** [Dielee/volvo2mqtt#56]
The recent [2.10 update](https://www.volvocars.com/uk/support/car/v60-recharge-plug-in-hybrid/22w46/software-release-notes) has added charge scheduling, which despite what the release notes say, also seem to work on a 2023 V60 T8 Recharge.

Is there a way we can integrate this? Automating when it can charge is obviously where we want to be.

If you can give me some pointers on where to look, I'll happily help figure this out / help build it (though the Home Assistant internals are unknown territory for me).

PS: Thanks for this brilliant project!

**Comment by Dielee** [comment]
This may be possible if somebody is able to reverse engineer the Volvo App, as there has been no official endpoint for this until now.
I tried it a few times, but without luck..

**Comment by rubenv** [comment]
If I find some free time I'll see if I can mitmproxy it :-)

**Comment by Dielee** [comment]
They are using certpinning. I managed to remove it, but still no luck. But yes, give it a try!

**Comment by rubenv** [comment]
Arrrh that's unfortunate. Got any pointers on how to do that?

**Comment by Dielee** [comment]
Yes. Take a look at frida and Http toolkit. You definitely need a rooted hardware android device!

**Comment by rubenv** [comment]
Tried giving it a go using https://github.com/mitmproxy/android-unpinner, which looked promising but I couldn't make it work (probably my fault!).

Sadly don't have a rooted device at hand right now.

**Comment by Dielee** [comment]
I don't have time to investigate here, sorry. But I will let this issue open. So anybody feel free to help here!

**Comment by Dielee** [comment]
Any news here ? 
If not, I possibly will add a schedule option to volvo2mqtt. Would this be an option for you ?

**Comment by rubenv** [comment]
No, sorry, didn't have any more time to look into it. Couldn't reverse engineer the endpoints yet.

**Comment by rubenv** [comment]
The `wirelesscar.net` stuff is, IIRC, the old API though, not the one used by newer cars.

**Comment by Dielee** [comment]
Alright, maybe this wouldn't even be the best option to use unsupported endpoints. I will think about my own implementation.

**Comment by rubenv** [comment]
Always happy to test things out!

**Comment by Dielee** [comment]
Ah sorry. Charge scheduleing will not be possible without the endpoints, because we do not have control to start or stop charging. But for climate this will be possible.

**Comment by rubenv** [comment]
My plan was to automate the adjustment of the charge schedule you can configure for the car.

So when you want to charge: disable the schedule (meaning charge now), when charging should stop: set it to charge from 01:00 to 02:00 (and flip it around to the afternoon when it's night).

**Comment by Dielee** [comment]
Jep, without reverse engineering, no way. 
I will close this issue because of that. If you have detailed information about the endpoints, feel free to open a new issue.
