### ISSUE TITLE
No data returned when charging system has error

### ISSUE THREAD

**Issue by colesadam** [Dielee/volvo2mqtt#57]
**Describe the bug**
Fails to start when charging returns error. Noticed since yesterday when cable not connected correctly. After replacing cable restarted container and now ok.

**To Reproduce**:<br>
1. Part connect cable 
2. Restart docker container

**Expected behavior**:<br>
start up and show
**Screenshots**:<br>

**Version info**:<br>
The version you are using and the method you are using (Docker container/HA Addon/Cloned repo)

**Logs**:<br>
Jul 06 08:58:16 volvo2mqtt [1] - INFO: Starting volvo2mqtt version v1.7.3
Jul 06 08:58:17 volvo2mqtt [1] - INFO: Vin: ['XXXXXXXXXXXXXXXXXX'] found!
Jul 06 08:58:17 volvo2mqtt [1] - INFO: Success! Battery Charge Level is supported by your vehicle.
Jul 06 08:58:17 volvo2mqtt [1] - INFO: Success! Electric Range is supported by your vehicle.
Jul 06 08:58:17 volvo2mqtt [1] - INFO: Success! Estimated Charging Time is supported by your vehicle.
Jul 06 08:58:17 volvo2mqtt [1] - INFO: Success! Charging System Status is supported by your vehicle.
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 13, in <module>
    authorize()
  File "/volvoAAOS2mqtt/volvo.py", line 52, in authorize
    check_supported_endpoints()
  File "/volvoAAOS2mqtt/volvo.py", line 159, in check_supported_endpoints
    state = api_call(entity["url"], "GET", vin, entity["id"])
  File "/volvoAAOS2mqtt/volvo.py", line 250, in api_call
    return parse_api_data(data, sensor_id)
  File "/volvoAAOS2mqtt/volvo.py", line 297, in parse_api_data
    return charging_connection_states[data["chargingConnectionStatus"]["value"]] \
KeyError: 'CONNECTION_STATUS_FAULT'

**Comment by Dielee** [comment]
Would you please enable debug and send the logs ?

**Comment by Dielee** [comment]
Done by verison v1.7.4! Are you able to test this change ?

**Comment by colesadam** [comment]
Yep, updated and tested and now shows correct info, thanks!

**Comment by Dielee** [comment]
Nice. Thanks for testing!
