### ISSUE TITLE
The 1.7.3 update is not available as an add on

### ISSUE THREAD

**Issue by kristofferbj** [Dielee/volvo2mqtt#58]
**Describe the bug**
1.7.2 does not work and 1.7.3 is not available as an add on.

**Comment by Dielee** [comment]
Version 1.7.3 is also available as addon.
This can only be a local problem. Try to uninstall and reinstall the addon.
![2023-07-06 10_44_46-Home Assistant](https://github.com/Dielee/volvo2mqtt/assets/45101649/1b1c6666-25c1-4635-8015-9f6c5b7e5948)

**Comment by kristofferbj** [comment]
Apparently I had to update the Supervisor. Now it works.
