### ISSUE TITLE
Access denied due to invalid VCC-API-KEY. Make sure to provide a valid key for an active application.

### ISSUE THREAD

**Issue by HWiese1980** [Dielee/volvo2mqtt#6]
Currently getting this error message upon starting the image. Has the VCC-API-KEY been invalidated?

**Comment by Dielee** [comment]
Please pull the latest image and read the release notes

**Comment by HWiese1980** [comment]
Right, just figured that out myself. So, never mind, sorry. You should mention that in the README.md too. Thanks for your great work!

**Comment by Dielee** [comment]
No problem! Feel free to open a new issue if something isn't working.
Please don't forget to comment or close #2 if the raspberry build is working!

**Comment by HWiese1980** [comment]
Yeah will do. I still have to check on #2.
