### ISSUE TITLE
"Not a valid value"

### ISSUE THREAD

**Issue by mboos** [Dielee/volvo2mqtt#61]
**Describe the bug**
When I try to start the add-on, I get a dialog with "Go to configuration not a valid value"

When I try to save the configuration, I get,
```
Failed to save add-on configuration, not a valid value. Got {'updateInterval': 300, 'babelLocale': 'en_CA', 'TZ': 'America/Toronto', 'debug': False, 'mqtt': {'broker': '********', 'port': ****, 'username': '*****', 'password': '*****'}, 'volvoData': {'username': '******', 'password': '******', 'vin': '******', 'vccapikey': '*******', 'odometerMultiplier': 1, 'averageSpeedDivider': 1, 'averageFuelConsumptionMultiplier': 1}}
```
(private information replaced by *****)

It would be really helpful if there could be useful information on what's wrong with the configuration. Nothing appears in the logs.

**To Reproduce**:<br>
1. Go to add-on info page
2. Click on Start
3. notice dialog
4. Click Edit config
5. Click Save
6. Notice error message

**Expected behavior**:<br>
I expect my previously working config to continue working, or for useful diagnostic messages to be able to guide me to a resolution.

**Screenshots**:<br>

**Version info**:<br>
Volvo2mqtt 1.7.5<br>
Home Assistant 2023.7.1<br>
Supervisor 2023.07.1<br>
Operating System 10.3<br>
Frontend 20230705.1 - latest

**Logs**:<br>
Logs in the UI are empty<br>
<b>If you are using the HA Addon the log location is `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

**Comment by mboos** [comment]
Ah, this appears to be related to https://github.com/Dielee/volvo2mqtt/issues/51 - adding quotes around the port number fixed it. I would argue it's still a bug that there's no useful error message or migration path though.

**Comment by Dielee** [comment]
Jep, I know this is a breaking change. Unfortunately there is no way to edit the error message from the addon. 

Adding a migration path is an option, but this change is still a few days old. So most people are using a version >= 1.7.0.

And this change is also documented in the addon changelog!

**Comment by mboos** [comment]
I had missed that, as my frontend was inaccessible for a few days of updates while I tried to convince Google my instance was not a phishing site.
