### ISSUE TITLE
Retrieve the exteriorDefaultUrl into an image entity

### ISSUE THREAD

**Issue by westlund** [Dielee/volvo2mqtt#62]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I wish for the exteriorDefaultUrl and optionally the interiorDefaultUrl fetched into the new image entity in HA 2023.7. It would be nice to be able to illustrate my HA car dashboard with an image of my own car as it was configured/built.

**Describe alternatives you've considered**
Manually upload a photo of my car into Home Assistant

**Comment by Dielee** [comment]
I will take a look at this tomorrow!

**Comment by d1nc174** [comment]
Great idea/feature! 👍

**Comment by Dielee** [comment]
Working with version v1.7.6. Please test!

**Comment by westlund** [comment]
I can confirm it is working for my car, a XC60 Rechargee 2023. Thanks!

**Comment by Dielee** [comment]
Let us see what you can make of this image. Would be useful for the community!

**Comment by westlund** [comment]
Here is an example dashboard for my car. The connection status is inoperable due to the current issue with retrieving it.

https://github.com/Dielee/volvo2mqtt/assets/16253150/a5f6f64f-8560-42a6-b1a4-61118f30d21b
