### ISSUE TITLE
Custom MQTT Topic and Duplicate messages

### ISSUE THREAD

**Issue by martin072** [Dielee/volvo2mqtt#64]
Just installed your script, and works like a charm. 
I am not a HA user, but the MQTT feature works for everything I guess.. 
Would it be a lot of work to make the MQTT topic configurable?

Also I noticed the messages are also send in duplicate:

Once in this topic;
homeassistand/< sensor >/<vin_xxxx>

and a second time user:
homeassistand/< sensor >/volvoAAOS2mqtt/<vin_xxxx>

Is this normal behaviour?

Thanks for the nice work!

**Comment by Dielee** [comment]
Which section of the topic do you want to make configurable ? The first `homeassistant` or what ? 

Can you provide some more details to the duplicated messages ? As I can't reproduce this behavior...

**Comment by martin072** [comment]
Yep, if not to much to ask. Would intergrate easier in my own mqtt setup, otherwise not a big deal to leave it as is. 
See attached screenshot (vin number de-identiefied partly)

![Untitled 2](https://github.com/Dielee/volvo2mqtt/assets/24524506/5c9732a2-69a1-4b8d-a213-f92b99dcf413)

**Comment by Dielee** [comment]
It would be possible to change this, but this is built as HA Addon, so I would leave it as it is. 

Your duplicated messages are no duplicates. One of them is the homassistant mqtt auto discovery, the other contains the data from the auto discoverd sensor.

**Comment by martin072** [comment]
Ok thanks for the quick reply!
