### ISSUE TITLE
Range and location not showing. 

### ISSUE THREAD

**Issue by walts22** [Dielee/volvo2mqtt#65]
Hi Dielee, again thank you for your great work on this!

Is there a trick to get it to show range?
Mine is functioning great, but doesn't pick up range or location like your examples.  

Is there something else I need to do in the Volvo Developer portal?

<img width="756" alt="2023_07_11_14_35_30_Settings_Home_Assistant" src="https://github.com/Dielee/volvo2mqtt/assets/87230803/a06555f7-7a37-4e89-b777-34b04b2ee055">

<img width="592" alt="2023_07_11_14_38_39_Account_Volvo_Cars_Developer_Portal" src="https://github.com/Dielee/volvo2mqtt/assets/87230803/a0e04c0c-6ff3-4621-952c-8b0e545b5dd6">

Note: Car is a 2023 XC40 Recharge Twin

**Comment by Dielee** [comment]
Please provide some debug logs. Pretty sure this is an Volvo API issue

**Comment by walts22** [comment]
Sure, nothing obvious in the logs since it is operating well. 
Just not collecting the range and location data.

On the Volvo developer site I am using an API application I made.  Do you think I need to "publish" this application to enable location and range data? 

Jul 11 15:30:09 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 15:35:09 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 15:35:11 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 15:40:11 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 15:40:14 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 15:45:14 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 15:45:17 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 15:50:17 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Refreshing credentials
Jul 11 15:50:17 volvo2mqtt [106] - INFO: Refreshing credentials
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 15:50:20 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 15:55:20 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 15:55:23 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 16:00:23 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 16:00:25 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 16:05:25 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 16:05:28 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
INFO:root:Sending mqtt update...
Jul 11 16:10:28 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 16:10:32 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.
Jul 11 16:15:32 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 16:15:34 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment]
This is not a debug log. Please enable debug and send the log as a file. 

I can't do anything if I can't see what's going on there.

**Comment by walts22** [comment]
Sorry, I still can't find the actual log file. But I have enabled debug mode and this is the new log:

      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "frontLeftTyrePressure" : {
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    }
DEBUG:root:Response status code: 200
  }
}
DEBUG:root:{
  "status" : 200,
  "operationId" : "20adac0a-8a9e-47a3-a09d-6d0d454e2795",
  "data" : {
    "rearLeftTyrePressure" : {
      "name" : "rearLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "rearRightTyrePressure" : {
      "name" : "rearRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "frontLeftTyrePressure" : {
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    }
  }
}
DEBUG:root:Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Jul 11 19:48:06 volvo2mqtt [106] - DEBUG: Response status code: 200
Jul 11 19:48:06 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "20adac0a-8a9e-47a3-a09d-6d0d454e2795",
  "data" : {
    "rearLeftTyrePressure" : {
      "name" : "rearLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "rearRightTyrePressure" : {
      "name" : "rearRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "frontRightTyrePressure" : {
      "name" : "frontRightTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    },
    "frontLeftTyrePressure" : {
      "name" : "frontLeftTyrePressure",
      "value" : "NORMAL",
      "timestamp" : "2023-07-11T07:54:18Z"
    }
  }
}
Jul 11 19:48:06 volvo2mqtt [106] - DEBUG: Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/engine-status
Jul 11 19:48:07 volvo2mqtt [106] - DEBUG: https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/LYVXZEDA6PL009989/engine-status HTTP/1.1" 200 226
DEBUG:urllib3.connectionpool:https://api.volvocars.com:443 "GET /connected-vehicle/v2/vehicles/LYVXZEDA6PL009989/engine-status HTTP/1.1" 200 226
Jul 11 19:48:07 volvo2mqtt [106] - DEBUG: Response status code: 200
DEBUG:root:Response status code: 200
DEBUG:root:{
  "status" : 200,
  "operationId" : "bd90b28e-eafb-4dc5-a668-c6ceb02c6dea",
  "data" : {
    "engineRunning" : {
Jul 11 19:48:07 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "bd90b28e-eafb-4dc5-a668-c6ceb02c6dea",
  "data" : {
    "engineRunning" : {
      "name" : "engineRunning",
      "value" : "false",
      "name" : "engineRunning",
      "value" : "false",
      "timestamp" : "1970-01-01T00:00:00Z"
    }
  }
      "timestamp" : "1970-01-01T00:00:00Z"
}
    }
  }
}
DEBUG:root:Updating icon to engine-off-outline for engine_state
Jul 11 19:48:07 volvo2mqtt [106] - DEBUG: Updating icon to engine-off-outline for engine_state
INFO:root:Mqtt update done. Next run in 300 seconds.
Jul 11 19:48:07 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment]
As said in the issue template, you can find your full log here `\\<Your HA IP>\addons\volvo2mqtt\log\volvo2mqtt.log`. I need the debug log from the addon start, after restarting the addon.

**Comment by walts22** [comment]
I would share the full logs if I could find them. 

I have tried to find that location in my HA file editor and just navigating in a web browser (with my HA ip first) and it just says 404: not found. 

Any hints with finding the log?
(If not you can just close this issue)

**Comment by Dielee** [comment]
You have to install and configure the smb share addon

**Comment by walts22** [comment]
> You have to install and configure the smb share addon
Sorry, this is the first time I've heard about this to find the Add On folder. 

Log file attached. Thank you for your help. 
[volvo2mqtt.log](https://github.com/Dielee/volvo2mqtt/files/12022022/volvo2mqtt.log)

**Comment by Dielee** [comment]
Thanks for the log. Unfortunately I can't do anything with the log, because you don't restarted the addon. As said above, I need the startup log, the first logs after the addon started. Stop the addon, delete the log file. Then start the addon and wait about 30 secs and send me the log. 
AND, I removed your file because it contains your car vin. Please remove all sensitive data from the file before uploading.

**Comment by walts22** [comment]
Sorry again, full log after restart here. 
I appreciate you removing the other log, my apologies.

[Log.txt](https://github.com/Dielee/volvo2mqtt/files/12024192/Log.txt)

**Comment by Dielee** [comment]
Jep, the whole energy API isn't supported by your car. Sorry, there is nothing I can do for you.

**Comment by walts22** [comment]
No problems, thanks for trying!
