### ISSUE TITLE
No respond after running the command

### ISSUE THREAD

**Issue by sanderhoeppermans** [Dielee/volvo2mqtt#72]
Hi,

Can someone help me out? I installed the HACS add-on with the URL (https://github.com/Dielee/volvo2mqtt). After that, I gave the following command (I used capital letters and bold font for the personal information):

docker run -d --pull=always -e CONF_updateInterval=300 -e CONF_babelLocale='nl_NL' -e CONF_mqtt='@json {"broker": "192.168.0.5", "username": “**PERSONAL E-MAIL**”, "password": “**PERSONAL PASSWORD**”, "port": 1883}' -e CONF_volvoData='@json {"username": “**PERSONAL E-MAIL**, "password": “**PERSONAL PASSWORD**”, "vin": “**VIN VOLVO CAR**”, "vccapikey": “**KEY FROM VOLVO API**”, "odometerMultiplier": 1, "averageSpeedDivider": 1, "averageFuelConsumptionMultiplier": 1}' -e TZ='Europe/Amsterdam’ --name volvo2mqtt ghcr.io/dielee/volvo2mqtt:latest

After running the command in the Terminal & SSH in home assistant there is no responding. Can some of you guys tell me what is wrong in the command above?

Thanks!

**Comment by Dielee** [comment]
You installed the ha addon and then started the raw docker install ?!

**Comment by sanderhoeppermans** [comment]
> You installed the ha addon and then started the raw docker install ?!
> 
> If you use the ha addon, there is no need to use the docker run command.

Thanks! Yes, I run the command because when I used the HA addon there is an error. I can't save the filled in configuration in the addon:

Failed to save add-on configuration, not a valid value. Got {'updateInterval': 300, 'babelLocale': 'nl_NL', 'TZ': 'Europe/Amsterdam', 'debug': False, 'mqtt': {'broker': '192.168.0.5.', 'port': 1883, 'username': 'auto_user', 'password': 'auto_password'}, 'volvoData': {'username': '**EMAIL**', 'password': '**PASSWORD**', 'vin': '**VIN**', 'vccapikey': '**API FROM VOLVO**', 'odometerMultiplier': 10, 'averageSpeedDivider': 10, 'averageFuelConsumptionMultiplier': 1}}

**Comment by sanderhoeppermans** [comment]
> Is your mqtt broker running also as HA Addon ?

Yes, I have a local MQTT broker (Mosquitto) and it's running in the HA addon.  I have an additional user for this broker. 

I filled in all the config fields as you can see below:

<img width="1010" alt="Scherm­afbeelding 2023-08-03 om 14 41 58" src="https://github.com/Dielee/volvo2mqtt/assets/121697071/c75b5073-d913-436f-a9b4-d51498fa2cd6">

Still get the following error:

Failed to save add-on configuration, not a valid value. Got {'updateInterval': 300, 'babelLocale': 'nl_NL', 'TZ': 'Europe/Amsterdam', 'debug': False, 'mqtt': {'broker': '**192.168**', 'port': 1883, 'username': 'MQTT', 'password': '**PASSWORD USER MQTT**'}, 'volvoData': {'username': '**E-MAIL VOLVO ON CALL APP**', 'password': '**PASSWORD VOLVO ON CALL APP**', 'vin': '**VIN VOLVO CAR**', 'vccapikey': '**API FROM VOLVO DEV SITE**', 'odometerMultiplier': 1, 'averageSpeedDivider': 1, 'averageFuelConsumptionMultiplier': 1}}

I don't understand what I'am doing wrong, but it can't be saved.

**Comment by Dielee** [comment]
So, if your mqtt broker runs on the same machine, just leave the mqtt config as it is.
```
    broker: "auto_broker"
    port: "auto_port"
    username: "auto_user"
    password: "auto_password"
```

Please read the instructions carefully:
`Leave the settings as they are if you are using the MQTT Mosquitto Addon. If not, take a look at the readme from volvo2mqtt.`

**Comment by sanderhoeppermans** [comment]
> So, if your mqtt broker runs on the same machine, just leave the mqtt config as it is.
> 
> ```
>     broker: "auto_broker"
>     port: "auto_port"
>     username: "auto_user"
>     password: "auto_password"
> ```
> 
> Please read the instructions carefully: `Leave the settings as they are if you are using the MQTT Mosquitto Addon. If not, take a look at the readme from volvo2mqtt.`

Thank you Dielee, it works! I'am sorry, havent' read the instructions carefully. Love the integration already :)!

**Comment by Dielee** [comment]
Nice! Have fun!
