### ISSUE TITLE
Estimated Charging Finished data in not available 

### ISSUE THREAD

**Issue by RobPijpers** [Dielee/volvo2mqtt#73]
After the installation of update 1.7.7 the sensor estimated_charging_finish_time has no data anymore.

**Comment by Dielee** [comment]
Please fill out the issue template and provide some logs. Without any information I can't do anything!

**Comment by Dielee** [comment]
Fixed with Version [v1.7.8](https://github.com/Dielee/volvo2mqtt/releases/tag/v1.7.8)
