### ISSUE TITLE
show vehicle diagnostics values

### ISSUE THREAD

**Issue by aerrow5** [Dielee/volvo2mqtt#75]
I would like to see the vehicle diagnostics published. These are available in Volvo's API via /vehicles/{vin}/diagnostics
I'll try to create a PR for this.

**Comment by bogdanbujdea** [comment]
great idea, and nice job with the PR! it's crazy how they have all these API's ready to be used but they don't add them to their official app...

**Comment by Dielee** [comment]
Thanks for your PR! 
Tested and merged. 
The feature is available by release v1.7.9.
