### ISSUE TITLE
Implement honk and flash 

### ISSUE THREAD

**Issue by bogdanbujdea** [Dielee/volvo2mqtt#77]
Is it possible to implement the endpoints from this page?
https://developer.volvocars.com/apis/connected-vehicle/v1/endpoints/lights-sound/#flash-exterior-lights

I tried using Postman to make these requests and I got a successful response, but nothing happened. I have a Volvo XC60 2023 T8, so it has AAOS, but I was expecting to get some error if that endpoint is not supported by my car. @Dielee maybe you can help here and point me in the right direction? If I can do this from Postman then I'll try to create a PR here as well!

**Comment by Dielee** [comment]
This endpoint won't work. I tried it multiple times, also with the V2 endpoint. Sorry, I can't help you. This seems to be a Volvo issue.

**Comment by bogdanbujdea** [comment]
I thought I'm not doing something right. Do you have any idea if this is something temporary? I'm thinking that maybe you had issues like this with other endpoints and they worked when they deployed a new version.
Anyway, it's weird that they don't give an error in the HTTP response.

**Comment by Dielee** [comment]
Yes, it's strange.. This feature never worked since I build this add-on. So maybe they will fix it. If it works, I will implement it, sure!

**Comment by bogdanbujdea** [comment]
Ok, then it doesn't make sense to keep this feature request open since there's nothing you can do about it, I'll close it for now!
