### ISSUE TITLE
2023 C40 BEV - Most EV sensors are not supported

### ISSUE THREAD

**Issue by jasonatepaint** [Dielee/volvo2mqtt#79]
**Describe the bug**

I am not sure if this is a bug or the C40 does not support the following sensors:

* Electric Range
* Estimated Charging Time
* Charging System Status
* Charging Connection Status
* Estimated Charging Finish Time

I am able to see these sensors in the Volvo Cars app so I know my car supports this functionality but the logs indicate no support.  

I have tried including a value for `vin` in the config and also w/no `vin`. In both situations, the results are the same; with all sensors functioning correctly.  The logs indicate a single API 404 failure with `vin not found`, which may indicate some sort of issue.

**Version info**:
1.7.8

**Logs**:
INFO:root:Starting volvo2mqtt version v1.7.8
Aug 05 14:26:11 volvo2mqtt [106] - INFO: Starting volvo2mqtt version v1.7.8
INFO:root:Vin: ['YV4ED3GM1P2041947'] found!
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Vin: ['xxxxxxxxxxxx'] found!
INFO:root:Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
INFO:root:Success! Battery Charge Level is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Battery Charge Level is supported by your vehicle.
INFO:root:Failed, Electric Range is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Electric Range is unfortunately not supported by your vehicle.
INFO:root:Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Estimated Charging Time is unfortunately not supported by your vehicle.
INFO:root:Failed, Charging System Status is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Charging System Status is unfortunately not supported by your vehicle.
INFO:root:Failed, Charging Connection Status is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Charging Connection Status is unfortunately not supported by your vehicle.
INFO:root:Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Estimated Charging Finish Time is unfortunately not supported by your vehicle.
INFO:root:Success! Odometer is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Odometer is supported by your vehicle.
INFO:root:Success! Last Data Update is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Last Data Update is supported by your vehicle.
INFO:root:Success! Active schedules is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Window Front Left is supported by your vehicle.
INFO:root:Success! Window Front Left is supported by your vehicle.
INFO:root:Success! Window Front Right is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Window Front Right is supported by your vehicle.
INFO:root:Success! Window Rear Left is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Window Rear Left is supported by your vehicle.
INFO:root:Success! Window Rear Right is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Window Rear Right is supported by your vehicle.
INFO:root:Success! Door Front Left is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Door Front Left is supported by your vehicle.
INFO:root:Success! Door Front Right is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Door Front Right is supported by your vehicle.
INFO:root:Success! Door Rear Left is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Door Rear Left is supported by your vehicle.
INFO:root:Success! Door Rear Right is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Door Rear Right is supported by your vehicle.
INFO:root:Success! Tailgate is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Tailgate is supported by your vehicle.
INFO:root:Success! Engine Hood is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Engine Hood is supported by your vehicle.
INFO:root:Success! Tank Lid is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Tank Lid is supported by your vehicle.
INFO:root:Success! Sunroof is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Sunroof is supported by your vehicle.
INFO:root:Success! Air Conditioning is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
INFO:root:Success! Lock state is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Lock state is supported by your vehicle.
INFO:root:Success! Force Update Data is supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
ERROR:root:API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "ea236f62-90a2-487e-9e96-c00775909a01",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
Aug 05 14:26:13 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  }
  "operationId" : "ea236f62-90a2-487e-9e96-c00775909a01",
}
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "VIN not found"
  }
}
INFO:root:Failed, Location is unfortunately not supported by your vehicle.
Aug 05 14:26:13 volvo2mqtt [106] - INFO: Failed, Location is unfortunately not supported by your vehicle.
INFO:root:Success! Tire Front Left is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Tire Front Left is supported by your vehicle.
INFO:root:Success! Tire Front Right is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Tire Front Right is supported by your vehicle.
INFO:root:Success! Tire Rear Left is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Tire Rear Left is supported by your vehicle.
INFO:root:Success! Tire Rear Right is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Tire Rear Right is supported by your vehicle.
INFO:root:Success! Engine State is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Engine State is supported by your vehicle.
INFO:root:Failed, Fuel Level is unfortunately not supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Failed, Fuel Level is unfortunately not supported by your vehicle.
INFO:root:Success! Average Fuel Consumption is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Average Fuel Consumption is supported by your vehicle.
INFO:root:Failed, Distance to Empty is unfortunately not supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Failed, Distance to Empty is unfortunately not supported by your vehicle.
INFO:root:Success! Average Speed is supported by your vehicle.
Aug 05 14:26:14 volvo2mqtt [106] - INFO: Success! Average Speed is supported by your vehicle.
INFO:root:Sending mqtt update...
Aug 05 14:26:17 volvo2mqtt [106] - INFO: Sending mqtt update...
INFO:root:Mqtt update done. Next run in 300 seconds.
Aug 05 14:26:17 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by Dielee** [comment]
Where do you come from ?

**Comment by jasonatepaint** [comment]
I am in the US.

**Comment by Dielee** [comment]
Yeah, then this is a country issue. I know a few C40 drivers in the USA. For all of them, those endpoints aren't working. This is a Volvo limitation. 

```
The API can be used with test credentials around the world. However, when published, only cars in the Europe / Middle East / Africa regions are available. We are working to bring other regions online.
```
[Source](https://developer.volvocars.com/apis/energy/v1/overview/)

There is nothing I can do for you, sorry.

**Comment by jasonatepaint** [comment]
Thanks for the info.  I'll keep an eye out for them to add support.

**Comment by bmesuere** [comment]
I'm sorry for replying to a closed issue, but I'm having the same problem with my MY24 XC40 in Belgium. 

The logs report a 404:
```
Aug 31 19:49:36 volvo2mqtt [106] - ERROR: API Call failed. Status Code: 404. Error: {
  "status" : 404,
  "operationId" : "xxxxxxxx",
  "error" : {
    "message" : "NOT_FOUND",
    "description" : "resource not found"
  }
}
Aug 31 19:49:36 volvo2mqtt [106] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
...
```

**Comment by Dielee** [comment]
Which endpoint is the problem ? Location ?

**Comment by bmesuere** [comment]
The first Battery Charge Level, Electric Range, Estimated Charging Time, Charging System Status, Charging Connection Status and Estimated Charging Finish Time.

**Comment by bmesuere** [comment]
As an FYI, these endpoints started working for me yesterday. I no longer receive an error.
