### ISSUE TITLE
vccapikey error

### ISSUE THREAD

**Issue by sschouten** [Dielee/volvo2mqtt#8]
when i want to install the docker i get this error:

File "/usr/local/lib/python3.9/site-packages/dynaconf/vendor/box/box.py", line 162, in __getitem__
    raise BoxKeyError(str(E)) from _A
dynaconf.vendor.box.exceptions.BoxKeyError: "'vccapikey'"

**Comment by sschouten** [comment]
<img width="682" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/cd008572-ad2a-4e03-9d76-8c1b2f94f239">
****

**Comment by sschouten** [comment]
<img width="682" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/5c2fee3b-76da-407f-957e-8aa8a6992c54">

**Comment by sschouten** [comment]
i used the docker pull on the site

**Comment by Dielee** [comment]
Your json from `CONF_volvoData` is definitely broken. 
Please recheck the notation. It should look like this:

`@json {"username": "yourMail@volvo.com", "password": "Your Password from Volvo", "vin": "", "vccapikey": "Your vccapikey from volvo developer"}`

**Comment by sschouten** [comment]
a nice :)
<img width="332" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/e9d8f94c-fcc1-45fc-a435-531bad1995dc">

it is working :)
<img width="353" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/30841665/bbd10709-3eed-4145-b3f2-ad43e728c67a">

**Comment by Dielee** [comment]
This seems to be my fault, wait a minute

**Comment by Dielee** [comment]
Please pull v1.0.7. It should work now!

**Comment by sschouten** [comment]
damm nice :):) finaly a working volvo solutions for homeassistant realy great work en tnx for the great support,
i will testing it the next few days and build some automations, and yes i will defently by some cofee for your great work

**Comment by Dielee** [comment]
Great! Thanks! Please let me know which car you are driving. So I can add this to readme :)

**Comment by sschouten** [comment]
i drive a volvo xc40 recharge single motor in the Netherlands

**Comment by Dielee** [comment]
Okay, 2023 model ?

**Comment by sschouten** [comment]
yes :)
