### ISSUE TITLE
Battery device class

### ISSUE THREAD

**Issue by Corsw** [Dielee/volvo2mqtt#87]
Would it be possible to add the device_class: battery to the battery_charge_level sensor? I would like this to let HA automaticly give colors to the tile card showing the charge level in lovelace.

**Comment by Dielee** [comment]
Good idea! I will take a look.

**Comment by Dielee** [comment]
Added function by release v1.8.3!

**Comment by Corsw** [comment]
Works brilliantly, thanks for the fast respons and adding this 👍
