### ISSUE TITLE
Battery_State -> unknown?

### ISSUE THREAD

**Issue by jvanderweken** [Dielee/volvo2mqtt#88]
Hi

volvo2mqtt works fine. But in the last UPDATE 1.8.3 --> Battery State is added.

The sensor battery State in my HA say unknown, and there is a difference to the other sensors, because all the other sensors are under the the code volvo_vin_**** .
But now for the Battery State the sensor is named under  volvo_battery_state. 
Is it normal? Or is there something missed? or is there a Bug,

Just for info I have a BEV XC40 2023

**Comment by AlexZuiderwijk** [comment]
Isn't this the Android Auto device battery state, similar to an Android
phone battery (I observed the same before)?

/Alex

Op vr 18 aug. 2023 18:14 schreef jvanderweken ***@***.***>:

**Comment by jvanderweken** [comment]
ok ok sorry, i didn't read very well the change is "device_class" it's ok
