### ISSUE TITLE
/data/options.json doesn't get loaded

### ISSUE THREAD

**Issue by mkrijtenberg** [Dielee/volvo2mqtt#89]
Hi,

I've noticed you use Dynaconf to load settings, and it's possible to read from a json file: /data/options.json
I have mounted a volume to /data and added an options.json file, but I have the impression it doesn't get loaded.

I'd like to load the settings from a json file, because it's easier to maintain :)

**Comment by Dielee** [comment]
Please share me your data.json file and your docker mount.

**Comment by mkrijtenberg** [comment]
Sorry for the late response, I was struck down with the flu. Anyway, I run the docker image on my NAS and use Portainer to configure everything:

![image](https://github.com/Dielee/volvo2mqtt/assets/101039/0e0ab7f0-83cd-419a-94f3-29469e5fb174)

And this is the contents from the **options.json** (not data.json):

```
{
    "updateInterval": 60,
    "babelLocale": "nl",
    "TZ": "Europe/Amsterdam",
    "mqtt": {
        "broker": "192.168.******",
        "port": 1883,
        "username": "mqttuser",
        "password": "********"
    },
    "volvoData": {
        "username": "*******@*****.com",
        "password": "*********",
        "vin": "",
        "vccapikey": [
            "*****************",
            "*****************",
            "*****************"
        ],
        "odometerMultiplier": "1",
        "averageSpeedDivider": "1",
        "averageFuelConsumptionMultiplier": "1"
    }
}

```

**Comment by mkrijtenberg** [comment]
AH! I've changed the filename to data.json, which resulted in a different error. This made me recheck the logs, and it did read my options.json, but the mqtt host was not reachable (different issue). 

So you can close this issue. Sorry for the trouble!
