### ISSUE TITLE
Unable to save configuration when having cellphone-number as username

### ISSUE THREAD

**Issue by skalman77** [Dielee/volvo2mqtt#91]
**Describe the bug**
I have my cellphone-number as username in Volvo app. This has not been a problem earlier, where i used format "+4670XXXXXXX" as username in the addon. But since some versions back i get an error when i try to save the config.

**To Reproduce**:<br>
1. Change username to a cellphone-number - i use "" as brackets. In my case i write the following in my config file
username: "+4670XXXXXX"

**Version info**:<br>
I use version 1.8.4

**Screenshot of error message**:<br>
![image](https://github.com/Dielee/volvo2mqtt/assets/3140624/a54598d8-96f8-4526-a40a-15db637491b3)

**Comment by Dielee** [comment]
Ah what ? It is possible to use a phone number as username ? Nevermind....

**Comment by skalman77** [comment]
> Ah what ? It is possible to use a phone number as username ? Nevermind....

Yes it is :). So there seems to be some kind of validation that restrict me from setting my phone number as usernmae. Is it possobile to change?

**Comment by Dielee** [comment]
Yes, already done. Fix will be up in a few minutes

**Comment by Dielee** [comment]
Please try v1.8.5!

**Comment by skalman77** [comment]
It’s working now. Thanks!
