### ISSUE TITLE
Cannot install as Add-on

### ISSUE THREAD

**Issue by iZac85** [Dielee/volvo2mqtt#92]
**Describe the bug**
When I try to install the add-on via by adding the repo to the add on store, I get the error message: 

```
Failed to install add-on
The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2
```

**To Reproduce**:<br>
1. Add repo 'https://github.com/Dielee/volvo2mqtt' in Add-on store
2. Refresh and find the Volvo2mqtt Add-on
3. Click on Install

**Expected behavior**:<br>
I expect the Add-on to be installed

**Screenshots**:<br>
<img width="1394" alt="image" src="https://github.com/Dielee/volvo2mqtt/assets/5288515/c346f310-a50e-4381-85d2-80f5646be0e3">

**Version info**:<br>
Version | core-2023.8.3
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.4
Operating System Family | Linux
Operating System Version | 5.10.103-v7l+
CPU Architecture | armv7l
Host Operating System | Raspbian GNU/Linux 10 (buster)
Update Channel | stable
Supervisor Version | supervisor-2023.08.1
Docker Version | 20.10.21

**Comment by Dielee** [comment]
As I can't reproduce this issue. Please take a look at the supervisor logs from your HA instance. Maybe this will point us to the right direction.

**Comment by iZac85** [comment]
Thanks for quick reply!
This is what I get from supervisor. Some kind of Python issue?

```
23-08-30 10:56:13 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 982ee2c4_volvo2mqtt
23-08-30 10:56:13 INFO (MainThread) [supervisor.docker.addon] Starting build for 982ee2c4/armv7-addon-volvo2mqtt:1.8.6
23-08-30 10:56:16 ERROR (MainThread) [supervisor.docker.addon] Can't build 982ee2c4/armv7-addon-volvo2mqtt:1.8.6: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2
23-08-30 10:56:16 ERROR (MainThread) [supervisor.docker.addon] Build log:
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> 89386b2d7696

Step 3/15 : RUN apk add --no-cache python3 bash py3-pip


 ---> Running in e256ab914e75

fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/armv7/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/armv7/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)

ERROR: unable to select packages:
  py3-pip (no such package):
    required by: world[py3-pip]
  python3 (no such package):
    required by:
 world[python3]
```

**Comment by Dielee** [comment]
This 
```
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)
```

looks like your HA cannot fetch data from `dl-cdn.alpinelinux.org`. Maybe a local DNS problem ?

**Comment by iZac85** [comment]
Thanks for pointing those out. There was no DNS issue but an issue related to that I'm running on a raspberrypi with 32bit os. I found the solution here:
https://community.home-assistant.io/t/supervisor-cant-install-add-ons/301771

**Comment by NiclasMol** [comment]
> Thanks for pointing those out. There was no DNS issue but an issue related to that I'm running on a raspberrypi with 32bit os and this add-on tries to build a docker image?
> 
> Anyway I found the solution here and could now install the add-on!: https://community.home-assistant.io/t/supervisor-cant-install-add-ons/301771

Same issue here. Can you describe what you did to fix it? There seem to be multiple different issues in the linked thread
