### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by julian-kemp** [Dielee/volvo2mqtt#95]
**Describe the bug**
Volvo2mqtt starts....... but is then stopped a few seconds later.

The MQTT service has found 1 device, and 39 entries 

The VIN number is displayed correctly - so I assume its loggig into my Volvo account correctly, and found my VIN number

All the devices are showing as "Unavailable"

**Screenshots**:<br>
I
<img width="648" alt="Screenshot 2023-09-03 at 17 54 34" src="https://github.com/Dielee/volvo2mqtt/assets/138529646/9b5d3cf9-e58b-4db7-9786-5072e521424e">
<img width="1056" alt="Screenshot 2023-09-03 at 17 56 26" src="https://github.com/Dielee/volvo2mqtt/assets/138529646/2279fcf5-afa1-4d68-82a7-987a714c378b">

**Logs**:<br>
Enable the debug option and upload your logfile here. <br>
<b>If you are using the HA Addon the log location is `\\<Your HA Host IP>\addons\volvo2mqtt\log\volvo2mqtt.log`

How do I enable debug option?

**Comment by julian-kemp** [comment]
OK - I found the log......

Looks like it receives confirmation from Volvo that the various features are supported - but its not receiving any data

<img width="892" alt="Screenshot 2023-09-03 at 18 04 21" src="https://github.com/Dielee/volvo2mqtt/assets/138529646/96e3936b-43af-4464-ae4a-677a29a74226">

**Comment by Dielee** [comment]
Please send the full debug log, not only a screenshot. On the screenshot, there is no issue visible.

**Comment by julian-kemp** [comment]
That's it - there is nothing else in the log - it just repeats (probably each time I restart the service)
There seems to be a gap after each "Sending matt update..

What I dont know is why the service is stopping - or why I am not getting any data!

**Comment by julian-kemp** [comment]
Looking at the Home-Assistant.log

When I start the service - I see messages, and it appears to be working, but then after a few seconds it goes "offline" and the service stops..

<img width="579" alt="Screenshot 2023-09-03 at 19 12 57" src="https://github.com/Dielee/volvo2mqtt/assets/138529646/1936c832-5c97-453d-9743-1e780771a794">

**Comment by Dielee** [comment]
You didn't enable the debug logging. Please toggle the "debug" switch inside the config. Also there should be a log from  the addon directly. Please share this also.

**Comment by julian-kemp** [comment]
Thanks for your help everyone - I found the problem and its now working!!

I had made a mistake in the "locale" setting.

When I viewed the log in the Volvo2Mqtt page in Home Assistant, I could see the error - looking at the log directly I couldn't see it!

Anyway - all good now, and I'm getting data from the car (and can lock and unlock it!)

Thanks again!
