### ISSUE TITLE
Disable logging until needed

### ISSUE THREAD

**Issue by billraff** [Dielee/volvo2mqtt#96]
Would it be possible to have a setting to disable logging until needed? Currently two lines are written to the log file in addons every X number of seconds (depending on when the refresh occurs). I'd like to see if we can disable until needed to troubleshoot a problem.

**Comment by Dielee** [comment]
Why do you need this feature ?

**Comment by billraff** [comment]
They cause a lot of sd card access and provide no value. I have no issue with warnings and errors being logged but would expect traces like these to only be needed if I enabled debugging.

**Comment by Dielee** [comment]
This option is available starting version v1.8.7. Please test!

**Comment by billraff** [comment]
Works wonderfully! Thanks for the work you do.
